### ISSUE TITLE
Problems with Vagrant installation

### ISSUE THREAD

**Issue by JoannaPearce** [adaptlearning/adapt_authoring#1000]
Hi am having problems trying to install the Adapt Authoring tool via Vagrant.

There are several errors coming through as it is trying to install, but then the last error terminates the install process.
See screenshot for the error which terminates the installation:
![vagrant_error](https://cloud.githubusercontent.com/assets/5995470/12495216/566f846a-c0f3-11e5-821f-2ffed5aff6a2.PNG)
Any help in troubleshooting this, would be much appreciated.

I'm running Windows 7.

Thanks

**Comment by brian-learningpool** [comment]
Hi @JoannaPearce, I see from your screenshot you're running this from Git Bash.  Were you running this as an Administrator?  (Installation will fail if it's not run as an Administrator.)

**Comment by JoannaPearce** [comment]
Hi, yes I was running it as administrator.
