### ISSUE TITLE
Problems installing Authoring Tool on Vagrant on Windows 10

### ISSUE THREAD

**Issue by hkalant** [adaptlearning/adapt_authoring#1006]
Hi there,

I'm trying to install the Adapt Authoring Tool through Vagrant. I followed all the steps in the wiki. But I get the following results.

![capture](https://cloud.githubusercontent.com/assets/2014422/12556897/1eca9132-c380-11e5-9b82-ca27625ef842.png)

I'm on Windows 10.

Any help hugely appreciated.

Thanks,
Harry

**Comment by brian-learningpool** [comment]
Hi @hkalant, thanks for reporting this.  We have had similar reports from other users running Windows 10  with the Vagrant install specifically and will try to get this resolved for the next release.

**Comment by Lockietoon** [comment]
Hi, I am having the same problem, I have just followed the same procedure on https://github.com/adaptlearning/adapt_authoring/wiki/Install-with-Vagrant

Has this been resolved yet. If not then when will the next release be?

Many thanks,

Haydn

**Comment by HikwaMehluli** [comment]
@brian-learningpool I have a similar problem
Vigrant and VirtualBox are installed and get success output after vigrant up, but when I visit 
http://localhost:5000 I get (image displayed below)

I am on windows 8.1 and using Chrome
![capture](https://cloud.githubusercontent.com/assets/11309006/15076478/24c4784e-13aa-11e6-8a7f-a929b026f373.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11309006/15076477/24c4503a-13aa-11e6-8608-48b23a4c7869.PNG)

**Comment by eish5000** [comment]
Hi all,

I am experiencing the exact same issue but with Windows 8.1. is there a known work around for that?

**Comment by affinitymc** [comment]
Same problem here, running Windows 10, tearing my hair out...lol

**Comment by desenvolvedorIcotrade** [comment]
Studio Visual code!
