### ISSUE TITLE
Remove defaulting of displayTitle for blocks

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#1025]
Blocks are usually only used for structural purposes and defaulting the `displayTitle` to 'Block title', while consistent with other elements, is unnecessary as it's typically removed right away.  I'm proposing that we remove the defaulting of this.

**Comment by johnniezen** [comment]
That would indeed save lots of fussing around, editing the block properties was an extra step not needed in most cases.

**Comment by brian-learningpool** [comment]
I agree. @johnniezen, this has made it for the 0.1.5 release.
