### ISSUE TITLE
Courses can't be opened on mobile OS

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1044]
Tried to use the AT on both my Android smartphone and on a iPad. When at the dashboard you are unable to open a course as the double-click on the course to open it just re-sizes the screen instead.

**Comment by taylortom** [comment]
We don't support mobile devices at the moment, so parking this one.

**Comment by taylortom** [comment]
There's currently no plan to enable the authoring tool on mobile devices, so closing this one.
