### ISSUE TITLE
Course is not connected to the LMS window appears in Preview each time v1.0.5

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1045]
AT 1.0.5
framework 2.0.7

Every time I preview I get the course is not connected to the LMS window.
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/index.html#L7-L11 are present in the page source
offline_API_wrapper.js does seem to be included in the preview.

**Comment by brian-learningpool** [comment]
@taylortom, what's the status of this?

**Comment by hmaffin** [comment]
Sorry for leaving this open - were you able to replicate? If not then I wouldn't worry as it's only seemed to have affected one of my legacy courses, not new builds....

**Comment by taylortom** [comment]
Haven't been able to replicate this in recent releases (can't remember why I assigned this to myself....)
