### ISSUE TITLE
Add permissions to /user/resetpassword route

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1057]
Currently only accessible to @learningpool.com users.
https://github.com/adaptlearning/adapt_authoring/blob/master/lib/usermanager.js#L755

**Comment by ryan-lynch** [comment]
Sorry I've just seen this issue. I have another issue (#1147) for this and raised a Pull Request for it here: https://github.com/adaptlearning/adapt_authoring/pull/1148

**Comment by taylortom** [comment]
Duplicate (and fixed)
