### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#1062]
Describe changes to the logon screen here.

**Comment by simondate** [comment]
![login screen](https://cloud.githubusercontent.com/assets/1676635/13355536/cbc6307c-dc98-11e5-9c38-efe2dc3e3d46.jpg) - proposed Art Direction

**Comment by simondate** [comment]
![login screen implementation](https://cloud.githubusercontent.com/assets/1676635/13359089/44fc348a-dcaa-11e5-9d62-9a31ae0d57bd.jpg) - current implementation

**Comment by taylortom** [comment]
This issue has been superseded by several newer tickets it seems: 
- [ ] https://github.com/adaptlearning/adapt_authoring/issues/1159
- [ ] https://github.com/adaptlearning/adapt_authoring/issues/1163
- [ ] https://github.com/adaptlearning/adapt_authoring/issues/1208
