### ISSUE TITLE
Login detecting an existing email address

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1084]
The login should be able to detect if the email exists so a different error prompt can be shown warning the users password is wrong not email.

**Comment by simondate** [comment]
This feature has been designed in @messyp 's mock up for design refresh.
![simondatescreenshot 3](https://cloud.githubusercontent.com/assets/1676635/13534992/bd9db776-e22f-11e5-87f3-0032078d4622.jpg)

**Comment by brian-learningpool** [comment]
I'm not sure about this one as it potentially opens up security issues, pretty much that we reveal to anyone who has and doesn't have an account.

**Comment by taylortom** [comment]
wontfix
