### ISSUE TITLE
Safeguarding/LMS issue

### ISSUE THREAD

**Issue by CollDevBrom** [adaptlearning/adapt_authoring#1086]
Hi there, 

I just opened the Safeguarding course from the Adapt builder. As soon as I preview it I get an error saying: 
Course could not connect to the LMS
ScormWrapper::getValue: _property=cmi.suspend_data
Course is not connected to the LMS

And every time I click on a question/answer I get an error:
Course could not connect to the LMS
ScormWrapper::getValue: _property=cmi.suspend_data
Course is not connected to the LMS
ScormWrapper::setValue: _property=cmi.suspend_data _value={"spoor":{"completion":"-00000100000000000000000000000000000","_isCourseComplete":false,"_isAssessmentPassed":false}}
Course is not connected to the LMS

**Comment by CollDevBrom** [comment]
I also get errors for 'Safeguarding and child protection for non-children service workers' and for Smoking awareness

**Comment by brian-learningpool** [comment]
Hi @CollDevBrom, I think you may have posted this in the wrong place.

This is the issues list for the open source Adapt authoring tool project, which does not come bundled with any courses.  If you're looking for support Learning Pool content please contact Learning Pool support directly.
