### ISSUE TITLE
preview fails running vagrant on windows

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#1087]
Error in console:

adapt-0 (err): error: [07 Mar 2016 11:19:15 +00:00] Error: EACCES: permission denied, mkdir '/home/vagrant/temp/56dd62fe69beb9c538c4dff1/adapt_framework/courses'
adapt-0 (err): error: [07 Mar 2016 11:19:15 +00:00] Error: EACCES: permission denied, mkdir '/home/vagrant/temp/56dd62fe69beb9c538c4dff1/adapt_framework/courses'
adapt-0 (err): error: [07 Mar 2016 11:21:06 +00:00] Error: EACCES: permission denied, mkdir '/home/vagrant/temp/56dd62fe69beb9c538c4dff1/adapt_framework/courses'
adapt-0 (err): error: [07 Mar 2016 11:21:06 +00:00] Error: EACCES: permission denied, mkdir '/home/vagrant/temp/56dd62fe69beb9c538c4dff1/adapt_framework/courses'

**Comment by brian-learningpool** [comment]
@lc-thomasberger, does the account have write permission on that folder?

**Comment by lc-thomasberger** [comment]
ran cmd as admin
files located at: C:\vagrant\
