### ISSUE TITLE
Add support for v4.5.7 of CKEditor and default Adapt Framework to v2.0.6

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#1109]
We should keep up to date with patch releases in order to ensure we have the latest bug fixes.

**Comment by johnniezen** [comment]
If you start the AT in the browser, it would be good if the version check is also done. So you are aware of updates. I can imagine that lots of content creators do not check their Plugin Management part regular, and this could help them stay with the latest versions.

**Comment by dancgray** [comment]
Fixed here https://github.com/adaptlearning/adapt_authoring/pull/1111
