### ISSUE TITLE
Install should not exit if plugin framework supported version is greater than the installed framework version.

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1110]
Example:

Authoring tool installs framework v2.0.1
latest version of Trickle requires framework v2.0.6
the install fails with output something like
```Unable to install adapt-contrib-trickle as it is not supported in the current version of of the Adapt framework ERROR: Unable to install adapt-contrib-trickle as it is not supported in the current version of of the Adapt framework Install was unsuccessful. Please check the console output.```

Suggest that this should just log an error and go to the next core plugin in adapt.json.

**Comment by MattPostlethwaite** [comment]
I got this message after a lot of failure attempts I found that in the `CHANGELOG.mg` of version 0.1.5 it stated:
```
### Added
- Support for v2.0.7 of the Adapt Framework
```

Although the `version.json` file was still getting `"adapt_framework": "v2.0.1"`

After changing this to `"adapt_framework": "v2.0.7"` and running the `node install` again it successfully installed and everything seems to run fine now.
