### ISSUE TITLE
Authoring tool does not surface attributes defined in properties.schema for menu plugins

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1116]
Some menus will have editable attributes e.g https://github.com/cgkineo/adapt-cover-menu

**Comment by brian-learningpool** [comment]
I think this would be a great addition.  👍

**Comment by taylortom** [comment]
Very useful feature. Suggest we open this up to all BowerPlugins (particularly menus and themes).
- [Content creation hook](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/extension/index.js#L513-L520)
- [Storing pluginLocations](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/extension/index.js#L263-L267)

**Comment by samumist** [comment]
+1 for this feature.

**Comment by EdwardHinkle** [comment]
Any word on a timeline for this?

**Comment by taylortom** [comment]
@EdwardHinkle it's on the roadmap, but dates in the diary.

**Comment by taylortom** [comment]
Some modifications for this are included in https://github.com/adaptlearning/adapt_authoring/pull/1499
