### ISSUE TITLE
An asset's description shouldn't be required

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1120]

**Comment by davetaz** [comment]
Any update on this one as it is breaking my PR to #1620 as everything is required by default regardless of config? As the framework is bumping to 2.1.0 today it would be good to have the asset manage able to manage attribution in the framework based upon the upgrades to components I have added.

**Comment by taylortom** [comment]
@davetaz it should already be in develop

**Comment by davetaz** [comment]
So this is not fixed as in the tests it sets an asset description. If you remove this from the test data then the travis build will fail as the description is still required and the validation error fails.
