### ISSUE TITLE
Notice of deprecated modules on install

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#1121]
Maybe we can tidy these up?

**Comment by hrajotia** [comment]
![image](https://cloud.githubusercontent.com/assets/6231183/14012870/ceb117b6-f1ce-11e5-8ffd-b3624658cf74.png)

**Comment by dancgray** [comment]
`npm WARN deprecated phantom@0.6.6: v1 is no longer maintained, please upgrade to v2.0+ as soon possible.
npm WARN deprecated URIjs@1.12.1: package renamed to "urijs" (lower-case), please update accordingly
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated lodash@2.3.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

**Comment by dancgray** [comment]
![screen shot 2016-03-29 at 11 25 54](https://cloud.githubusercontent.com/assets/6452430/14105053/0c4f844c-f5a1-11e5-80ec-c9fbccb21eb8.png)

**Comment by dancgray** [comment]
unzip (used by bower plugin) has not been updated for 2 years and has sub dependency on old graceful-fs. Perhaps this can be changed to decompress-zip?

**Comment by brian-learningpool** [comment]
@dancgray, yes, I think this makes sense.

**Comment by dancgray** [comment]
@brian-learningpool some of the deprecated modules are sub dependencies of json-schema-mapper.
Have made a [PR for that repo](https://github.com/LearningPool/json-schema-mapper/pull/2)

The lodash warning is coming from the [grunt-requirejs-bundle](https://github.com/cajones/grunt-requirejs-bundle) i think.

**Comment by taylortom** [comment]
Out-of-date, see https://github.com/adaptlearning/adapt_authoring/issues/1704
