### ISSUE TITLE
Heroku installation improvements

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1139]
I've managed to get this working (and am writing a quick wiki instructions page as I go), but there are a few issues with the current installation process that make it a bit more difficult than necessary to install on Heroku.

**_So_**, I have a few questions about how things work (@brian-learningpool @dennis-learningpool):
- What's the best way to set the relevant config options (db: user, pass, port, URL etc. etc.). I'd prefer not to have to go through the command line input for Heroku. I'm _thinking_ this can be done in config.json, although I'm not 100% sure how that file fits into everything.
- We need to allow for dynamic port setting, which is stored in `process.env.PORT`. In my test, I just added this [here](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/application.js#L482). Is there a better way?
- What's the ['minimal'](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/application.js#L251) server config used for? This caused me a few errors initially (I think this code was running for my Heroku test because I'd pushed a very basic config.json) -- an error was being thrown by serve-favicon, which seems to have been [commented out](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/application.js#L290) for the non-minimal config. It worked fine once I added the full config.json.
- What's the .env file used for (it contains all of the same attributes as stored in configuration/config.json) -- foreman has been replaced in the heroku toolbelt, so not sure if this is still required.
- I propose the removal of the Procfile in favour of adding the relevant fields to the package.json. Is there any reason the seperate Procfile is preferable?

I think ideally, the process for a Heroku (and possibly any) install would be to populate the config.json file, followed by running `node install`, which reads in said file, and skips the prompt inputs for any fields found in the config.

**Comment by brian-learningpool** [comment]
Hi @taylortom, I'm not sure if I can answer all of your questions, as I've not really used Heroku.

- All those things can be configured in config.json.
- The port can also be defined in config.json.
- I'm not sure what the 'minimal' config is used for these days.  It's possibly been there since before I started working on the project and could probably be removed.

Note that you can default the config.json by passing the values to the install script the way the Vagrant installation does it.

**Comment by dancgray** [comment]
@taylortom @brian-learningpool don't we also need a file storage plugin (AWS S3) as heroku file storage is temporary.
