### ISSUE TITLE
1. Login page - background

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1159]
Background image needs to use the ‘cover’ attribute as it does not tile.

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Fixed in 5417a3704f2d1d6a2ea20184308b25adb284e8bd

**Comment by michael-palmer** [comment]
We not seeing this on https://adapt-at.herokuapp.com?

**Comment by simondate** [comment]
added background-size: cover attribute

**Comment by michael-palmer** [comment]
not seeing this one?

**Comment by simondate** [comment]
This attribute is definietly here. Just tested on over 1920px wide and looks good.

**Comment by michael-palmer** [comment]
There is still something amiss with the background tiling even though the 'background-size:cover;' attribute is there .. maybe try applying the background to a different element (html, body)?

![screen shot 2016-06-23 at 09 45 12](https://cloud.githubusercontent.com/assets/946424/16297134/66c2be02-3927-11e6-9a49-5985449b1143.png)
