### ISSUE TITLE
2. Login page - title

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1160]
Currently title says ‘Login’ please change this to ‘Sign in’ and ensure central alignment of text with the form below.

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Fixed in 5417a3704f2d1d6a2ea20184308b25adb284e8bd

**Comment by michael-palmer** [comment]
all good .. thanks
