### ISSUE TITLE
3. Login page - form text

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1161]
‘E-mail address’ and ‘Password’ text size is too large and is displaying grey in Chrome (needs to be white).

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Added padding and changed placeholder text to white in chrome. 5417a3704f2d1d6a2ea20184308b25adb284e8bd

**Comment by michael-palmer** [comment]
please reduce size of ‘E-mail address’, ‘Password’ and 'Login' text to 20px

**Comment by simondate** [comment]
Decreased to 20px

**Comment by michael-palmer** [comment]
looks good
