### ISSUE TITLE
4. Login page - forgot password

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1162]
'Forgot your password?' is currently displayed with a button style, please change this to a standard link.

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Changed to standard link 5417a3704f2d1d6a2ea20184308b25adb284e8bd

**Comment by michael-palmer** [comment]
done
