### ISSUE TITLE
5. Login page - remember me and forgot password

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1163]
Currently the 'remember me' text and checkbox is aligned left and 'forgot your password?' is aligned right. Please centre align both of these elements (see design).

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Updated here 5417a37 may require more padding

**Comment by michael-palmer** [comment]
not seeing this one yet?

**Comment by simondate** [comment]
Added padding to both sides to center them.

**Comment by michael-palmer** [comment]
'remember me' and 'forgot your password?' look different sizes?
![screen shot 2016-06-07 at 13 56 02](https://cloud.githubusercontent.com/assets/946424/15858275/99435480-2cb7-11e6-8eac-a35b1f1adfec.png)

**Comment by simondate** [comment]
Fixed 5366d33

**Comment by michael-palmer** [comment]
looks good

**Comment by michael-palmer** [comment]
any reason why we reopened this one?
