### ISSUE TITLE
6. Login page - form padding

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1164]
The text within the login form, 'Email address' and 'Password', needs more horizontal padding (see design).

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Added padding 5417a3704f2d1d6a2ea20184308b25adb284e8bd

**Comment by michael-palmer** [comment]
all good .. thanks
