### ISSUE TITLE
7. Login page - login button

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1165]
The text within the button 'Login' is too small, it should be the same size as the form text (see design).

Original design:
https://invis.io/WX5UHY0HC#/96193103_login

Comments on screenshot:
https://invis.io/SF73OS0YH#/153992360_Adapt-Authoring-Tool
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Incrreased size 5417a3704f2d1d6a2ea20184308b25adb284e8bd

**Comment by michael-palmer** [comment]
text to 20px
#1161

**Comment by simondate** [comment]
Decreased to 20px

**Comment by michael-palmer** [comment]
looks good
