### ISSUE TITLE
1. Dashboard - header

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1168]
Please can we use a we use a slightly different graphic strip within the header so the blue is lighter (see design)? Graphic can be supplied if you can provide the dimensions.

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
@messyp

**Comment by simondate** [comment]
1920x60 px

**Comment by michael-palmer** [comment]
can we keep the current graphic but align the background to the right edge?

if you resize your window to a large width, you can see a lighter part of the blue background, we want this to always be behind the logout button even at small window sizes

**Comment by simondate** [comment]
Can we create the banner at 2560*60px instead for 4k/dual monitors?

**Comment by michael-palmer** [comment]
requested from Paul

**Comment by simondate** [comment]
Added `background-position: right` 7e72ea8

However on screens over 1920px it still has a jarring line that appears.

![image](https://cloud.githubusercontent.com/assets/1676635/15861348/0b73a65c-2cc4-11e6-9bb8-44b56e7e6ee7.png)

**Comment by michael-palmer** [comment]
requested comment from Paul

**Comment by messyp** [comment]
new image saved in source folder on invision @simondate

**Comment by simondate** [comment]
Support added. Also created a 1080x60 image to reduce loading the full screen image.
