### ISSUE TITLE
2. Dashboard - menu icon

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1169]
Please change the menu icon to standard hamburger icon (fa-navicon [&#xf0c9;]).

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Changed in 60c311aa4a6b6b8046c116c0faa3257b6975b823

**Comment by michael-palmer** [comment]
looks better but still a little to thin and chunky

please try:

#global-menu-icon span {
height: 2px;
width: 22px;
}

**Comment by simondate** [comment]
![simondatescreenshot 3](https://cloud.githubusercontent.com/assets/1676635/15752282/5c12e8e4-28e5-11e6-9e02-f57931b16148.jpg)  Changed but concerned this is too thin?

**Comment by michael-palmer** [comment]
agreed .. can you try 'height: 3px;'

**Comment by simondate** [comment]
Changed to 3px 2f9e253

**Comment by michael-palmer** [comment]
looks good
