### ISSUE TITLE
3. Dashboard - nav drawer top padding

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1170]
There is a large gap at the top of the navigation drawer, please reduce this as per the designs.

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
see 	3fcc29f

**Comment by michael-palmer** [comment]
fixed .. thanks
