### ISSUE TITLE
4. Dashboard - nav drawer items padding

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1171]
Please reduce the padding between the > icon and the text.

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Changed to 8px 29274b09bf7e072cc3186b8241e3f4b14698076c

**Comment by michael-palmer** [comment]
done .. thanks
