### ISSUE TITLE
6. Dashboard - course items

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1173]
The boxes that contain each course item are missing the drop shadow (see design).

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Added 60c311aa4a6b6b8046c116c0faa3257b6975b823

**Comment by michael-palmer** [comment]
all good .. thanks
