### ISSUE TITLE
7. Dashboard - sort by icons

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1174]
Please ensure all icons are centrally aligned with each label, Last updated is out of alignment.

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Changed text to 'recent' now center aligned. 72370ec127d7195c61fb940627de60ac75631df6

**Comment by michael-palmer** [comment]
looks good .. thanks
