### ISSUE TITLE
9. Dashboard - nav drawer button

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1176]
The ‘Add new course’ button doesn’t appear centrally aligned as it is slightly too narrow. Please increase the width so it appears to sit perfectly in the centre.

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Fixed 60c311aa4a6b6b8046c116c0faa3257b6975b823

**Comment by michael-palmer** [comment]
not seeing this?

currently there is more space to the right of the button than there is on the left

**Comment by simondate** [comment]
Moved the button primary and secondary buttons right by 5px to be center aligned. This may need to be done with other sidebar objects too.

**Comment by michael-palmer** [comment]
looks good
