### ISSUE TITLE
10. Dashboard - logged in username

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1177]
In the header the logged in username is displayed without a label, please can we change this to ‘Signed in as [username]’

Original design:
https://invis.io/WX5UHY0HC#/140022793_Dashboard

Comments on screenshot:
https://invis.io/SF73OS0YH#/153994421_Projects
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Added 60c311aa4a6b6b8046c116c0faa3257b6975b823

**Comment by michael-palmer** [comment]
looks ok .. thanks
