### ISSUE TITLE
Should Vagrantfile be set to ubuntu/trusty64?

### ISSUE THREAD

**Issue by DivByZRo** [adaptlearning/adapt_authoring#1178]
This is the current setting in vagrantfile:

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"

The install instructions say that Vagrant will install ubuntu/trusty64. I had issues getting adapt AT to install on Windows 10. This is one of the changes I made to finally get the install to work.

Thanks

**Comment by lc-thomasberger** [comment]
64 bit OS requires VT-x or other virtualization technology, this caused issues for some Windows users so we moved to 32 bit.
