### ISSUE TITLE
1. Settings page - section titles

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1180]
At the minute the section titles within the page (‘General’ ‘Settings’ etc) are displayed with a dark background colour. Please can you remove the background colour, increase the size of the title slightly and add a 1px light grey border underneath.

Original design:
https://invis.io/WX5UHY0HC#/140022871_Settings

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by michael-palmer** [comment]
looks better but still doesn't quite feel right

using Paul's design as guidance (https://invis.io/WX5UHY0HC#/135703371_Edit-Course) .. can you add a white background to each fieldset plus a 30px margin and the standard drop shadow so we visually separate each group into blocks

then we can remove the border from the legend

**Comment by simondate** [comment]
Added white background, drop shadow and width to each fieldset. Added extra padding around the title to make it stand out more. 577dc9e

**Comment by michael-palmer** [comment]
![screen shot 2016-06-07 at 13 46 06](https://cloud.githubusercontent.com/assets/946424/15858007/4b75adee-2cb6-11e6-918d-2df15c86ffa6.png)
can you increase the size of the fieldset title?

**Comment by simondate** [comment]
Increased by 2px. Also reduced bottom padding by 5px. 2f9e253

**Comment by michael-palmer** [comment]
looks good
