### ISSUE TITLE
2. Settings page - nav drawer top padding

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1181]
There is a large gap at the top of the navigation drawer, please reduce this as per the designs.

This issue is also captured in #1170 

Original design:
https://invis.io/WX5UHY0HC#/140022871_Settings

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by simondate** [comment]
3fcc29f

**Comment by michael-palmer** [comment]
looks good
