### ISSUE TITLE
3. Settings page - nav drawer title

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1182]
Please remove the project settings title that is displayed above the ‘Save’ and ‘Cancel’ buttons.

Original design:
https://invis.io/WX5UHY0HC#/140022871_Settings

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by simondate** [comment]
944fec2

**Comment by michael-palmer** [comment]
looks good
