### ISSUE TITLE
4. Settings page - nav drawer filters title

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1183]
Please remove the ‘Filters’ icon and title (see design).

Original design:
https://invis.io/WX5UHY0HC#/140022871_Settings

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by michael-palmer** [comment]
can you add some space between the buttons and the filters (see the design)

**Comment by simondate** [comment]
Added in 040a229

**Comment by michael-palmer** [comment]
looks good
