### ISSUE TITLE
8. Settings page - Start title

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1187]
I was a little confused by this title, can we rename it to ’Start controls’ please.

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Couldn't find this file anywhere. @brian-learningpool can you assist?

**Comment by simondate** [comment]
Deleted the second title "Start settings:" cf11288

As for the main title name @taylortom  has advised it may be a bit trickier due as the name of the title inherits from the object. We can't just change this as it will break other things.

I suggest that we delay a renaming until the next refresh.

**Comment by michael-palmer** [comment]
ok
