### ISSUE TITLE
9. Settings page - textarea

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1188]
Please add rounded corners to the text areas so it is consistent.

Original design:
https://invis.io/WX5UHY0HC#/140022871_Settings

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Done as much as I can but a bit tricky due to different implementations of buttons.

**Comment by michael-palmer** [comment]
nice
