### ISSUE TITLE
10. Settings page - select box

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1189]
In Firefox the select boxes display fine but in Pauls screenshot (which i believe is Chrome) they display smaller and without padding.

Original design:
https://invis.io/WX5UHY0HC#/140022871_Settings

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998406_New-Course
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Think this has been addressed by increasing text size.

**Comment by michael-palmer** [comment]
still looks different in Chrome

**Comment by simondate** [comment]
These generic form fields all are rendered differently by the browser and the operating system. Not much we can do to make them look exactly identical.

**Comment by michael-palmer** [comment]
ok .. closing off this issue
