### ISSUE TITLE
1. Course structure page - dividing line

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1191]
The dividing line between columns needs to be a thin 1px line, colour value #ddf2fa

Original design:
https://invis.io/WX5UHY0HC#/109479794_Structure

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998480_Menu-Editor
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Changed.

**Comment by michael-palmer** [comment]
looks good
