### ISSUE TITLE
4. Course structure page - add buttons

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1193]
Please reduce the vertical padding within the ‘Add page’ and ‘Add section’ buttons. Please include the page and folder icons, both buttons should also be in the same blue (see design).

Original design:
https://invis.io/WX5UHY0HC#/109479794_Structure

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998480_Menu-Editor
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Made the change. a654690

![simondatescreenshot 5](https://cloud.githubusercontent.com/assets/1676635/15821222/6a91a53c-2be6-11e6-859a-575f4022bf61.jpg)

To be honest I'm not really very keen on this change as it breaks the design of the buttons. The buttons appear on the whole AT as a primary action button which is filled and a secondary action button which is hollow. The whole AT uses this design and this change conflicts with it. 

Will be happy to discuss this with you further.

**Comment by michael-palmer** [comment]
in this instance it's difficult to define which is the primary and secondary action but if we were i'd say the 'add page' is primary .. try it if you like .. also please can you change the icons within these buttons to the ones shown on the original design

**Comment by simondate** [comment]
Discussed this issue on the call last Tuesday. We decided that there should be no icons and primary and secondary button. 77b28fd

**Comment by michael-palmer** [comment]
Sorry but i disagree that the icons should be removed as they give context to the items they create

**Comment by simondate** [comment]
Added icon back 3bfab85

**Comment by michael-palmer** [comment]
Please use the solid version of the icons that are shown on the designs

- fa-file - for the page
- fa-folder - the section

Add section has been changed to 'Add sub menu'?

I'm also seeing an alignment / display issue on the buttons

![screen shot 2016-06-23 at 09 28 10](https://cloud.githubusercontent.com/assets/946424/16296601/e577e9aa-3924-11e6-8579-3f903e54a7bc.png)

**Comment by simondate** [comment]
Fixed the screenshot above by reducing padding (seemed to be problem in Firefox only)

Not sure about the icons being filled. I personally think the left one looks better filled. Can someone else give their opinion?

**Comment by taylortom** [comment]
Don't really mind either way. Swaying towards filled as @michael-palmer suggested.

**Comment by michael-palmer** [comment]
go with the filled versions .. you know you want to :)

personally i think the filled versions work better at the small size and the outlined versions work better at the large size
