### ISSUE TITLE
5. Course structure page - page and section blocks

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1194]
The icon with the page/section blocks should be aligned to the left and vertically aligned to the middle of the page/section name (see design).

Original design:
https://invis.io/WX5UHY0HC#/109479794_Structure

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998480_Menu-Editor
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Fixed in 129f0ee and f86b63a

**Comment by michael-palmer** [comment]
looks good
