### ISSUE TITLE
6. Course structure page - page and section block shadow

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1195]
Please add the drop shadow to the page and section blocks, same values as the dashboard.

Original design:
https://invis.io/WX5UHY0HC#/109479794_Structure

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998480_Menu-Editor
(bottom right click to turn comments on)

**Comment by michael-palmer** [comment]
There should also be no border .. use the same code as the dashboard

**Comment by simondate** [comment]
Fixed in

**Comment by michael-palmer** [comment]
looks good
