### ISSUE TITLE
8. Course structure page - column backgrounds

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1197]
When viewing a new section, the column background colours should alternate from #f3fcfe to #f1f9fb (see design).

Original design:
https://invis.io/WX5UHY0HC#/109479794_Structure

Comments on screenshot:
https://invis.io/SF73OS0YH#/153998480_Menu-Editor
(bottom right click to turn comments on)

**Comment by simondate** [comment]
Added 2cbd4af.

**Comment by michael-palmer** [comment]
looks good
