### ISSUE TITLE
Page editor

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1198]
Please follow the original design to retheme the page editor screen.

Original design:
https://invis.io/WX5UHY0HC#/140022866_Page

Current screenshot:
https://invis.io/SF73OS0YH#/154004313_Page-Editor

**Comment by simondate** [comment]
Pretty happy with what's here but need designer to look into the hover and active states. 58723bb

**Comment by michael-palmer** [comment]
looks good to me .. happy to close
