### ISSUE TITLE
General - font family

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1199]
The original Raleway font (https://www.google.com/fonts/specimen/Raleway) has been replaced by Arial. 

Please can we talk about these issues and use this ticket to track alternatives if Raleway is not suitable.

**Comment by simondate** [comment]
A few people thought that Raleway looked good for websites but wasn't really very good for working with. One issue was how numbers are rendered in Raleway. @brian-learningpool any further insights?

**Comment by simondate** [comment]
Perhaps a good idea would be to pair with another font? https://www.google.com/fonts/specimen/Raleway#pairings

**Comment by michael-palmer** [comment]
Can we try the pairing of Raleway for titles and open sans for everything else

**Comment by corymayfield** [comment]
Raleway is a rather wide font and can be difficult to read in some circumstances. I recommend using Roboto which is also part of the Google Fonts library. It also contains a condensed width too. It will also resonate well with Android users as this is also the font Google defaults to with a backup to Helvetica then Arial.

**Comment by simondate** [comment]
Changed to Open Sans for body text and Raleway regular for the location and title bars. 19f7663

**Comment by taylortom** [comment]
Leaving this open for the rewrite.
Also see https://github.com/adaptlearning/adapt_authoring/issues/1223
