### ISSUE TITLE
General - nav drawer buttons

### ISSUE THREAD

**Issue by michael-palmer** [adaptlearning/adapt_authoring#1200]
The gap between the primary and secondary buttons in the nav drawer (for all pages) needs reducing slightly (see design).

Original design example:
https://invis.io/WX5UHY0HC#/140022866_Page

Current screenshot example:
https://invis.io/SF73OS0YH#/154004313_Page-Editor

**Comment by simondate** [comment]
Reduced. Please advise how much space you want between these buttons and the items below them.

**Comment by michael-palmer** [comment]
looks good
