### ISSUE TITLE
feature request : Hide the Show Feedback button if it is turned off!

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1201]
In the Authoring Tool even if in Assessment settings I have show feedback set to false all it does is grey out the button.
Can we have it so that the button is not shown, and the Submit/Reset button is shown full width?

Something to do with _canShowFeedback for the component?

**Comment by moloko** [comment]
@hmaffin this isn't really an authoring tool issue - would you mind logging it in the [framework repository](https://github.com/adaptlearning/adapt_framework/issues)?

**Comment by brian-learningpool** [comment]
Closing the issue per @moloko's comment.
