### ISSUE TITLE
Login Page - error validation

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1208]
@michael-palmer @messyp If a user enters their email or password incorrectly a error validation message comes up. However it is currently not positioned at all.

Do you have any suggestions of how to show this error message? We could just have a X inside the email address box?

**Comment by taylortom** [comment]
Spacing off here ![screen shot 2016-06-16 at 11 51 20](https://cloud.githubusercontent.com/assets/1059083/16114363/b90c3eb4-33b8-11e6-9839-55bf8f5fcef8.png)

**Comment by messyp** [comment]
there is already AD for this - https://invis.io/WX5UHY0HC#/135766381_Signup-Validation

**Comment by simondate** [comment]
This type of validation is not allowed according to #1084

**Comment by michael-palmer** [comment]
requested new validation styling from Paul
