### ISSUE TITLE
Upgrading from 1.2 to 1.7 getting ERROR: 128

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#1210]
Hi I could really use some help I am upgrading our adapt authoring tool from 1.2 to 1.7. I don't want to nuke any of our courses we have built out in the authoring tool so I don't want to install 1.7 from scratch. I am using Windows 7 OS.

I have followed the instructions to removed the "node_modules" folder and type in "npm install --production". I then try to install the latest code dependencies by typing in "node upgrade".  I then get the following screen...

├── crc@3.4.0
├── uid-safe@2.0.0 (base64-url@1.2.1)
└── debug@2.2.0 (ms@0.7.1)

grunt-requirejs-bundle@0.0.9 node_modules\grunt-requirejs-bundle
└── lodash@2.3.0

grunt-merge-json@0.9.5 node_modules\grunt-merge-json
├── lodash@2.4.2
└── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

errorhandler@1.4.3 node_modules\errorhandler
├── escape-html@1.0.3
└── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)

compression@1.6.2 node_modules\compression
├── on-headers@1.0.1
├── vary@1.1.0
├── bytes@2.3.0
├── compressible@2.0.8 (mime-db@1.23.0)
├── debug@2.2.0 (ms@0.7.1)
└── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)

body-parser@1.15.1 node_modules\body-parser
├── content-type@1.0.2
├── bytes@2.3.0
├── depd@1.1.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── qs@6.1.0
├── debug@2.2.0 (ms@0.7.1)
├── raw-body@2.1.6 (unpipe@1.0.0)
├── http-errors@1.4.0 (inherits@2.0.1, statuses@1.3.0)
├── iconv-lite@0.4.13
└── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)

express@4.13.4 node_modules\express
├── escape-html@1.0.3
├── cookie-signature@1.0.6
├── content-type@1.0.2
├── utils-merge@1.0.0
├── vary@1.0.1
├── etag@1.7.0
├── methods@1.1.2
├── fresh@0.3.0
├── range-parser@1.0.3
├── parseurl@1.3.1
├── array-flatten@1.1.1
├── merge-descriptors@1.0.1
├── content-disposition@0.5.1
├── path-to-regexp@0.1.7
├── cookie@0.1.5
├── depd@1.1.0
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.11)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
├── send@0.13.1 (statuses@1.2.1, ms@0.7.1, destroy@1.0.4, mime@1.3.4, http-error
s@1.3.1)
└── serve-static@1.10.3 (send@0.13.2)

winston@1.0.2 node_modules\winston
├── cycle@1.0.3
├── stack-trace@0.0.9
├── eyes@0.1.8
├── isstream@0.1.2
├── async@1.0.0
├── pkginfo@0.3.1
└── colors@1.0.3

nodemailer@1.3.4 node_modules\nodemailer
├── buildmail@1.3.0 (libqp@1.1.0, libbase64@0.1.0, addressparser@0.3.2)
├── nodemailer-direct-transport@1.1.0 (smtp-connection@1.3.8)
├── nodemailer-smtp-transport@1.1.0 (clone@1.0.2, nodemailer-wellknown@0.1.10, s
mtp-connection@1.3.8)
├── libmime@1.2.0 (libqp@1.1.0, libbase64@0.1.0, iconv-lite@0.4.13)
└── hyperquest@1.3.0 (through2@0.6.5, duplexer2@0.0.2)

matchdep@0.3.0 node_modules\matchdep
├── stack-trace@0.0.7
├── resolve@0.5.1
├── globule@0.1.0 (lodash@1.0.2, minimatch@0.2.14, glob@3.1.21)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

prompt@0.2.14 node_modules\prompt
├── revalidator@0.1.8
├── pkginfo@0.4.0
├── read@1.0.7 (mute-stream@0.0.6)
├── utile@0.2.1 (async@0.2.10, deep-equal@1.0.1, i@0.3.5, ncp@0.4.2)
└── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, c
olors@0.6.2, pkginfo@0.3.1)

unzip@0.1.8 node_modules\unzip
├── setimmediate@1.0.4
├── pullstream@0.4.1 (over@0.0.5, slice-stream@1.0.0)
├── readable-stream@1.0.34 (string_decoder@0.10.31, inherits@2.0.1, isarray@0.0.
1, core-util-is@1.0.2)
├── match-stream@0.0.2 (buffers@0.1.1)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8, mkdirp@0.5.1)
└── binary@0.3.0 (buffers@0.1.1, chainsaw@0.1.0)

grunt@0.4.5 node_modules\grunt
├── eventemitter2@0.4.14
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── async@0.1.22
├── colors@0.6.2
├── getobject@0.1.0
├── lodash@0.9.2
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── coffee-script@1.3.3
├── nopt@1.0.10 (abbrev@1.0.7)
├── iconv-lite@0.2.11
├── underscore.string@2.2.1
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── grunt-legacy-log@0.1.3 (grunt-legacy-log-utils@0.1.1, lodash@2.4.2, undersco
re.string@2.3.3)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

request@2.72.0 node_modules\request
├── tunnel-agent@0.4.3
├── oauth-sign@0.8.2
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── is-typedarray@1.0.0
├── stringstream@0.0.5
├── aws4@1.4.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── tough-cookie@2.2.2
├── node-uuid@1.4.7
├── qs@6.1.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.11 (mime-db@1.23.0)
├── form-data@1.0.0-rc4 (async@1.5.2)
├── bl@1.1.2 (readable-stream@2.0.6)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.2.2, sshpk@1.8.3)
└── har-validator@2.0.6 (pinkie-promise@2.0.1, commander@2.9.0, is-my-json-valid
@2.13.1)

multer@1.1.0 node_modules\multer
├── object-assign@3.0.0
├── append-field@0.1.0
├── xtend@4.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6
)
├── mkdirp@0.5.1 (minimist@0.0.8)
└── busboy@0.2.13 (readable-stream@1.1.14, dicer@0.2.5)

grunt-contrib-watch@0.5.3 node_modules\grunt-contrib-watch
├── tiny-lr@0.0.4 (debug@0.7.4, qs@0.5.6, faye-websocket@0.4.4, noptify@0.0.3)
└── gaze@0.4.3 (globule@0.1.0)

grunt-contrib-connect@0.3.0 node_modules\grunt-contrib-connect
└── connect@2.7.11 (qs@0.6.5, fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1,
buffer-crc32@0.2.1, bytes@0.2.0, cookie@0.0.5, send@0.1.1, debug@2.2.0)

archiver@0.8.1 node_modules\archiver
├── buffer-crc32@0.2.5
├── lazystream@0.1.0
├── lodash@2.4.2
├── readable-stream@1.0.34 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.
1, core-util-is@1.0.2)
├── zip-stream@0.3.7 (deflate-crc32-stream@0.1.2, crc32-stream@0.2.0, debug@1.0.
4)
└── file-utils@0.1.5 (isbinaryfile@0.1.9, lodash@2.1.0, iconv-lite@0.2.11, minim
atch@0.2.14, findup-sync@0.1.3, glob@3.2.11)

grunt-contrib-handlebars@0.7.0 node_modules\grunt-contrib-handlebars
├── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.7, strip-ansi@0.1.1)
├── grunt-lib-contrib@0.5.3 (zlib-browserify@0.0.1)
└── handlebars@1.3.0 (optimist@0.3.7, uglify-js@2.3.6)

hbs@2.4.0 node_modules\hbs
├── walk@2.2.1 (forEachAsync@2.2.1)
└── handlebars@1.0.12 (optimist@0.3.7, uglify-js@2.3.6)

node-gyp@0.12.2 node_modules\node-gyp
├── graceful-fs@2.0.3
├── semver@2.2.1
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── nopt@2.2.1 (abbrev@1.0.7)
├── minimatch@0.4.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── which@1.2.10 (isexe@1.1.2)
├── npmlog@0.1.1 (ansi@0.3.1)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.9)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8, mkdirp@0.5.1)

connect-mongo@0.4.2 node_modules\connect-mongo
└── mongodb@1.4.40 (readable-stream@2.1.4, kerberos@0.0.11, bson@0.2.22)

mongoose@3.8.40 node_modules\mongoose
├── hooks@0.2.1
├── regexp-clone@0.0.1
├── mpath@0.1.1
├── muri@1.1.0
├── ms@0.1.0
├── sliced@0.0.5
├── mpromise@0.4.3
├── mquery@1.10.0 (debug@2.2.0, bluebird@2.10.2)
└── mongodb@1.4.38 (readable-stream@2.1.4, kerberos@0.0.11, bson@0.2.22)

moment@2.13.0 node_modules\moment

grunt-contrib-less@0.7.0 node_modules\grunt-contrib-less
├── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)
└── less@1.4.2 (ycssmin@1.0.1)

bower@1.3.12 node_modules\bower
├── is-root@1.0.0
├── stringify-object@1.0.1
├── junk@1.0.2
├── chmodr@0.1.0
├── which@1.0.9
├── abbrev@1.0.7
├── osenv@0.1.0
├── opn@1.0.2
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.1
├── bower-logger@0.2.2
├── q@1.0.1
├── graceful-fs@3.0.8
├── lru-cache@2.5.2
├── archy@0.0.2
├── nopt@3.0.6
├── retry@0.6.0
├── tmp@0.0.23
├── request-progress@0.3.0 (throttleit@0.0.2)
├── p-throttler@0.1.0 (q@0.9.7)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, jsonify@0.0.0, ar
ray-map@0.0.0)
├── chalk@0.5.0 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── promptly@0.2.0 (read@1.0.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── fstream-ignore@1.0.5 (inherits@2.0.1, minimatch@3.0.0)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.3, minimatch@1.0.0)
├── fstream@1.0.9 (inherits@2.0.1, graceful-fs@4.1.4)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── request@2.42.0 (forever-agent@0.5.2, tunnel-agent@0.4.3, aws-sign2@0.5.0, ca
seless@0.6.0, oauth-sign@0.4.0, stringstream@0.0.5, json-stringify-safe@5.0.1, t
ough-cookie@2.2.2, mime-types@1.0.2, qs@1.2.2, node-uuid@1.4.7, http-signature@0
.10.1, form-data@0.1.4, bl@0.9.5, hawk@1.1.1)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream
@1.1.14, binary@0.3.0)
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-versio
n@0.2.0, configstore@0.3.2)
├── bower-registry-client@0.2.4 (async@0.2.10, graceful-fs@2.0.3, request-replay
@0.2.0, lru-cache@2.3.1, mkdirp@0.3.5, request@2.51.0)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── mout@0.9.1
├── insight@0.4.3 (object-assign@1.0.0, async@0.9.2, chalk@0.5.1, tough-cookie@0
.12.1, lodash.debounce@2.4.1, os-name@1.0.3, configstore@0.3.2, inquirer@0.6.0)
└── inquirer@0.7.1 (mute-stream@0.0.4, through@2.3.8, figures@1.7.0, lodash@2.4.
2, readline2@0.1.1, rx@2.5.3, cli-color@0.3.3)

Adapt_Authoring@PRODUCTION-PC ~/adapt_authoring_v2_ORGINAL
$ node upgrade
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
This script will update the Adapt Builder (and/or Adapt Framework) to the latest
 released version. Would you like to continue?
prompt: Y/n:  (Y) y
info: [09 Jun 2016 14:23:25 -04:00] configuration loaded from c:\Users\Adapt_Aut
horing\adapt_authoring_v2_ORGINAL\conf\config.json
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
Server has started
Checking versions
Currently installed versions:
- Adapt Builder: v0.1.2
- Adapt Framework: v2.0.2
info: [09 Jun 2016 14:23:27 -04:00] Server started listening on port 5000
Checking for Adapt Builder upgrades...
Checking for Adapt Framework upgrades...
Update for Adapt Builder is available: v0.1.7
Update for Adapt Framework is available: v2.0.10
Upgrading the Adapt Builder...please hold on!
fatal: Not a git repository (or any of the parent directories): .git

ERROR: 128

**Comment by taylortom** [comment]
Looks like your code isn't stored in a git repository (the script uses git to pull down the latest code). You have two options really:

1. You could try and upgrade manually by: 
    - Grab a copy of the latest code authoring tool code from [here](https://github.com/adaptlearning/adapt_authoring/releases/tag/v0.1.7) 
    - Copy files over your existing code
    - Run `npm install && grunt build` to install the dependencies and rebuild the frontend
    - To upgrade the framework:
        -  `cd` to the framework repo (`/temp/TENANT_ID/adapt_framework/`)
        - Get the latest data for the repo by running `git fetch origin`
        - Get the latest framework release: `git reset --hard v2.0.10`
        - Install the framework's dependencies: `npm install`
        - Remove the course folder from the updated framework folder

2. The other solution is to:
    -  Install a fresh version of the authoring tool [from scratch](https://github.com/adaptlearning/adapt_authoring/wiki/Install-on-Server)
    - Copy across `conf`, `data` to your new authoring tool root. 

The latter may be better if you're looking to update later.

_**Note**: the above instructions were written from the top of my head at 5:30pm on a Friday, so forgive me for any errors._
