### ISSUE TITLE
Spacing on smaller screens

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1212]
I've got a few concerns about the design update when viewed on a smaller screen (in my case 1440x900) - there's noticeably less screen 'real estate' in the main content area (i.e. the `.app-inner` div).

Here are my thought on possible areas for tweaking:
- Padding in general (main offenders here are things like the page title area, sidebar and top bar)
- Text size/weight in general (specific offenders: sidebar, page title/location text, title field for the page/section tiles on the Menu editor page). Incidentally, using a heavier text weight universally makes the font look a bit more rounded/comic-sans-y to me -- using a light weight in more places might help this.
- Dashboard tiles seem unnecessarily big (this was a problem with the old design, but maybe something we can improve a bit here) -- in particular, list view seems *way* too chunky (I'd like one of the views to allow you to get a whole load of courses on screen at once).
- The forms are too narrow (e.g. component edit). I think these should fill the available content area (again, this makes a big difference when viewed on my smaller screen).

**Comment by simondate** [comment]
34bf5e5 I've made some changes to make titles on the dashboard screen to appear slightly bigger whilst making titles on the menu editor screen to appear slightly smaller.

As for padding being too big will leave it for @michael-palmer and @messyp to advise here.

**Comment by simondate** [comment]
Suggest that we have a video call on Tuesday looking specifically at padding and font sizes on as many screen as possible.

**Comment by taylortom** [comment]
Few things to at:
- Form padding/margins need amending as per discussion (suggest maybe making the `fieldset` margin 20px all round)
- Sidebar/page location bar still look quite chunky (see attached) -- can we make these percentage based perhaps?

**Comment by taylortom** [comment]
![screen shot 2016-06-21 at 14 05 04](https://cloud.githubusercontent.com/assets/1059083/16230426/5007701e-37b9-11e6-986c-ec3340eb2954.png)

**Comment by taylortom** [comment]
Fine for now.
