### ISSUE TITLE
Menu Editor - Title and icons colour 

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1217]
![simondatescreenshot 1](https://cloud.githubusercontent.com/assets/1676635/16188110/d0d1862e-36cb-11e6-83cc-3ba3c51c4b98.jpg)

Should this page/folder icon and title be blue like the cog and delete icons?

**Comment by michael-palmer** [comment]
as per the design .. icon is grey and the text it black
https://projects.invisionapp.com/share/WX5UHY0HC#/screens/109479794_Structure

**Comment by simondate** [comment]
Done in 3bfab85

**Comment by michael-palmer** [comment]
looks good
