### ISSUE TITLE
Multi-user previewing/publishing

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1220]
Publishing fails if 2+ users attempt it at once.

**Problem seems to stem around the way a temporary theme folder is created for each build** -- if a build process has already started, then a user triggers another, the new build will empty this theme folder, causing the original process to fail if it needs to access some files which it thinks are there.

**Comment by taylortom** [comment]
I've pushed a temporary fix to a dev fork which just adds a listener if a build is already in-progress, and acts accordingly when the build is finished.

Big downside to this is that the second user may not get their changes included in the in-progress build.

**Comment by taylortom** [comment]
I guess this begs the question: how do we deal with multiple users previewing/modifying content simultaneously?

Some issues/scenarios to discuss:

**2+ users editing the same page/config/whatever**<br>Data corruption-wise, I've not seen any issues with this, but from a usability point of view, how do we deal with this? Multiple users could unknowingly be changing the same attribute at the same time, causing user confusion when previewing/refreshing the page.

**2+ users previewing/publishing at the same time**<br>Current outcome: build will likely fail if preview button is pressed while a build is happening.

Possible solutions:
- Block preview while building
- 'Other users are editing this page' popup/warning
- 'Course has been updated, rebuild to see the latest' in the event of previewing while another user is editing course.

**Comment by dancgray** [comment]
At a general level I'm in favour of informing the user that someone else is editing the course without preventing collaboration (perhaps similar to the way google displays other active users on the same doc maybe with 'Other users are editing this page' popup/warning ). As long as users are informed and errors are prevented.

**Comment by taylortom** [comment]
This should be fixed.
