### ISSUE TITLE
'Table' colours need updating

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1221]
Think this is pretty obvious, the grey looks a bit odd, as isn't used elsewhere:

![screen shot 2016-06-21 at 15 15 45](https://cloud.githubusercontent.com/assets/1059083/16232599/1b2d5958-37c3-11e6-9957-b10e1659b7e6.png)

**Comment by simondate** [comment]
![simondatescreenshot 5](https://cloud.githubusercontent.com/assets/1676635/16233456/4e43a9d4-37c6-11e6-8b5c-26bd1c3cfa99.jpg)

Changed to this. e952acd

Think the line below the title might need to be changed too.

**Comment by taylortom** [comment]
Looks much better. We also need to update the heading bg colour in **Manage extensions**

**Comment by taylortom** [comment]
![screen shot 2016-06-22 at 10 01 02](https://cloud.githubusercontent.com/assets/1059083/16262586/20c77448-3868-11e6-9dab-acd87f4acac2.png)

**Comment by messyp** [comment]
Mike and I were looking at this and the all blue table doesn't quite feel analogous to the rest of the AD

Link to a new table style which is padded more like the form pages

https://invis.io/WX5UHY0HC#/172308279_Table

**Comment by taylortom** [comment]
Have styled this to look as close as possible. Won't be able to implement the sidebar filters for this release unfortunately (although think it should go in later)
