### ISSUE TITLE
Loading icon outdated

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1222]
This hasn't been changed since the beginning. As we're IE9, we could possibly get an SVG in here?

![screen shot 2016-06-21 at 15 17 51](https://cloud.githubusercontent.com/assets/1059083/16232655/5b91e766-37c3-11e6-839d-9d53fa1b9e82.png)

This is an example I set up a while ago (not suggesting we use this, just something more modern pls):
![screen shot 2016-06-21 at 15 19 11](https://cloud.githubusercontent.com/assets/1059083/16232708/8cf25c8c-37c3-11e6-95fe-742bcefcb3a5.png)

**Comment by simondate** [comment]
@taylortom has updated this. Assigning to Mike to review.
