### ISSUE TITLE
Font weights

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1223]
In the earlier designs, we seemed to use a lighter variation of the font than is used in the current build.

Open sans has a tendency to look a bit chunky and cartoony (a bit Comic Sans-y) when the weight is heavy (see sidebar text, button text to name but two).

Any thoughts?

**Comment by michael-palmer** [comment]
there's been a lot of comment and subjective opinion on the fonts we've used, which is fine .. personally i preferred the Roboto font (default on Android) as it's a good all-rounder but maybe that's just me :)

**Comment by taylortom** [comment]
Yeah, it's one of those things everyone has an opinion on. Will park this until the 'rewrite'.

**Comment by taylortom** [comment]
Closing this, as we're happy with current font selection.
