### ISSUE TITLE
Export button omitted from designs

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1225]
In addition to preview and publish, we also now have an 'Export source code' button (relatively new feature added since the designs were created I believe).

**Comment by michael-palmer** [comment]
i'm thinking it should be a text link displayed alongside the 'fa-code' icon .. positioned between the download button and project settings link .. have asked Paul for comment

**Comment by michael-palmer** [comment]
please style as per the attached (icon is 'fa-code')
![1467298492](https://cloud.githubusercontent.com/assets/946424/16516183/74a75cec-3f6e-11e6-9512-e54a8247ae3a.png)

**Comment by simondate** [comment]
I've added this as above. However I'm still not sure we have reached a consensus on what animation to use for downloading/previewing/exporting?
