### ISSUE TITLE
Sidebar button rollovers

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1228]
I'm not sure about the rollover styling/spacing. 

On some screens (see next paragraph), it looks odd when you rollover the very top button -- the spacing between the rollover background and the 'action' button(s) is too little.

Menu editor/Page editor pages seems to be spaced correctly, whereas specific form/edit screens (i.e. component edit screens) aren't. Have attached screens below for clarification.

**Comment by taylortom** [comment]
### Bad
![screen shot 2016-06-29 at 10 01 26](https://cloud.githubusercontent.com/assets/1059083/16446716/d8c132d2-3de0-11e6-8730-9dc7083ab0cf.png)

### Good
![screen shot 2016-06-29 at 10 01 48](https://cloud.githubusercontent.com/assets/1059083/16446715/d8bc28be-3de0-11e6-8cb6-4770c3210120.png)

**Comment by taylortom** [comment]
Possible solution: style like hyperlinks rather than buttons

**Comment by taylortom** [comment]
The more I see this, the more I think this is a bug, with the component buttons just needing some more spacing.

**Comment by taylortom** [comment]
Possibly change text to white

**Comment by messyp** [comment]
Mike and I have just been playing around with this - The white text and no hover background looks good
