### ISSUE TITLE
Component Drawer styling

### ISSUE THREAD

**Issue by messyp** [adaptlearning/adapt_authoring#1241]
Please can we style the component drawer to be more like the AD

Please check spacing, line colour, header etc

Invision link: 

https://invis.io/WX5UHY0HC#/166578605_New-Component-Bar

**Comment by taylortom** [comment]
Done

**Comment by messyp** [comment]
Looking good!

Just noticed a few minor things and its done

- Borders between rows should be #f1f0f0 and 2px high
- Remove the border from the search
- Hover colour appears to be leftover from old styling - suggest changing to light blue  #f3fcfe
