### ISSUE TITLE
Error running Authoring Tool after installation

### ISSUE THREAD

**Issue by jgraham-plm** [adaptlearning/adapt_authoring#1250]
I have just installed the Adapt Authoring Tool for the first time; while everything seemed to install ok and I can connect to the server in my browser, I'm getting a JS error in the browser preventing the tool from loading (it just hangs on 'Loading...').

The error is:

```
Uncaught Error: Load timeout for modules: adaptbuilder/js/origin.js?20160708160947956
```

Details about my installation:
OS: Ubuntu 14.04.3 LTS
Adapt authoring tool v0.1.7
Adapt framework v2.0.7
Node version 4.4.2

I would be very grateful if anyone could help me address this issue. Thank you!

**Comment by jgraham-plm** [comment]
Anyone have any ideas? This strikes me as perhaps a version mismatch issue, but I have no way of knowing if the versions listed above

**Comment by jgraham-plm** [comment]
Close/reopen was completely accidental — sorry!

**Comment by brian-learningpool** [comment]
Try running: `grunt build:prod && node server.js`

**Comment by jgraham-plm** [comment]
@brian-learningpool Thanks for the reply. Tried this but it does not fix the issue.

**Comment by jgraham-plm** [comment]
I did look at this doc: http://requirejs.org/docs/errors.html#timeout

I'm not seeing any 404 errors in browser dev tools (I've also tried a handful of browsers); the other issues suggested here have to do with script errors and map config issues, so I'm not sure where I'd begin with troubleshooting that.

**Comment by exff** [comment]
Hi, I have the same problem as @jgraham-plm. The login page starts loading ("Loading..." in middle of the page) but then hangs.

The error in my case is also: 
"Script error for: adaptbuilder/js/origin.js?20160810095533452"

Details about my server installation:
Ubuntu 16.04.1 LTS
Adapt authoring tool v0.1.7
Adapt Framework v2.0.7
Node version v4.2.6

I find that after finishing "node install" there is no "origin.js" in my "/adapt_authoring/frontend/src/adaptbuilder/js" directory.

During the installation process I got the following error during "node install":
_____
Running  "requirejs:compile" (requirejs) task

[Error: Error: Module loading did not complete for: core/app/app, sweetalert,  coreJS/notify/notify, coreJS/notify/plugins/alert/index
    at Function.build.checkForErrors (/root/adapt_authoring/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:31556:19)
]
  originalError: [Error: Module loading did not complete for: core/app/app, sweetalert, coreJS/notify/notify, coreJS/notify/plugins/alert/index] }

ERROR:  { [Error: Command failed: /bin/sh -c grunt build:prod
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c grunt build:prod' }
grunt build:prod command failed. Is the grunt-cli module installed? You can install using npm install -g grunt grunt-cli
Install will continue. Try running grunt build:prod after installation completes.
____________
The other build tasks seem to have been completed OK. So for instance I get the message "... frontend/src/adaptbuilder/css/adapt.css created." and the file is actually there.
If I run "grunt build:prod" again, I get the same error.

The same problem occurs to me when installing Adapt authoring tool v0.2.0.

Maybe the above information helps with further trobleshooting. I would be more than grateful if I could get the system running.

**Comment by exff** [comment]
In my case I was able to resolve the problem:

Guessing that it might be a timeout issue I added in "/adapt_authoring/frontend/src/core/app/config.js" right at the beginning of  " require.config({ " :

waitSeconds: 300,

then the installation completed without errors.

(I am using an older PC as a test server. On the other hand I have not experienced any performance issues so far.)
