### ISSUE TITLE
Error when double-clicking menu item

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#1262]
```
ReferenceError: event is not defined
```
This error can prevent entering into a menu item in Firefox. I can replicate by clicking on menu items.

The offender: https://github.com/adaptlearning/adapt_authoring/blob/front-end-work-dev/frontend/src/core/editor/menu/views/editorMenuItemView.js#L113.

Note: this is on the Heroku instance.

**Comment by taylortom** [comment]
Good spot, this one's been there while 😦

**Comment by taylortom** [comment]
Fixed
