### ISSUE TITLE
Can't edit and save copied content

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1288]
AT 0.2.0 FW 2.0.11
Open an existing project. Copy a section from the menu and paste.
Go into section and make changes to text in a component or the section name for example, click Save and get loading wheel and Saving which hangs so can not save changes.

Also hangs after adding new section to the course and trying to edit that.

Can add and edit existing content fine, just not a section that I have duplicated or added.

**Comment by hmaffin** [comment]
After some playing around this seems to have sorted itself out but will monitor.

**Comment by hmaffin** [comment]
OK identified the cause - this is the same as the issue where extensions require certain criteria #1293 but it happens with articles only, because there is no list of sections on the left such as Extensions to turn red, we just see a whirling save icon.

I recreated this by trying to amend an article in which i had bookmarking. I noticed that the attribute of where the bookmark returns you to is required, but was empty. So I had to set that to something THEN save my changes to the article which prevented the Saving whirl issue.

**Comment by taylortom** [comment]
I'm not sure I understand this one -- articles should have the same sections as the other content objects:

![screen shot 2016-08-03 at 09 46 08](https://cloud.githubusercontent.com/assets/1059083/17359587/338c8ccc-595f-11e6-8e04-d519e70b1162.png)

**Comment by hmaffin** [comment]
Sorry! Wasn't an article after all - it was the Page Settings section. So the very top box on each page.

**Comment by taylortom** [comment]
Ahh, ok! :)

I've just tried retracing your steps, but not getting the same issue: have bookmarking enabled, but saves ok with the default settings. Any ideas?

**Comment by hmaffin** [comment]
OK I just added a new page and went in to edit the name of the page. When I checked bookmarking this is what I see 
![image](https://cloud.githubusercontent.com/assets/11558341/17372266/04841eb8-599b-11e6-865b-a2cda6b717c2.png)

and if you don't choose an option from the bookmarking before you click Save, it goes to Saving and whirly icon and hangs. You can only click Cancel then and then lose your work. 

Extra point on this - why do we need to have bookmarking settings on each page? Shouldn't it just be a one off for the whole project? What happens if I pick return to block for one page and return to article for another? Just how it sounds? I think I'd prefer it to be consistent but I guess there's a reason why?
