### ISSUE TITLE
Drag and drop of articles and blocks broken

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1290]
AT 0.2.0 FW 0.2.11
Can't drag an article further up or down the page, page doesn't scroll.
Can drop the article if you can see the destination on the page already so it IS working, just not scrolling.

**Comment by taylortom** [comment]
This also affects the menu editor page when you try to rearrange pages/sections.

**Comment by brian-learningpool** [comment]
@taylortom, I'm pretty sure that moving sections to other sections was intentionally prevented as if it were allowed we'd run into possible issues with parenting of menu items.  

The course structure editor UI is such that clicking on a section expands the rest of the hierarchy path, so without a lot of re-work, you could only move sections within the currently opened path, not anywhere in the course.

**Comment by taylortom** [comment]
Ah, that makes sense @brian-learningpool. We could do with some kind of visual notification that this isn't allowed, as it looks broken atm. 

For another time though.

**Comment by taylortom** [comment]
Fix merged

**Comment by hmaffin** [comment]
Just discovered with this if you click and hold the block, then use the arrow keys on the keyboard you could scroll to where you want to drop the block! Bit late but thought I'd mention it :)
