### ISSUE TITLE
Assessment attempts won't accept -1

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1292]
![image](https://cloud.githubusercontent.com/assets/11558341/17324064/8ba01ff0-589c-11e6-8132-e1259eb2f6ca.png)

I don't even want an assessment in this article but it won't let me proceed without it.

**Comment by hmaffin** [comment]
Ah - this is the same at #1289

**Comment by taylortom** [comment]
Closing, as duplicate.
