### ISSUE TITLE
Can't save articles/blocks without extension criteria

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1293]
AT 0.2.0 FW 2.0.11
When trying to save changes to an article, one is given a red warning on Extensions on the LHS.

The AT is requiring criteria within the Extensions even though I do not wish for them to be used in this article, for example;

Assessment requires an Assessment name ;
![image](https://cloud.githubusercontent.com/assets/11558341/17324179/2921ae7e-589d-11e6-8d1b-3b11f1f3ca3e.png)

Block Slider requires a minimum height
![image](https://cloud.githubusercontent.com/assets/11558341/17324193/3dbf11c8-589d-11e6-8934-3706bb8fe9e8.png)

**Comment by taylortom** [comment]
These validation errors are due to the schemas being incorrectly set up/having fields marked as required when they perhaps shouldn't be.

Will need to be fixed in the individual repos -- I'll create a ticket for assessment, could you do one for block slider (not sure which repo you've used)

**Comment by hmaffin** [comment]
Roger!

**Comment by taylortom** [comment]
Closing as not specifically relevant to the AT
