### ISSUE TITLE
Suggestion : Sliders for True/False rather than dropdowns

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1324]
There are so many settings in pages, components, extensions etc of the User Interface that are just True/False, such as Page Level Progress etc.

To save clicks on these would it be easier to have a slider like toggle or on/off switch type of button for these rather than the current dropdown which takes two clicks?

**Comment by taylortom** [comment]
+1 for this

**Comment by tomgreenfield** [comment]
I already use `"inputType": "Checkbox"` for a most of the Boolean attributes in my own extensions; it should be relatively easy to style up the checkboxes to look like switches.

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
Going to close this, as is really up to the plugin maintainers to use the checkbox type (see #1380).
