### ISSUE TITLE
Enhancement: allow adapt-contrib-media _playerOptions to be set in authoring tool

### ISSUE THREAD

**Issue by sharpb** [adaptlearning/adapt_authoring#1326]
At present it states on the [adapt-contrib-media](https://github.com/adaptlearning/adapt-contrib-media) github readme:

> Currently, the Adapt authoring tool does not accommodate configuring these options; courses that require _playerOptions must be built directly in the Adapt framework.

It would be great if we could set these via the authoring tool, for example:

![playeroptions](https://cloud.githubusercontent.com/assets/20811952/17669647/57189400-6306-11e6-98d2-dce22b4add6d.jpg)

**Comment by brian-learningpool** [comment]
I agree that this would be a really worthwhile enhancement.  I think using a serialised string for the player options might be quite error prone though.  Let's have a think about this.

**Comment by sharpb** [comment]
@brian-learningpool in terms of implementing this would you class as easy, medium, hard or insane?  I'm looking for an excuse/feature/bug to have a go at to get into contributing but don't want to jump to far into the deep end (mainly as I don't have loads of time to spend on it) :)

**Comment by brian-learningpool** [comment]
I'd say this is medium difficulty.  

It really requires a knowledge of JSON (to update `properties.schema`) and JavaScript to make the associated change to `adapt-contrib-media.js`.  Depending on the approach it should be doable in a few hours.

While this is actually a ticket in the authoring tool, the fix is in the Media component itself.

**Comment by sharpb** [comment]
@brian-learningpool Thanks, I'll give it a go.  I've forked adapt-contrib-media and will submit a PR if I can get it working ok :)

**Comment by tomgreenfield** [comment]
Hi @sharpb, I've actually already made good headway with allowing JSON to be entered into the authoring tool. I'll try to get some time to tidy up my work and put in a PR so we don't force you to duplicate work!
