### ISSUE TITLE
‘Downloading...’ text wraps outside of button

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#1328]
A bit of multiline fun:

![downloading](https://cloud.githubusercontent.com/assets/922987/17693844/e213af62-6398-11e6-91cc-819a328d1d0c.png)

**Comment by taylortom** [comment]
This should be an easy fix (if it still exists...).

**Comment by tomgreenfield** [comment]
P.S. replicated in Chrome (Windows).

**Comment by hmaffin** [comment]
Does for me too briefly in Chrome then sorts itself out after a second or two
