### ISSUE TITLE
New asset saving spinner not reset on permissions error

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1339]
May affect all errors, but confirmed for at least permissions errors.

**Comment by taylortom** [comment]
Check this is still an issue

**Comment by canstudios-nicolaw** [comment]
When I upload an asset there is a spinner on the save button, when the upload is complete I am redirected to the asset manager.

When I do not have permission and I attempt to upload an asset, then the spinner on the button is shown momentarily. The save button returns to it's default state, I am not redirected anywhere, and I see an error modal.

![Screenshot from 2019-04-23 11:10:01](https://user-images.githubusercontent.com/25502448/56573186-72726c00-65b8-11e9-8cb2-37d8e96712db.png)

I think this means that this is no longer an issue @taylortom ? Just running this past you before closing as the original issue was a little vague.

**Comment by taylortom** [comment]
Fine with me
