### ISSUE TITLE
Customisable Theme 

### ISSUE THREAD

**Issue by MiguelMB** [adaptlearning/adapt_authoring#1341]
I whant to change the theme  default of adapt_authoring ,
need install adapt_framework , no adapt_authoring ?

Thanks for read 

Miguel

**Comment by taylortom** [comment]
Hi Miguel,

To change the theme, you need to upload it using the **Plugin Management** area, and then select it for your course using the **Theme picker**. There's currently no way to change which theme is selected by default when you create a new course.

**Comment by MiguelMB** [comment]
Thanks taylortom 

This days read so much the documentation and know more stuff.
Congratulation your work are amazing.
