### ISSUE TITLE
Should we allow password changing using the interface

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1348]
As opposed to only password reset emails

Think it might be useful to more people than using a reset email (not sure how many people have this set up).

**Comment by taylortom** [comment]
We could check whether the mail server's been set up, and hide the option appropriately.

**Comment by johnniezen** [comment]
Indeed, if no mail server is setup, then it should be direct, but maybe with an additional check or validation, ie like chaptcha.

**Comment by brian-learningpool** [comment]
I think "Yes" to hiding the reset password link if e-mail isn't configured.

I don't think reCAPTCHA is required as this will add more complexity to the setup (extra steps in installation, configuration, etc.) and besides, the user profile screen -- where I'd expect the user could change their password -- should only be available to the logged on user.

**Comment by taylortom** [comment]
@brian-learningpool this was referring to the user management 'change password' button: 
![screen shot 2016-09-13 at 15 03 11](https://cloud.githubusercontent.com/assets/1059083/18476792/4fc278c8-79c3-11e6-9d8c-b48789446d55.png)

![screen shot 2016-09-13 at 15 03 22](https://cloud.githubusercontent.com/assets/1059083/18476815/630dfe48-79c3-11e6-9dfc-e5813df0ee61.png)

**Comment by taylortom** [comment]
No longer relevant
