### ISSUE TITLE
Remove hard-coded locked value for users

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1354]
At the moment, `MAX_LOGIN_ATTEMPTS` which is used to determine whether a user can log in or not is only specified in [`plugins/auth/local`](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/auth/local/index.js#L30).

Locked user accounts should have a property in the DB (as with _isDeleted), and the `MAX_LOGIN_ATTEMPTS` should be externalised somewhere (possibly configurable in `config.json`?)

**Comment by lc-thomasberger** [comment]
Is this already fixed?
`maxLoginAttempts` is exposed in the config however user's don't have a `_isLocked` attribute.

**Comment by taylortom** [comment]
Yep, think this can be closed now
