### ISSUE TITLE
Scope theme editor requirements

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1360]
Please add a comment with requirements, and will add them to the [requirements doc](https://github.com/adaptlearning/documentation/blob/master/02_authoring_tool/04_feature_development/theme_editor/theme-editor-reqs.md).

**Comment by aniketdharia** [comment]
- When we double click on a theme, it should provide a pop-up or a new page with "back" button to return to the themes page.
- The new page will contain all the variable names and a color-picker next to it.
- If the user saves it will save all the updated values in the theme folder
- The user should be able to duplicate theme and modify it with above steps

**Comment by johnniezen** [comment]
Regarding the pop-up Aniket describes, there should be some kind of help of info on the impact of the variables. For example the padding of the ABC elements, or no padding when titles are not used.
It would also be nice if there is some preview available to check the impact of your changes.

**Comment by lc-thomasberger** [comment]
Ability to update (Background-) Images used in a Theme.

**Comment by lc-thomasberger** [comment]
When working in the course, it would be nice to have a user-friendly way to use the `_classes` attribute of elements. When the Theme registers classes for a block, it would be nice to have a visual representation of the css-styles available when editing a block. Something like a style selector that uses images to preview the applied styles.

**Comment by lc-thomasberger** [comment]
Ability to add a thumbnail image to a custom theme that is used in the theme-picker.

**Comment by johnniezen** [comment]
Regarding "User", I think if Tenant/User Management is active, there should be a restriction to the level what a user could change. As Admin, I would like to be able to create/setup certain templates that a team can use. As a user I might want to try and change little things, but that should not override the original theme.

**Comment by taylortom** [comment]
Interesting thought @johnniezen :)

**Comment by taylortom** [comment]
Have summarised these requirements in the InVision mood board, both as a part of the [requirements](https://projects.invisionapp.com/d/main#/projects/boards/5275687/160435627), and [exposed settings](https://projects.invisionapp.com/d/main#/projects/boards/5275687/160476816) notes.
