### ISSUE TITLE
Refactor editor.js

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1372]
Very difficult to read and understand what's going on in here. Suggest maybe moving the router code into the specific folders and let them deal with specific routing.

e.g. create a `page/page.js`, which preloads all page-related data, and listens to relevant `router:editor` events. I've done something similar here: [cgkineo:adapt_authoring-themeEditor/index.js#L18-L28](https://github.com/cgkineo/adapt_authoring/blob/production/frontend/src/plugins/themeEditor/index.js#L18-L28)

**Comment by brian-learningpool** [comment]
I agree.  It's just kind of grown more bloated over time, and I think we've been putting off the refactor for too long.

**Comment by taylortom** [comment]
Have done some refactoring as a test. There's nothing fundamentally different in terms of what it does now, I've basically just moved all routing code into a new file (editorRotuer.js) and untangled the switch statement/if logic. 

Probably more that can be done.

Commit here: https://github.com/cgkineo/adapt_authoring/commit/668f3b95a8823fac688109e90f0a2b9bd1e454ce
[editor.js](https://github.com/cgkineo/adapt_authoring/blob/668f3b95a8823fac688109e90f0a2b9bd1e454ce/frontend/src/core/editor/editor.js)
[editorRouter.js](https://github.com/cgkineo/adapt_authoring/blob/668f3b95a8823fac688109e90f0a2b9bd1e454ce/frontend/src/core/editor/global/editorRouter.js)

**Comment by taylortom** [comment]
Fixed as part of 0.4.0
