### ISSUE TITLE
Change boolean selects to type Checkbox

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1380]
Seems more intuitive than using a select (and not to mention it reduces the clicks). This affects all schemas (see #1324 for more info).

Need to list all plugins this affects.

**Comment by brian-learningpool** [comment]
@moloko has started adjusting this as part of a PR so let's use this ticket to keep track of it.  For consistency we should probably merge these changes at the same time.

Extensions:
- [ ] adapt-contrib-assessment
- [ ] adapt-contrib-resources
- [x] adapt-contrib-spoor - https://github.com/adaptlearning/adapt-contrib-spoor/pull/153
- [ ] adapt-contrib-bookmarking		
- [ ] adapt-contrib-trickle			
- [ ] adapt-contrib-tutor
- [ ] adapt-contrib-languagePicker
- [ ] adapt-contrib-pageLevelProgress

Components:
- [ ] adapt-contrib-text
- [ ] adapt-contrib-narrative
- [ ] adapt-contrib-media
- [ ] adapt-contrib-hotgraphic
- [ ] adapt-contrib-blank
- [ ] adapt-contrib-accordion
- [ ] adapt-contrib-graphic
- [ ] adapt-contrib-matching
- [ ] adapt-contrib-textInput
- [ ] adapt-contrib-mcq
- [ ] adapt-contrib-gmcq
- [ ] adapt-contrib-assessmentResults

**Comment by moloko** [comment]
sorry I can't check the checkboxes in your comment @brian-learningpool as I've not got that level of access in this repo, I'll have to add PRs here instead

https://github.com/adaptlearning/adapt-contrib-narrative/pull/173

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-resources/pull/48
https://github.com/adaptlearning/adapt-contrib-bookmarking/pull/24

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-media/pull/164

**Comment by moloko** [comment]
Mustn't forget to amend the [core .schema files too](https://github.com/adaptlearning/adapt_framework/tree/master/src/core/schema)...

**Comment by moloko** [comment]
Mustn't forget to amend the [core .schema files too](https://github.com/adaptlearning/adapt_framework/tree/master/src/core/schema)...

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-gmcq/pull/109
https://github.com/adaptlearning/adapt-contrib-mcq/pull/134

**Comment by moloko** [comment]
right, last ones I think...

https://github.com/adaptlearning/adapt_framework/pull/1606
https://github.com/adaptlearning/adapt-contrib-slider/pull/123
