### ISSUE TITLE
Allow custom framework plugins to hook into 'Check for update' button

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1382]
However, I think it's important to keep the distinction between core plugins, and user uploaded plugins.

**Comment by dancgray** [comment]
+1 this would be very useful

**Comment by aniketdharia** [comment]
👍

**Comment by taylortom** [comment]
👍  from @hmaffin (see #1434)

**Comment by hmaffin** [comment]
Great minds think alike @taylortom

**Comment by taylortom** [comment]
Duplicate of https://github.com/adaptlearning/adapt_authoring/issues/921
