### ISSUE TITLE
Travis failing on develop

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1389]
https://travis-ci.org/adaptlearning/adapt_authoring/builds/160126913

**Comment by hrajotia** [comment]
Might be an issue with npm it self. found a related link - https://github.com/npm/npm/issues/7472#issuecomment-76510381

The latest build seems to me working: https://travis-ci.org/adaptlearning/adapt_authoring/builds/161010644.

**Comment by taylortom** [comment]
Ok cool, will leave this open until we merge something and confirm :)
