### ISSUE TITLE
update grunt process to merge/minify the frontend plugins to reduce server requests

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1397]
Currently the task requirePlugins does not minify the code but just copy pastes and changes the path. The more plugins the more requests are being sent to the server. If we need to optimise this, during the grunt build:prod execution the requirePlugins should also me minified. Hope this makes sense.

This will help as we are in process of releasing usermanagement, multi-lingual and theme -editor. This will help us keep the server trips in check.

**Comment by canstudios-louisem** [comment]
I've had a quick look into this and merging goes against the point of require js and its not easily do able with requirejs we can easily uglify them in prod though.

**Comment by canstudios-louisem** [comment]
Ive dug into this some more, at present `grunt build` will include files from src but 'grunt build:prod' will compile and minify all files into one. I think we can close this for now @aniketdharia @taylortom?

**Comment by aniketdharia** [comment]
ok.. will test it tomorrow morning. :) Already left office

**Comment by taylortom** [comment]
Yep, fine by me

**Comment by taylortom** [comment]
Is this still an issue?

**Comment by aniketdharia** [comment]
![screen shot 2017-09-01 at 11 43 28 am](https://user-images.githubusercontent.com/5195781/29957397-dc6f7854-8f0a-11e7-82a8-da48f809e1e3.png)

The issue is still open. Used the latest master branch

**Comment by canstudios-louisem** [comment]
@aniketdharia please can you test with the develop branch it's so different to master at the moment.

**Comment by aniketdharia** [comment]
ha yes! The grunt command is modified and also the complete folder structure in the develop branch. It seems to work ...

**Comment by canstudios-louisem** [comment]
ok ill close this for now
