### ISSUE TITLE
Server install: find alternative ffmpeg install links for Mac

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1400]
404.

**Comment by samumist** [comment]
I manage dependencies with [homebrew](http://brew.sh/) on my mac, it is pretty easy. 

Once you have homebrew installed, you just type `brew install ffmpeg` to install it. To update, run `brew update` and `brew upgrade`, very straight forward.

**Comment by taylortom** [comment]
Done
