### ISSUE TITLE
.rebuild file problem - Custom Css/Less or theme change breaks preview build

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1412]
AT 0.2.2
Framework 2.0.12

Course was fine, then made a change to custom CSS/Less. Previewing threw up attached error.
Deleted offending CSS, preview still erroring. Checked various other things it could be to no avail.
Deleted build folder and restored from a recent download.
Course then previews ok.
Add, remove or change *any* custom CSS/Less now, even original working stuff, and it breaks. Replace build with old version and it works again.

![image](https://cloud.githubusercontent.com/assets/11558341/18922771/e9b0439a-85a1-11e6-8da2-7d1a3cc7a893.png)

Replicable with several other courses. First time I have changed any custom css since upgrading to 2.0.12.

Something to do with the .rebuild file perhaps?

***update*** Yes it's the .rebuild file as this happens if I try to change theme too. If I then remove the .rebuild file from the build folder it works ok, but obviously doesn't rebuild.

**Comment by aniketdharia** [comment]
@hmaffin can you stop the server and do the following steps - 

1. npm install
2. grunt build
3. node server

Please add "sudo" if linux or mac.

**Comment by hmaffin** [comment]
Trying it now. Did remove my node_modules folder yesterday and npm installed on Dan's advice, but didn't seem to fix.

**Comment by hmaffin** [comment]
nope - till no joy i'm afraid.

**Comment by aniketdharia** [comment]
Which folder did you run the npm install? You will need to run this in all the adapt framework folders which have node modules.

**Comment by hmaffin** [comment]
ok - will try the full monty on them all :)

**Comment by aniketdharia** [comment]
😄

**Comment by hmaffin** [comment]
i deleted every nod_modules i could find. Then I had to reinstate one because when i tried to run npm install it complained (the one in C:\Adapt\nodist\bin\node_modules\npm) .

npm installing now to C:\adapt\adapt_authoring.

Where else might it have to be done? Not *all* the ones i deleted surely? there were at least 5 or 6 of them :)

**Comment by aniketdharia** [comment]
PMed you...

**Comment by hmaffin** [comment]
I deleted every node_modules folder i could find, from...
c:\adapt_authoring
c:\adapt_authoring\plugins\auth\local
c:\adapt\npm
c:\adapt\nodist
c:\adapt\nodist\v-x64\nodev4.2.2
c:\adapt\nodist\bin (but put this one back from the recycle bin as it complained about that folder not being there when i tried npm install)
C:\Adapt\adapt_authoring\temp\5614f85c4bd4be5018026e8f\adapt_framework
c:\adapt\adapt_authoring\framework (was asked to remove from here but there was no folder)

I then did "npm install" on the following...
c:\adapt\adapt_authoring\
c:\adapt\adapt_authoring\framework
C:\Adapt\adapt_authoring\temp\5614f85c4bd4be5018026e8f\adapt_framework

i then tried "grunt build" on...
C:\Adapt\adapt_authoring\temp\5614f85c4bd4be5018026e8f\adapt_framework

but it gave me the error message below.

i then tried "grunt build" on 
C:\Adapt\adapt_authoring

and that worked fine. Now have done "node server" on C:\Adapt\adapt_authoring and am going to try the interface again.

![image](https://cloud.githubusercontent.com/assets/11558341/18949602/091dead8-8634-11e6-9972-f15d7b77bc68.png)

**Comment by hmaffin** [comment]
Now getting a new error message in my node server routine that I haven't seen before...

![image](https://cloud.githubusercontent.com/assets/11558341/18949692/6438fc1e-8634-11e6-92ed-ce91a29c5f0e.png)

**Comment by taylortom** [comment]
Glad you fixed the issue! 😄 

For anyone coming late to this: the important folder is the one found in `AUTHORING_ROOT/temp/YOUR_TENANT/adapt_framework/node_modules` -- doing an `npm install` here should have fixed the issue (the clue is that the error occurred while building the framework using grunt).
