### ISSUE TITLE
An Error Occured Doing The Save

### ISSUE THREAD

**Issue by RM4G00** [adaptlearning/adapt_authoring#1414]
Hello,

Following steps for Centos- all goes well - all installed - when adding any new component - an asset for example - results in error "ERROR, an Error Occurred During the Save"

Upgraded to the latest I have all the dependencies - cant remove this error - when ok'n this error the image is uploaded and saved 

Any help would be appreciated

**Comment by RM4G00** [comment]
Anyone?

**Comment by taylortom** [comment]
Apologies for the lack of response.

Were there any errors in your server console?

**Comment by RM4G00** [comment]
How would I go about obtaining this? cat log - its basically on the front end when uploading any asset - an error occured - but it does save the asset and does display - I'd like to fix this?

**Comment by taylortom** [comment]
@RM4G00 did you ever find a fix for your issue?

**Comment by RM4G00** [comment]
No, we gave up ..Moved on which was a shame.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by taylortom** [comment]
Sorry to hear that.
