### ISSUE TITLE
Plugin manager: always seems to say there is an update when there isn't one

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1415]
When you do a "Check for Update" in the plugin manager in the AT, it pretty much always says Update available.
so you click to update
and then it stays on the same version and nothing changes.

![image](https://cloud.githubusercontent.com/assets/11558341/19149833/c172f588-8bbb-11e6-9da4-807a494ae299.png)

**Comment by taylortom** [comment]
This will be fixed in #1627 :)
