### ISSUE TITLE
Users not created in right tenant

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1421]
When we create a user using the user management plugin or even the API the users are created in the main tenant instead of them being created in the tenant they are assigned to.

**Comment by aniketdharia** [comment]
closed for now!

**Comment by taylortom** [comment]
This was closed as being 'as designed'.

It was decided that users should be independent of tenants, and that a user should be able to be assigned multiple tenants, and to switch tenants easily. Therefore, it was felt that a light coupling between tenant and user worked best.
