### ISSUE TITLE
Search tags different behaviours in two instances

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1424]
Search tags functionality has two behaviours in two instances - Dashboard and Asset management. Can we try to have similar functionality in both? or is there a specific reason to have separate behaviours?

**Comment by taylortom** [comment]
Can you be more specific about this please?

**Comment by aniketdharia** [comment]
Dashboard - The tags get added on the sidebar when we select a tag and it goes off from the list of tags.
Asset upload or addition -  When we want the add an asset we get options to filter the assets using tags, when we select a tag it gets a check mark and the box closes we need to again open the box to select another tag.

Hope this helps.
