### ISSUE TITLE
Scope tenant management requirements

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1425]
Please add a comment with requirements, and will add them to the [requirements doc](https://github.com/adaptlearning/documentation/blob/master/02_authoring_tool/04_feature_development/tenant_management/tenant-management-reqs.md).

**Comment by aniketdharia** [comment]
Create a tenant
Edit tenant
Disable Tenant
Show tenant size - data and DB

**Comment by aniketdharia** [comment]
Delete a tenant
Backup a tenant [optional]

**Comment by aniketdharia** [comment]
Import a tenant [from backup]

**Comment by lc-thomasberger** [comment]
Should we define how the tenants are separated from each other? For instance each tenant has it's own Filesystem and database.
