### ISSUE TITLE
contentobject deletion not cleaning up all courseassets

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1427]
The criteria for deletion means that only courseasset records that are directly associated with the page/menu will be removed. 

Point of issue: https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/courseasset/index.js#L87-L91

We need something like the special article case -- see https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/courseasset/index.js#L59-L79

**Comment by dancgray** [comment]
@taylortom would be good to get this in the "THEBIGFIX" if it isn't already.

**Comment by dancgray** [comment]
Also extensions with assets on articles and blocks will not currently be cleaned up.
