### ISSUE TITLE
Add ability to reorder list items

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_authoring#1430]
I have a number of people on my team that are using the resources extension and one issue they are having is once they have created a number of resources (like 10) they is no easy way to reorder those items without deleting an doing a number items over. The suggestion would be to allow the designer to drag to reorder or have an arrow to move the item up or down in the order.

Thanks,
Mark

**Comment by taylortom** [comment]
+1

**Comment by dancgray** [comment]
+1 same goes for accordion and narrative items

**Comment by taylortom** [comment]
There's a community plugin that make work for this: https://gist.github.com/tamagokun/95e76ee50f59a97696ce

**Comment by mldaq** [comment]
@taylortom - Thanks, I'll check it out.

**Comment by mldaq** [comment]
@taylortom - can you provide info on how I would use this or apply it?

**Comment by taylortom** [comment]
@mldaq it was as much a note for the dev that picks this up as something directed at you. If you have the dev capacity though, I'm happy to guide.

**Comment by SpacegoatHQ** [comment]
+1 same goes for accordion and narrative items
