### ISSUE TITLE
"Failed to connect to github.com port" error on install

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1431]
Installing the authoring tool is failing on clone of framework or on install of plugins. Example error is:

```
ERROR:  { [Error: Failed to execute "git ls-remote --tags --heads git://github.com/adaptlearning/adapt-contrib-vanilla.git", exit code of #128
fatal: unable to access 'https://github.com/adaptlearning/adapt-contrib-vanilla.git/': Failed to connect to github.com port 443: Operation timed out
]
  code: 'ECMDERR',
  details: 'fatal: unable to access \'https://github.com/adaptlearning/adapt-contrib-vanilla.git/\': Failed to connect to github.com port 443: Operation timed out\n',
  exitCode: 128 }
```

**Comment by dancgray** [comment]
Don't think this is caused by proxy servers or firewall blocking git. Suspect it could be github blocking due to frequency of calls in the install script. 

We may need to separate out the plugin install process.

**Comment by taylortom** [comment]
I haven't seen this issue recently, I'm putting it down to a server issue.

**Comment by RavenousPett** [comment]
I'm getting this issue now. Was there ever a fix found for it?

**Comment by taylortom** [comment]
@RavenousPett the problem was pretty inconsistent and seemed to resolve itself, so this hasn't been looked at. Are you still having issues?

**Comment by yabbes** [comment]
Hello folks, 
I am having exactly this problem now, trying to run "node install" on the machine I am trying to install adapt on. Sadly, I can't really say that it's resolving itself.

Is there any connection to the added message in red "Failed to create master tenant. Please check the console output"? I guess this is just the normal error message when something fails. I am getting exactly the same error as in post #1

**Comment by yabbes** [comment]
Could be that it's the "git://" type url that is responsible for the timeout? 
When I am running the command
`git ls-remote --tags --heads git://github.com/adaptlearning/adapt-contrib-vanilla.git` 
manually in the terminal I am getting a timeout as well.
But when I am running:
`git ls-remote --tags --heads http://github.com/adaptlearning/adapt-contrib-vanilla.git` 
it is working

**Comment by matachi** [comment]
I am getting the same error when trying to install Adapt. Did anyone ever figure out a workaround?

**Comment by five0va** [comment]
I have ran into this as well - Ubuntu 16.04 and CentOS 7.5: 

Updating Adapt framework plugin 'adapt-contrib-vanilla'
ERROR: Error: Failed to execute "git ls-remote --tags --heads git://github.com/adaptlearning/adapt-contrib-vanilla.git", exit code of #128
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Connection timed out
github.com[1: 192.30.255.112]: errno=Connection timed out



Failed to create master tenant. Please check the console output.

It's the "git://" part for sure. This makes the install broken and the app unusable.

**Comment by five0va** [comment]
Workaround is to force Git to use https instead of git:

git config --global url."https://".insteadOf git://

https://coderwall.com/p/sitezg/force-git-to-clone-with-https-instead-of-git-urls

**Comment by taylortom** [comment]
Thanks @five0va, have added this tip to the [Troubleshooting wiki page](https://github.com/adaptlearning/adapt_authoring/wiki/Troubleshooting#i-receive-a-ecmderr-error-during-install) for future reference.

Closing as not an Adapt issue.

**Comment by Tara-azimi** [comment]
I'm getting this error while installing the adapting tool on Windows 10. What do you think I should do? 

error [28 Jan 24 00:40:48 -08:00] Error downloading the framework Cloning into 'C:\Users\Tara\Documents\adapt_authoring _files\adapt_authoring\temp\65b612fbc13c911c943582b9\adapt_framework'...
fatal: unable to access 'https://github.com/adaptlearning/adapt_framework.git/': Failed to connect to github.com port 443 after 21357 ms: Couldn't connect to server

ERROR: Cloning into 'C:\Users\Tara\Documents\adapt_authoring _files\adapt_authoring\temp\65b612fbc13c911c943582b9\adapt_framework'...
fatal: unable to access 'https://github.com/adaptlearning/adapt_framework.git/': Failed to connect to github.com port 443 after 21357 ms: Couldn't connect to server


Failed to create master tenant. Please check the console output.
