### ISSUE TITLE
It would be good to have more control over upgrade routines

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1435]
At the moment we can only run`node upgrade` from the command line. I think it would be good to make upgrading more modular (e.g upgrading authoring tool, framework, re-installing plugins) without having to run git checkout, npm install etc in various folders. Not to mention the problems if an upgrade fails part way through.

We could probably do with listing what functionality we want to have in a production environment for upgrading? Suggestions welcome.

**Comment by taylortom** [comment]
+1 This should also apply to the install. 

We should have a way to update each moving part in isolation; oftentimes, I just want to update the server code for example.

Think we should also allow for reattempts of the different stages. Nothing more annoying than having something break near the end.

For me, the logical parts are:
- Server code
- Framework core
- Framework plugins
- *Database*
- *Tenant*

*italics*: install only

**Comment by taylortom** [comment]
Think it would also be interesting to see if we could access any of these routines from the front-end (particularly upgrading the framework).

**Comment by taylortom** [comment]
I've written a front-end plugin which shows current versions of the server and framework, and allows the framework to be updated via the UI:
https://github.com/taylortom/adapt-systemInfo

**Comment by taylortom** [comment]
See https://github.com/adaptlearning/adapt_authoring/issues/1570

**Comment by canstudios-louisem** [comment]
Are we happy to drop this from 0.4.0 and revisit upgrade at a later date? @taylortom @dancgray

**Comment by taylortom** [comment]
Yeah I think so

**Comment by taylortom** [comment]
I think this one is now covered?

**Comment by canstudios-louisem** [comment]
I think there are a few more things we could do ie separate framework and AT updates but that can be raised as a sperate issue.

**Comment by taylortom** [comment]
Cool :)

I think it's already possible to do a manual upgrade to either the AT or the FW
