### ISSUE TITLE
Casper tests are currently out of date

### ISSUE THREAD

**Issue by canstudios-adamr** [adaptlearning/adapt_authoring#1440]
#Adapt has changed a lot since the first Casper tests were written. It would be good to update these.

**Comment by taylortom** [comment]
We need to investigate whether casper's the right tool for the job, as @canstudios-louisem suggested we switch to something else (I forget what...).

I'm always a bit reluctant to spent too much time on front-end tests, as you either spend more time keeping them up-to-date than coding new things, or they just get out of date and stay out of date (as is the case now).

**Comment by canstudios-louisem** [comment]
If we do move to another tool I need to run as part of CI the reason they are out of date all the time as they don't get run enough.

The tool we use is Selenium with TestNG we use it on a real browser but QA tells me it can be used headless as well which would be my suggested use case as it's much easier to get running in CI.

**Comment by taylortom** [comment]
I'm nott suggesting we drop automated front-end testing completely, but I'm not convinced it should be used for anything other than a very high-level sweep to catch critical issues with the main workflows. 

I'm a bit dubious about headless browsers, as have had varying success with them (but fine for the above kinds of tests).

**Comment by canstudios-louisem** [comment]
I agree, maybe just tests for login, create a course, create a user, click Preview. Would give us enough app coverage to spot large issues.

In which case, a lightweight Casper tests suite would suffice.

**Comment by taylortom** [comment]
For our info, we test the following atm:

## Asset manager
- Navigate to asset manager
- Filter assets with no results
- Upload a new asset
- Filter assets with results (using new asset)
 
## Dashboard
- Click project filter buttons (list/grid, ascending/descending)  

## Projects
- Create
- Edit
   - Config.json
   - Course.json
   - Add page
   - Add block
   - Add component
   - Add/remove extension
- Copy
- Delete

## Session
- Successful log in
- Failed log in
- Log out

**Comment by oliverfoster** [comment]
casperjs is no longer updated. it needs to be replaced. https://github.com/ronaldlokers/grunt-casperjs/graphs/code-frequency

**Comment by canstudios-louisem** [comment]
I just want to check, you mean the package [grunt-casperjs](https://github.com/ronaldlokers/grunt-casperjs) which is just a wrapper for [casperjs](https://github.com/casperjs/casperjs) is out of date and we should replace it, not casperjs itself? it was the last updated on the 25 Apr 2017

**Comment by oliverfoster** [comment]
indeed. there are a few forks of grunt-casperjs which are also not worth using.

**Comment by taylortom** [comment]
These have now been removed completely
