### ISSUE TITLE
Don't know super user credentials for Adapt Authoring Tool

### ISSUE THREAD

**Issue by athyg** [adaptlearning/adapt_authoring#1445]
Please excuse my ignorance in this area....I feel as though I should know this.
I have been able to successfully install and use Adapt Authoring Tool in the past, but as I didn't get a chance to do much with it, have reinstalled from scratch.
Had a few minor hiccups, which appear to have been resolved now. However, final instructions on this page: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin are:
 - When the login page appears, enter the super user's e-mail address and password.
I thought this could be fixed by editing the config file (config.json) in config directory, which is mentioned in the info msg. So I updated the SMPT username/password and email fields, but this hasn't made any difference.
Can you please advise what the super user credentials are, or where I can find & configure them?
Thanks in advance.
Athy.

**Comment by taylortom** [comment]
Hi @athyg,

The SMTP credentials are only used for sending emails. First off, try the default login details, which are: *admin* and *password*. If these don't work, you will have to set a new password manually by updating the database.

**Comment by athyg** [comment]
Thanks for getting back to me Tom.


I tried admin/password, but no luck unfortunately. The authoring tool is asking for an email and password; does that mean it will only accept an email address as username?


Also, can you please direct me to instructions for updating the credentials in the DB?


Thanks.

________________________________

**Comment by taylortom** [comment]
Apologies @athyg, have been off for a week, and missed this before I left.

I've added instructions to [this wiki page](https://github.com/adaptlearning/adapt_authoring/wiki/Troubleshooting#how-do-i-change-my-password) -- let me know how you get on.

**Comment by athyg** [comment]
Thanks for the update Tom & apologies for the delayed response.


All sorted now, which is great. Reinstalling from scratch did the trick.

It's more than likely that I missed a step first time round!


Thanks again.

Athy.

________________________________
