### ISSUE TITLE
Allow for custom SMTP servers

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1447]
Currently we only support services listed here: https://nodemailer.com/2-0-0-beta/setup-smtp/well-known-services/

Easiest solution is to use a connection URL:
```
smtps://user%40gmail.com:pass@smtp.gmail.com/?pool=true
```

**Comment by canstudios-louisem** [comment]
We are running into an issue with this. What was the outcome of the reference PR @lc-thomasberger @taylortom I see it was close without much discussion?

**Comment by taylortom** [comment]
Looks like the fix was added to https://github.com/adaptlearning/adapt_authoring/pull/1615
