### ISSUE TITLE
User view not updating when we upload a new plugin using Tenant Admin login

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1449]
User display: When I upload a plugin using tenant admin login the plugin is added correctly in the new tenant tables but is not displayed on the frontend.

**Comment by aniketdharia** [comment]
@taylortom this has an issue right from the API point. Can you let @ambadasavhad how to proceed with this issue?

**Comment by canstudios-louisem** [comment]
This should now be solved by work done in 0.4.1
