### ISSUE TITLE
Permanently deleting a user from usermanagent does not delete the user

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1452]

**Comment by taylortom** [comment]
@aniketdharia User deletion is working as expected for me. Do you have any specific steps to reproduce?

**Comment by aniketdharia** [comment]
@taylortom this bug was added way back in November. Might be fixed. Will test again and confirm if you want me to close this issue can be done over the weekend.

**Comment by taylortom** [comment]
👍

**Comment by taylortom** [comment]
Not sure this is still relevant

**Comment by aniketdharia** [comment]
the issue closed. user gets deleted correctly. cheers!
