### ISSUE TITLE
Default feedback for Question components

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1460]
Would it be possible for the properties.schema files of all the question components to have pre filled default attributes added to them. example here https://github.com/simondate/adapt-contrib-slider/blob/master/properties.schema#L354

Not sure if this could be implemented some other way that allows the tenant owner some way to configure this feedback for their tenancy.

**Comment by aniketdharia** [comment]
We would need to keep all the required fields prefilled. This will help in framework not crashing. As currently the preview works even if required fields are not added and then the framework crashes. It just shows a loading icon.

**Comment by taylortom** [comment]
+1 for this idea.

I think we should go a step further and have generic feedback for _any_ question type.

**Comment by aniketdharia** [comment]
One more point. Should we have a separate feedback when the user clicks on Correct Answer? It will show a feedback with explanation why this answer is correct.

**Comment by taylortom** [comment]
Closing this, as is not relevant to the authoring tool. See discussion in https://github.com/adaptlearning/adapt_authoring/issues/1505 for an authoring tool solution.
