### ISSUE TITLE
StartController

### ISSUE THREAD

**Issue by webb-nickj** [adaptlearning/adapt_authoring#1462]
StartController ids are not being updated when a course is duplicated in the authoring tool

**Comment by johnniezen** [comment]
had the same problem. would save time when fixed, now when I do preview if I forget then I see the homepage. Need to go back and fix. +1 from me when fixed

**Comment by taylortom** [comment]
Will be fixed in https://github.com/adaptlearning/adapt_authoring/issues/1752
