### ISSUE TITLE
Inconsistency with default _isEnabled value

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1471]
Sometimes it's set to true sometimes false. Should have consistency.

**Comment by taylortom** [comment]
Broadly agree, although I think this has been set up based on what users are most likely to choose. In the case of spoor, isEnabled is most likely to be true, whereas you don't want an assessment to be enabled on every article by default.

**Comment by taylortom** [comment]
Closing this, as is not relevant to the authoring tool. See discussion in https://github.com/adaptlearning/adapt_authoring/issues/1505 for an authoring tool solution.
