### ISSUE TITLE
outputmanager is preventing correct asset paths being written for assets in contenObject collection

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1474]
It will only convert asset paths for attributes _graphic.src

https://github.com/adaptlearning/adapt_authoring/blob/master/lib/outputmanager.js#L770

Some extensions or menus may set assets here.

Use case: I have an extension that adds an asset to contentObject. The asset is not defined as _graphic.src. Output manager will not add the lang folder to the path.

**Comment by dancgray** [comment]
@taylortom this is still an issue for the current dev branch (0.4.0 RC)

**Comment by taylortom** [comment]
Fixed in #1717
