### ISSUE TITLE
Setting percentage values causes error

### ISSUE THREAD

**Issue by Johntyb** [adaptlearning/adapt_authoring#1476]
Whenever I attempt to include a % symbol in CSS or a component config setting this returns an error when saving, thus preventing me from continuing.

This relates to the Adapt Builder.

**Comment by Johntyb** [comment]
This relates to the Adapt Builder.

**Comment by tomgreenfield** [comment]
Hi, which browser are you using and in particular which attributes/fields are giving you trouble?

If the plugin's properties schema has been set up correctly then it usually isn't possible to type non-numerical characters.

See [here](https://github.com/adaptlearning/adapt-contrib-slider/blob/master/properties.schema#L144-L151) for a working example.

**Comment by taylortom** [comment]
I've tested this in a few places, and can't replicate. In the cases where only numerical values are allowed, you can't input a % at all. All other cases save fine for me.

@Johntyb I'll close this issue in due course if we don't hear a response.
