### ISSUE TITLE
Enhancement: Minimize articles

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1483]
I have some pages which use block slider so the articles are many blocks long. If I have a few of these on the page the page can get very long and finding what I need is getting tricky.

I suggest that the article bar has an icon on it (+ and -) that allows you to minimize the article to a bar so you can work on other articles while leaving those at a minimum intrusion on the page.

Hope that makes sense!

**Comment by johnniezen** [comment]
Makes lots of sense to us. We started using the Block Slider in December, and my team members love it, but also grumble over the length while editing. Specialy when you always start at the top again after editing any part on the page.

**Comment by hmaffin** [comment]
Yes John, the fact it doesn't keep scroll position when you save and go back can be a pain in the behind - if you don't keep on top of naming articles and blocks properly like me *whistle*

**Comment by taylortom** [comment]
This sounds like a pretty useful feature, especially considering the lack of a page overview/navigator feature. Could potentially replace the delete button (always been a bit unsure about having it there and in the actions dropdown).
