### ISSUE TITLE
Copy and paste losing extensions data

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#1484]
I have copied/duplicated several articles on a page before and they turn off important settings in my extensions such as block slider where I have got the article set as I want. 

From Kineo testing:
> If the user copies and pastes a page/article/block the new instance does not retain the settings of the original instead all form data fro plugins on block/article/page level reverts to default.

**Comment by dancgray** [comment]
Also getting this issue.
