### ISSUE TITLE
Reducing repetitive actions

### ISSUE THREAD

**Issue by Deathjam** [adaptlearning/adapt_authoring#1485]
Sorry in advance if these are already setting that I've missed.

Allow default settings applied for the entire project in `Project Settings`, then any settings changed at the block/component level will be for that block/component only. 

Sometimes i want to set all the default text/options to the same thing. It is quicker to change 1-2 to be something different then to change them all.

This will be useful for

- Tutor
- Trickle
- Question components (Display Model Answer, Display Attempts, Randomised Items, etc)

**Copy & Paste**

If i copy a Block/component, the pasted Block/component keeps all the same details, expect for any extension settings, can be annoying to copy&paste a lot of graphic components and have to reset page level progress on all of them.

Ability to continue to paste after initial paste, maybe once you copy something a control appears, which you have to exit out of to stop pasting ability

**Comment by hmaffin** [comment]
We reported the copied block issue here as well - https://github.com/adaptlearning/adapt_authoring/issues/1484

**Comment by moloko** [comment]
someone else (from King's College?) mentioned wanting something that sounded very like this at the Adapt Meetup on Tuesday...

Some way of being able to create default settings for certain plugins at a project level definitely sounds like a time-saver to me.

**Comment by taylortom** [comment]
@Deathjam can I politely request that we split this into separate issues?
- Support default settings
- Multiple copy/paste
- ~Copy/paste losing extension config (#1484)~

**Comment by Deathjam** [comment]
Closed and split into individual issues

* Multiple copy/paste https://github.com/adaptlearning/adapt_authoring/issues/1504
* Support default settings https://github.com/adaptlearning/adapt_authoring/issues/1505
