### ISSUE TITLE
Menu and page editor should display the course/page title

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1486]
It's not easy to tell which course/page you are editing from these screens, would be useful to orientate the user within the tool.

**Comment by hmaffin** [comment]
Totally agree - was thinking this in the last few days especially after editing the wrong page - d'oh!

**Comment by taylortom** [comment]
I've implemented a version of the breadcrumb trail as was included in the updated AD:

![screen shot 2017-01-21 at 17 10 36](https://cloud.githubusercontent.com/assets/1059083/22176200/c0827398-dffc-11e6-9a91-825cba3f1577.png)

The breadcrumb segments describe the page, while the page title is set to the title. Each segment is also a clickable link.
