### ISSUE TITLE
Drop support for vagrant

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1503]
This was discussed at the roadmap meeting.

Will involve the following:
- Removing relevant files from the repo
- Updating the wiki/removing references in the install instructions
- Potentially researching an alternative option (docker?)

**Comment by taylortom** [comment]
As agreed in the weekly meeting 8/02/17:
- Test installation on Windows
- Improve windows-specific install instructions if necessary 
- Investigate Docker as an alternative

**Comment by canstudios-louisem** [comment]
We did some docker investigation which I can dig out, or is the current plan to just to drop vagrant? if so should we remove the special cases for it?

**Comment by taylortom** [comment]
I'd be most comfortable just dropping vagrant without a replacement, unless we can get several people to commit to supporting the alternative.

**Comment by canstudios-louisem** [comment]
can we close #1000 and #1006 with this?

**Comment by taylortom** [comment]
Yep!
