### ISSUE TITLE
Option to output JSON as .txt

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_authoring#1506]
For the rare occasions where a server cannot be configured to allow JSON file types, it would be good to have the ability to publish as .txt files and for the ```app.js``` to handle this.

**Comment by taylortom** [comment]
I wonder if we could implement this as part of the grunt process (would probably also need a tool-side config option still).

**Comment by taylortom** [comment]
Is this still an AT requirement?

**Comment by taylortom** [comment]
Being worked on with #2102
