### ISSUE TITLE
Remove build includes from export

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1511]
As we only add the relevant plugins, this often adds extra complexity to those not familiar with the feature.

**Comment by moloko** [comment]
when this is done and released, please could you delete [the section on manually removing this property](https://github.com/adaptlearning/adapt_authoring/wiki/Exporting-Course-Source-Code#remove-the-includes-array-from-the-configuration-file) from the wiki page on exporting?
