### ISSUE TITLE
Menu background image

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1530]
Would it be possible to have a way to upload a menu background image for a course without having to use the theme.

I can appreciate this is could cause issues with different menu types but could we just have support for the box menu and then disable it for other menus?

**Comment by taylortom** [comment]
This will be possible with https://github.com/adaptlearning/adapt_authoring/issues/1116. This issue should probably be raised in the framework repo when that's done.

**Comment by taylortom** [comment]
Closing, as duplicate of #1116
