### ISSUE TITLE
Default option doesn't work for select input with string options

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#1539]
Inputs of type boolean can use the "default" option to choose an option which will be selected by default.

This "default" option does not work for select inputs with string options. It should be possible to define which will be selected.

**Comment by tomgreenfield** [comment]
I actually can't replicate this on the develop branch. Seems to be working fine now.

Schema example:
```json
"_selectTest": {
  "type": "string",
  "default": "blue",
  "inputType": {
    "type": "Select",
    "options": [
      "red",
      "blue"
    ]
  }
}
```

**Comment by danielstorey** [comment]
I've experienced a similar issue. From what I can deduce so far default options work fine on extensions but are blank on components.

**Comment by simondate** [comment]
We've had this issue recently with the Trickle extension since we've upgraded the latest version of the AT.
