### ISSUE TITLE
Allow for pages without a sidebar

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1541]
If no sidebar is added, you just get the empty column. Would be nice if we could have nice styling in this case -- maybe hiding completely and centring the page.

**Comment by taylortom** [comment]
https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/modules/sidebar/less/sidebar.less#L127-L134

**Comment by canstudios-nicolaw** [comment]
@lc-thomasberger just assigning to you so it's clear this has been worked on
