### ISSUE TITLE
How To Install FFmpeg and FFmpeg-PHP Extension on CentOS 7

### ISSUE THREAD

**Issue by Nirjonadda** [adaptlearning/adapt_authoring#1572]
Please can you let me know that How To Install FFmpeg and FFmpeg-PHP Extension on CentOS 7 with cPanel?

**Comment by taylortom** [comment]
Have a look at the links on the following page, you may find something useful: https://github.com/adaptlearning/adapt_authoring/wiki/installing-ffmpeg

**Comment by Nirjonadda** [comment]
@taylortom I am asked to support installing CentOS 7

**Comment by taylortom** [comment]
We can't offer support for third party products I'm afraid. Maybe check on the [FFmpeg site](http://ffmpeg.org/).
