### ISSUE TITLE
Schema values for _accessibilityToggleTextOff and _accessibilityToggleTextOn are incorrect

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1575]
https://github.com/adaptlearning/adapt_authoring/blob/81c26222cc02e00b039fe1e207aa17421ad05921/plugins/content/course/model.schema#L141

https://github.com/adaptlearning/adapt_framework/blob/master/src/core/schema/course.model.schema#L152

**Comment by tomgreenfield** [comment]
It's actually the framework schema that is out of date following the changes in https://github.com/adaptlearning/adapt_authoring/pull/1317 & https://github.com/adaptlearning/adapt_framework/pull/1194.

**Comment by dancgray** [comment]
Thanks @tomgreenfield I'll close this issue. Do you want me to raise a ticket for a change to course.model.schema in the framework?

**Comment by tomgreenfield** [comment]
Yes please, cheers @dancgray.
