### ISSUE TITLE
Switch over to node v8

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1580]
v4 goes into 'maintenance' from April, with v6 taking over as the active LTS. I've heard two reports that there's nothing to do for this, so may be a nice clean switch.

See https://github.com/nodejs/LTS for more.

**Comment by canstudios-louisem** [comment]
Should we consider 8.x it is production ready and will go into LTS with the end of its maintenance being December 2019. It would give us even more of a performance boost with v8 5.8 and access to things like `util.promisify()`.

**Comment by taylortom** [comment]
@canstudios-louisem I'm happy to take this approach, and aim to get a release out in october to support v8. 

Seems a bit pointless going for v6 at this point.

**Comment by canstudios-louisem** [comment]
Should we update the [travis.yml](https://github.com/adaptlearning/adapt_authoring/blob/master/.travis.yml) file to start testing node 7 and 8
