### ISSUE TITLE
Revisit browser support

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1581]
Given the current [ongoing discussion](https://community.adaptlearning.org/mod/forum/discuss.php?d=1946) regarding dropping legacy browser support in the framework, I thought it was probably time to do the same for the authoring tool. At Kineo, we require modern browser support (IE11+, Safari 7[??], Evergreen Chrome & FF)

At the very least, I think we should look at dropping IE9 & IE10 support.

**Comment by lc-thomasberger** [comment]
It is time to drop IE 9 and IE 10.
I suggest we only support latest Edge, Safari, Chrome and Firefox.

**Comment by canstudios-louisem** [comment]
Are we suggesting any code changes or is this just symbolic? if its the latter I'm happy to do that as part of 0.5.0.

**Comment by lc-thomasberger** [comment]
Symbolic for now, but I think we should do a code cleanup in the Frontend.

**Comment by canstudios-louisem** [comment]
Ok well I'm happy to drop them as it means we get one step closer to using more ES6 features.

**Comment by taylortom** [comment]
Closing as duplicate of https://github.com/adaptlearning/adapt_authoring/issues/1743
