### ISSUE TITLE
Upgrade to latest versions of Adapt_Authoring Tool (v0.2.2 to v0.3.0) and Adapt_Framework (v2.0.7 to v2.0.17)

### ISSUE THREAD

**Issue by omololuwa** [adaptlearning/adapt_authoring#1585]
When I ran "node upgrade" after a successful installation of Adapt_Authoring Tool v0.2.2 and Adapt_Framework v2.0.7, the upgrade process successfully installed all the Adapt_Authoring Tool dependencies. However, when it got to the "**Building front-end**" process, the following errors occurred while "**Running "requirejs:compile" (requirejs) task**" and the upgrade process just hanged "forever". 

**Running "requirejs:compile" (requirejs) task

{ [Error: Error: Module loading did not complete for: core/app/app, sweetalert, coreJS/notify/notify, coreJS/notify/plugins/alert/index
    at Function.build.checkForErrors (/Users/lolu/adapt_authoring/node_modules/requirejs/bin/r.js:31556:19)
]
  originalError: [Error: Module loading did not complete for: core/app/app, sweetalert, coreJS/notify/notify, coreJS/notify/plugins/alert/index] }

ERROR: 1**

So, I'm unable to do the upgrade. Meanwhile, would it not be better if the latest releases of the Adapt_Authoring Tool v0.3.0 and Adapt_Framework v2.0.17 are available so that I can do a fresh installation of the new releases either through a direct download or cloning ?

Regards.

Omololuwa

**Comment by caztillo** [comment]
Hello, I have the same error. Can someone help us? thanks

**Comment by canstudios-louisem** [comment]
@taylortom why was this added to the milestone? Could you put some more information or is this just for investigation?

**Comment by taylortom** [comment]
I think it was to investigate in light of the refactor, and close off, as may no longer be relevant

**Comment by taylortom** [comment]
Note to update package.json to latest versions
