### ISSUE TITLE
Components with "Add" items,  button location

### ISSUE THREAD

**Issue by Deathjam** [adaptlearning/adapt_authoring#1587]
A small UI thing, on components with the add item button, including when it is in drill down menus ( ie matching question component)

Can the Add button be stuck to the top where it says Items:

![image](https://cloud.githubusercontent.com/assets/1510595/23909565/f97c99a8-08ce-11e7-86c2-1cf9758925c6.png)

i can add about 3-4 items before the button drops off the screen
knowing where the button will always be will help improve speed when adding multiple items, instead of:
add item 
scroll to to get button into view
add item
scroll to to get button into view
add item
etc

**Comment by derhuebiii** [comment]
Also, is there something planned to add items inbetween? Or resorting of items? Didn't find any request.

**Comment by taylortom** [comment]
We have a similar issue here: https://github.com/adaptlearning/adapt_authoring/issues/1430

**Comment by lc-thomasberger** [comment]
#1430 is for reordering items.
I think this one should only be concerned about re positioning the add button to the top of the list.

**Comment by taylortom** [comment]
Yeah that was a response to @derhuebiii

**Comment by tomgreenfield** [comment]
Please see https://github.com/adaptlearning/adapt_authoring/pull/2172#issuecomment-452280254 & https://github.com/adaptlearning/adapt_authoring/pull/2172#issuecomment-456329160.
