### ISSUE TITLE
CKEditor is stripping out attributes and styles

### ISSUE THREAD

**Issue by liquidmelon** [adaptlearning/adapt_authoring#1619]
this issue is easy to replicate by adding the data attribute to a span in the source editor of a component, for example:
`<span class="tidbit-trigger tidbit-color" data-bitnum="0">your text here</span>`

if you edit anything in the component a second time, the data attribute will get stripped

based on the [CKEditor documentation](http://sdk.ckeditor.com/samples/acf.html), CKEditor filters incoming HTML content by transforming and deleting disallowed elements, attributes, classes and styles.

taking what is already in the code and adding two things, i have a solution. change this line: https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/scaffold/scaffoldOverrides.js#L125

to this:
`extraAllowedContent: 'span(*)[*]{*}',`

please note that this might only fix the span tag ([see this post](https://community.adaptlearning.org/mod/forum/discuss.php?d=1857#p9032)). there's [another post in the forum](https://community.adaptlearning.org/mod/forum/discuss.php?d=1849) that appears to be doing this to ordered list tags.

the editor documentation shows that specific things can be allowed or disallowed. there is also a way to allow everything... so maybe changing line 125 to this might also fix the ol tags? i haven't tested this theory, just putting it out there:
`allowedContent = true`

**Comment by lc-thomasberger** [comment]
Also `<button>` tag's are stripped out when added as html markup. Plugins like glossary do use `<a>` links to reference Glossary Items from the content. Those should be converted to `<button>` to fix issues on iOS.  This requires a way to add `<button>`'s through CKEditor.

**Comment by melmilloway** [comment]
A callout in case anyone wants to put multiple items. Here's mine for svgs.

extraAllowedContent: ['svg(*)[*]{*}', 'path[*]', 'polyline[*]', 'g[*]', 'ellipse[*]'],

**Comment by lc-thomasberger** [comment]
`extraAllowedContent: 'span(*);*(*);button[name]',`
for buttons and classes in general

**Comment by taylortom** [comment]
Think we need to make this configurable somewhere, as it may be a security concern for some people (similarly,some may want it to be even more lenient).

**Comment by lc-thomasberger** [comment]
Load a custom config file on installation + a set of default settings?
For instance: allow all, better styling, save mode, ...

**Comment by ceplICT** [comment]
Am I missing something? I tried changing my config/config.json  to "ckEditorExtraAllowedContent": "span(*)[*]{*}" but adapt still removes tags added to elements (data-bitnum="0")

**Comment by chucklorenz** [comment]
@ceplICT After changing the config file, did you attempt to rebuild and restart the authoring tool? If not, give that a shot.
