### ISSUE TITLE
Floating blocks / missing article _parentId

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_authoring#1622]
@mldaq had a course in the authoring tool in which at least one block was being published without a parent article.

you can reproduce the error by deleting "a-10" from the standard adapt_framework build.

it looks something like this:
![image](https://cloud.githubusercontent.com/assets/7974663/25343271/728f88a8-2906-11e7-96fc-c5968b7b0c75.png)

**Comment by simondate** [comment]
related to #1700
