### ISSUE TITLE
All components and extensions are included in preview and  download

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1623]
Removing the build includes from lib/outputmanager.js results in all components and extensions being included in preview and download.

Export source code only includes enabled extensions.

**Comment by canstudios-nicolaw** [comment]
Hi Dan,
We have noticed this at Can, it appears the bug came from https://github.com/adaptlearning/adapt_authoring/pull/1586 

I will make a PR to revert this change

**Comment by canstudios-nicolaw** [comment]
https://github.com/adaptlearning/adapt_authoring/pull/1664
