### ISSUE TITLE
Cannot lock a sub menu

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1625]
In the authoring tool _lockType attribute can only be set on course model. This prevents sub menus from being locked as _lockType needs to be set on the menu contentObject.

See framework [wiki](https://github.com/adaptlearning/adapt_framework/wiki/Locking-objects-with-'_isLocked'-and-'_lockType') :

> The normal use case has the menu at the root level of the course and so the _lockType should be added to course.json. For a sub-menu, the _lockType should be added to the content object (in contentObjects.json) which is the parent of the pages to be locked. 

[_lockType](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/course/model.schema#L598) attribute should be added to contentObject [schema](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/contentobject/model.schema).

Unfortunately this will also be displayed on page type contentObjects.

"The schema needs to be updated to allow this to be set on content objects too."

**Comment by dancgray** [comment]
This is a duplicate of #1363

**Comment by canstudios-nicolaw** [comment]
Can this be made into a PR? If so we would be happy to approve

**Comment by dancgray** [comment]
@canstudios-nicolaw apologies, must have missed referencing it on the [PR](https://github.com/adaptlearning/adapt_authoring/pull/1647). I think there is a usability issue with it appearing on pages as well as menus.

**Comment by canstudios-nicolaw** [comment]
Ah I thought it rang a bell! My apologies should have looked through the PRs
