### ISSUE TITLE
Install script needs to be updated to encompass latest changes

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1626]
- `rootUrl`: used for the password reset email. Currently, the install script does not set it in the config file.
- `useSmtp`
- `root`

**Comment by dancgray** [comment]
The config wiki is [here](https://github.com/adaptlearning/adapt_authoring/wiki/Configuring-the-Authoring-Tool)

**Comment by canstudios-louisem** [comment]
Do we want to add `trackingId`? most people add it after although some people may use if you do programmatic installs.

**Comment by taylortom** [comment]
Don't see why not.

**Comment by canstudios-louisem** [comment]
this is done in #1667
