### ISSUE TITLE
ETIMEDOUT error

### ISSUE THREAD

**Issue by SeemaSP** [adaptlearning/adapt_authoring#1629]
When I ran the node install, it gave the following error after having collected all the config data:
ERROR:  { [Error: Request to http://adapt-bower-repository.herokuapp.com/packages/search/adapt-contrib-vanilla failed: ETIMEDOUT] code: 'ETIMEDOUT' }
Install was unsuccessful. Please check the console output.

Why is it requesting heroku server for adapt-contrib-vanilla when there is a repo of this on github?

**Comment by SeemaSP** [comment]
Well I found the issue. Just hat to export the http_proxy value.

**Comment by taylortom** [comment]
@SeemaSP glad you solved the issue :)

We use a public bower repository to keep a record of all registered plugins, which is used for things like the [plugin browser](https://www.adaptlearning.org/index.php/plugin-browser/). The source files aren't stored here, only a link to the git repository (which in the case of most plugins is in fact GitHub).

**Comment by catchshiv** [comment]
I'm facing the same issue. I'm newbie in installing Adapt. Can somebody elaborate on how install Adapt.

**Comment by catchshiv** [comment]
@SeemaSP: can you elaborate on how to export the http_proxy value?
