### ISSUE TITLE
Stuck Installing Windows VM Ware

### ISSUE THREAD

**Issue by Basti922** [adaptlearning/adapt_authoring#1646]
![grafik](https://cloud.githubusercontent.com/assets/29119470/26674373/9029423c-46c0-11e7-95ac-6d02342cd4bd.png)

Hello, 

it stucks installing it on Windows with VM ware. 

Thanks!

**Comment by taylortom** [comment]
Hi @Basti922, are you trying to install the authoring tool or framework?

**Comment by Basti922** [comment]
Hello the Authoring tool.

**Comment by taylortom** [comment]
@Basti922 what steps did you follow to get to this point? There seems to be a problem with the git repo for the authoring tool files.

**Comment by taylortom** [comment]
Closing due to lack of response.
