### ISSUE TITLE
Update package.json and version.json version numbers

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1649]
Just a reminder so it doesn't get forgotten like it has in the past

**Comment by tomgreenfield** [comment]
Note: with the develop branch, it seems that the version checking is a buggy regardless:
```console
You are currently running Adapt authoring tool v0.3.1 - v0.3.0 is now available
```

**Comment by canstudios-louisem** [comment]
The current version checking is very simple it gets the latest tag from GitHub and does an if `!==` on that.
