### ISSUE TITLE
Create User XSS

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1652]
Intercepting the request to create a new user, and then enter a script into the email address and this will run when displayed. This is prevented when entering the email address via the browser but is not stripped when stored or displayed via hbs.

**Comment by taylortom** [comment]
Think this has been fixed by @ambadasavhad in https://github.com/adaptlearning/adapt_authoring/commit/5894f1132dab8912a20971be960288573bc4df04
