### ISSUE TITLE
Tenant Admins do not see full list of users within tenant

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#1655]
The Tenant Admin user can see all accounts within their assigned tenant. However, the user will need to click the <Refresh> button a few times in order to see the full list. This issue occurs per browser session.

Steps to reproduce:
01) Log in as a Tenant Admin. Navigate to "User Management".
02) Click the <Refresh> button. Notice that the list becomes more complete per click.

**Comment by canstudios-louisem** [comment]
This has been fixed
