### ISSUE TITLE
Ability to limit 'Number' editor to a specific range

### ISSUE THREAD

**Issue by barrymckay397** [adaptlearning/adapt_authoring#1659]
It would be good to be able to specify min and max attributes for Number editors in the schemas.

This could be achieved via a Scaffold override, perhaps making use of the Backbone Forms validators i.e.
      "validators": [
        {"type": "range", "min": 1, "max": 100}
      ]

If detected, the Scaffold override could then apply the 'min' and 'max' attributes to the editor element. This ensures there is also a validation rule applied to the editor.

It seems that 'step' can be defined within an 'editorAttrs' object

**Comment by tomgreenfield** [comment]
As you mention, Backbone Forms includes a range validator so we don't actually need to implement any override.

Please test with this [branch](https://github.com/tomgreenfield/adapt_authoring/tree/issue/1544) which has includes the latest version of Backbone Forms.

Example schema:
```json
"_percentage": {
  "type": "number",
  "default": 50,
  "title": "Percentage",
  "inputType": "Number",
  "validators": [
    {
      "type": "range",
      "min": 0,
      "max": 100
    }
  ]
}
```

**Comment by barry-learningpool** [comment]
The purpose of this override though is to ensure the min, max values defined in the validator are actually applied to the <input>

**Comment by tomgreenfield** [comment]
Gotcha!

**Comment by tomgreenfield** [comment]
Can I therefore suggest we add something like the following to our [`setUpSchemaFields()`](https://github.com/tomgreenfield/adapt_authoring/blob/issue/1544/frontend/src/core/scaffold/scaffold.js#L53-L109) function:
```js
var editorAttrs = field.editorAttrs;

if (editorAttrs) {
	scaffoldSchema[key].editorAttrs = editorAttrs;
}
```

This would add an awesome amount of flexibility through feeding in attributes to the form element, as designed in Backbone Forms. It also avoids having to implement overrides to the library.

Example schema:
```json
"_bigSteps": {
  "type": "number",
  "default": 100,
  "title": "Big steps",
  "inputType": "Number",
  "validators": [
    {
      "type": "range",
      "min": 0,
      "max": 1000
    }
  ],
  "editorAttrs": {
    "step": 100,
    "min": 0,
    "max": 1000
  }
}
```

**Comment by barry-learningpool** [comment]
Good shout! I've made the change, works well

**Comment by tomgreenfield** [comment]
While I'm here, could I make a shameless plug for a +1 on the Backbone Forms upgrade?

`https://github.com/adaptlearning/adapt_authoring/pull/1548`

**Comment by taylortom** [comment]
Superseded by scaffold refactor
