### ISSUE TITLE
_disableAnimationFor attribute is missing from config schema

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1675]
Can't see why this should not be exposed in AT. In framework [here](https://github.com/adaptlearning/adapt_framework/blob/be7d695c8eeed47c2025f0c7687c48f12e7e5c2c/src/course/config.json#L38) and [here](https://github.com/adaptlearning/adapt_framework/blob/8b3446376e42fdf8fe2e3897916d3cc170470da8/src/core/js/models/configModel.js#L33)

**Comment by tomgreenfield** [comment]
This was resolved in 0.6.3 when we switched to utilising the framework schemas.
