### ISSUE TITLE
Component display set to "false" breaking course preview

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#1682]
Hi there is a pretty big issue with Adapt authoring tool v0.3.0 / Adapt Framework v2.1.3

I have tested on a couple machines with the same versioning for authoring tool and framework and I am getting the same results across the board on this one. When I set any component's display to "false" and then preview the course it breaks the course preview by the loading window constantly spinning and never going away. When I set the component's display back to "true" it works fine again. I use this great feature a lot so it would be great if you could fix it back to working again like previous versions. Right now I am adding custom CSS classes in to hide components which is needed for the Quick Nav controls at the bottom of the page since it needs to go in it's own article. Here is a screen shot of what I mean...
![adapt_display_false](https://user-images.githubusercontent.com/10455453/28373668-d8bc2e30-6c70-11e7-9380-88ba3e6dfb8f.jpg)

**Comment by tomgreenfield** [comment]
Have you ensured there is at least one _available_ component in each block?

**Comment by brian-learningpool** [comment]
That fixes it for me.  Perhaps we should add an `Adapt.log` call to highlight this?

**Comment by mike-st** [comment]
Thanks for looking into the issue appreciate it! Your right that is true it works if I have 2 half components with one displayed to False.

Thing is I am trying to use the Quick Nav and I don't want the extra padding space at the bottom of my course which is created by the last article's component which is needed for the Quick nav to show. By selecting false for display on that component it nicely fixed the padding issue in old versions.

I am using custom class which works fine too but would be great to have it working on the Full component in the future if possible again. Didn't mean to make this sound like a huge issue but it would be a nice one to have fixed. Thanks again to you both.

**Comment by taylortom** [comment]
This needs moving to the framework repo, will look into this.

**Comment by taylortom** [comment]
Have discussed this with the framework guys, and found out that quicknav has become a component, so this is no longer applicable. See the [component's page](https://github.com/cgkineo/adapt-quicknav) for more info.
