### ISSUE TITLE
Deleting files/folders can cause EPERM errors on windows

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1698]
We've observed this in relation to `node_modules` folders in `/temp`, which often take a long time to index, causing text editors and virus scanners to hang onto files.

A possible solution could be to prefix any offending folder names with a `.`.

**Comment by taylortom** [comment]
@tomgreenfield, @lc-thomasberger I haven't seen/heard of this one recently, shall close it if you're happy

**Comment by tomgreenfield** [comment]
Don't remember this one @taylortom; happy for it to go.
