### ISSUE TITLE
Copy function fails if course has orphaned components

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1701]
As per #1700 occasionally you can have a course with a component whose parent block has been deleted but it hasnt.

When you attempt to copy the course the copy fails as it can't find the components parent block by id. 

We need to handle this better, I think it would be safe to just not copy that content.

It would also be good if the copy function would delete a failed to copy course as it will be broken anyway this would help to limit user confusion.

**Comment by taylortom** [comment]
I've added the below 'workaround' for this specific use-case until we figure out why this is happening (although it's probably worth having some kind of defensive programming anyway rather than just assuming the structure's fine and dandy):
```javascript
if(oldParentId && !contentData._parentId) {
  logger.log('warn', `Cannot copy ${contenttype} '${oldId}', cannot find parent object with ID '${oldParentId}'`);
  return next();
}
```
