### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1704]
Need to make sure we support current/supported versions of our npm deps.

Particular issue with:
- grunt-casperjs v2 which errors (v1 looks to work ok).
- nodemailer no longer supports node v4

It's been suggested that we cut out as much dead wood as we can to keep these kind of issues to a minimum.

**Comment by taylortom** [comment]
Related to #1440

**Comment by canstudios-louisem** [comment]
Their are a few tools that we can use to help upgrade npm deps easier https://www.npmjs.com/package/next-update and greenkeeper.io both look useful.

**Comment by canstudios-louisem** [comment]
Related to #1121

**Comment by canstudios-louisem** [comment]
Something to be aware of, in with npm 5 (standard in node 8) npm now creates a `package-lock.json` similar to `composer.lock` and is intended to be committed into VCS.

I have not used it yet and am unsure of its advantages of YARN but if we did not wish to require another global package it may be a good option.

**Comment by canstudios-louisem** [comment]
Could we suppress the depreciation warnings from NPM they seem to cause some users undue worry?

**Comment by taylortom** [comment]
@tomgreenfield assigned this to you for visibility -- this was done as part of your PR, right?

**Comment by tomgreenfield** [comment]
@taylortom, naturally.
