### ISSUE TITLE
Investigate link between frontend & backend plugin architecture

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1713]
Plugins often require both frontend and backend bits. We need to look into making this as simple as possible, while also keeping flexible. Ideally, a dev could drag and drop a single folder (or a frontend and backend folder)

Things to think about: 
- Localisation strings: these should be in the plugin folder rather than the single app file
- Tests: we should be able to support tests in a plugin folder
- Routes: currently, only routes in the `routes` folder are supported
- Dynamic loading: i.e. being able to drag n' drop a plugin without having to amend any core code

**Comment by canstudios-louisem** [comment]
Can have raised some similar issues internally and one thing we would really like to see is more of a hooks/events system. The front end events work really well for adding more functionality but they are limited. 

On the back end, you can keep most of your code in separate files but you often have to make changes to core files as well some kind of hooks system would work really well allowing us to respond to events and make changes to the passed event data.

NodeBB is a really good example of a hooks system done well https://docs.nodebb.org/development/plugins/

**Comment by taylortom** [comment]
We have some hooks for content-related actions (see https://github.com/cgkineo/adapt_authoring/blob/production/lib/contentmanager.js#L417). Is this what you were thinking of?

**Comment by canstudios-louisem** [comment]
Yep if that kind of think was added and standardised i think it would allow much more modular code.

**Comment by taylortom** [comment]
Closing due to irrelevance
