### ISSUE TITLE
Upload of Bower plugin fails with error msg "invalid signature: 0x20200a7b"

### ISSUE THREAD

**Issue by UlfChristensen** [adaptlearning/adapt_authoring#1732]
When trying to upload a Authoring Tool plugin packed by the grunt-contrib-compress task it fails with the rather unhelpful error message "invalid signature: 0x20200a7b".
This seems to be caused by unzip not handling the "store" attribute on the zip archive correctly.

Steps to reproduce:
 - Repack any Bower plugin using grunt-contrib-compress using these options:
     `options: {
                    mode: "zip",
                    archive: "./plugin_name.zip",
                    store: true
                }`

- Use the Authoring Tool to install the resulting archive via the "Upload Plugin" functionality.

Related issue: #920

**Comment by canstudios-louisem** [comment]
Does this occur without the store argument? What is your reason for using the store argument? I assume its just quicker if it's not compressing?

**Comment by UlfChristensen** [comment]
@canstudios-louisem
From my experiments it did not matter if the store argument was explicitly set or not. 
The problem is most likely due to the fact that the grunt-contrib-compress task generates archives that actually embeds the "store" argument and the unzip task cannot handle that argument.

**Comment by canstudios-louisem** [comment]
@UlfChristensen so any zips generated with grunt-contrib-compress fail?

**Comment by UlfChristensen** [comment]
@canstudios-louisem
At least according to my experiments....
