### ISSUE TITLE
What OS's and software versions do we support

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1743]
## Affected Area
Install and upgrade

## Requested Feature
We currently do not specify what OS's and nginx/apache versions we support. The node version support is woolly at best as well.

## Use Case
We have lots of people having issues installing the AT this would help users to install and us to debug as we cant be expected to debug on every strange system config.

**Comment by canstudios-louisem** [comment]
For me its very hard to support or give help to people using windows and I do think we should at least say only Unix is supported for a production environment.

**Comment by taylortom** [comment]
Discussed in catch-up to publish 'recommended specification' list of software requirements

**Comment by taylortom** [comment]
Have started the below page. Wasn't sure what to put, so please have a proof-read and add/change anything as necessary.
https://github.com/adaptlearning/adapt_authoring/wiki/Recommended-system-requirements
