### ISSUE TITLE
Changes to course model.schema don't appear

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1754]
## Expected Behaviour
A change is made to course's model.schema and it appears in the product.
## Actual Behaviour
Nothing happens.
## Steps to Reproduce
1. Create a change in [course's model.schema](https://github.com/KingsOnline/adapt_authoring/commit/79732f9a79e8c9cfac2bcba23542ed968d08f7ff#diff-46d4105de41cab367f5690e1448f0ec1R628)
2. run `node install` to rebuild Adapt AT 
3. Observe if something happened.

## Versions
  - Authoring Tool Version: 0.4
  - Framework Version: 2.2.2
  - Operating System: Mac
  - Browser: Chrome

**Comment by taylortom** [comment]
This is as expected -- running the install script will reset all local changes according to the

**Comment by canstudios-louisem** [comment]
Does anything need to be done here or can we close this? @taylortom

**Comment by taylortom** [comment]
Nothing to do imo, I'd say it's expected that running the install script is a destructive task. 
Any objections?
