### ISSUE TITLE
largely populated AT instance running slow after v0.4 upgrade

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1758]
Since we upgraded to v0.4 the AT has been running really slow (like takes 15s to load a course when it would previously take 2s).

This was never an issue on my local installation or our dev installation, which runs of the same server and config as the live one.

## Versions
  - Authoring Tool Version: 0.4
  - Framework Version: 2.2.2
  - Operating System: Unix based server
  - Node version: 6.6.0

**Comment by simondate** [comment]
We've been looking at the developer tools network and it seems that when you navigate into a course from the dashboard lots of other courses seem to get loaded too.

**Comment by louisebennett** [comment]
https://imgur.com/8OgidG3

**Comment by louisebennett** [comment]
I did some further testing into this: 

On the Dashboard page, it first loads the json for each component/extension that is installed, and then each course in the (I assume) tenant. It also looks like a number of js files are being loaded in, including things like editors and plugin managers that (I'm guessing) shouldn't be there. 

When you're editing an individual course, it loads in the components and extensions again, and then config for individual components, articles and pages.

Needless to say, the more courses you have in your tenant, the longer the load times are (the screenshot above was taken while the page was still loading).

**Comment by simondate** [comment]
@taylortom @canstudios-louisem is there anything we can do to help with this? We really want to be able to use the features of 0.4 but it's not in a workable state atm.
