### ISSUE TITLE
Dashboard not paging correctly

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1759]
## Expected Behaviour

When you scroll down the page new courses are bought in.

## Actual Behaviour

Only the initial 32 courses loaded are shown.

## Versions
  - Authoring Tool Version: 0.4
  - Framework Version: 2.2.2

**Comment by johnniezen** [comment]
I got 32, 4 columns 8 rows, our FW is still 2.0.12, but AT is 0.4

**Comment by taylortom** [comment]
If you have time, please test the solution at https://github.com/adaptlearning/adapt_authoring/pull/1764
