### ISSUE TITLE
Editor preloading has emphasised performance issues with large installs

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1765]
As we now wait for the editor data to preloaded, we're seeing more obvious slow-down in 'large' installs (it's not entirely clear what categorises large: many courses, courses with a lot of content -- probably both). 

This needs to be investigated.

## Versions
  - Authoring Tool Version: 0.4.0

**Comment by canstudios-louisem** [comment]
Isnt this just a duplicate of #1758?
