### ISSUE TITLE
Cannot delete empty articles

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1770]
## Expected Behaviour
Removing an empty article (by clicking the trash icon) would remove the article if alert is confirmed.

## Actual Behaviour
Article is not removed. No console errors in browser or terminal. Delete using cog icon works.

## Steps to Reproduce
1. Create a new course
2. Add a new article that does not contain a component
3. Try to remove article using the trash icon.

## Versions
  - Authoring Tool Version: develop b ranch
  - Framework Version: v2.2.2
  - Operating System: MacOS 10.12.6
  - Browser: Chrome 62

**Comment by mike-st** [comment]
This seems to be a big issue also effecting various components... I can't remove items in matching or GMCQ/multiple choice question

**Comment by canstudios-louisem** [comment]
Hi @mike-st could you raise a seperate issue for that with some more info about your system and reproduction steps?

**Comment by mike-st** [comment]
Hi actually my issue is 1756. I will respond there thanks.
[https://github.com/adaptlearning/adapt_authoring/pull/1756](https://github.com/adaptlearning/adapt_authoring/pull/1756)
