### ISSUE TITLE
ability to collapse articles

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#1784]
## Affected Area
Editor interface 

## Requested Feature
When working with long pages that contain multiple pages, it would be nice to be able to collapse individual articles. 

## Use Case
Pages with Assessment, multiple ArticleReveal, ArticleBlockSlider

## Current Workaround
None

## Additional Information

**Comment by tomgreenfield** [comment]
Duplicate of #1483?

**Comment by lc-thomasberger** [comment]
yes @tomgreenfield
