### ISSUE TITLE
Will only load 32 Assets Max in 0.4.0 authoring tool

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#1790]
# Will only load 32 Assets Max in the Asset Management 

## Expected Behaviour
Should continue to load assets as you scroll down the page in Asset Management

## Actual Behaviour
Only loads 32 assets then you can't scroll any more.

## Steps to Reproduce
1. go to asset management and try to scroll

## Versions
  - Authoring Tool Version: 0.4.0
  - Framework Version: 2.2.2
  - Operating System: Win 10
  - Browser: Chrome 61

![only-loads-32-assests-max](https://user-images.githubusercontent.com/10455453/32801253-8b024ba2-c94a-11e7-8bb2-c0c69378685d.jpg)

**Comment by canstudios-louisem** [comment]
Related: #1759
