### ISSUE TITLE
Trickle extension - remove isEnabled by default on Block

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1803]
This line was added 4 months ago https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/properties.schema#L229

It means that if Trickle is added to a course that every single block in the course is Trickle locked by default. I don't think this is the standard way that people use Trickle (they usually use it sparingly in a course) and should therefore be set to false by default

**Comment by tomgreenfield** [comment]
Original issue: https://github.com/adaptlearning/adapt_framework/issues/1672.

**Comment by simondate** [comment]
Thanks for finding the issue @tomgreenfield . However I don't think that things like should be copied so literally from the Framework.

In the Framework you are given the option to just remove the extensions code. If the extensions code exists in a block then it is assumed the course builder wants to use the extension.

In the Authoring Tool the course builder is given no choice. They must have every single block so the default behaviour that exists for the FW makes less sense to me. I think we should be designing default settings so that they are the most time convenient for the course builder. If the average use of the extension means it is enabled on over >50% of blocks it should be enabled by default. If the reverse is true it should be disabled.

@danielstorey  I would love to hear your opinion on this. How have you found using this extension since changing it do your courses that have the Trickle extension use it on most of the blocks in the course.

**Comment by taylortom** [comment]
If I understand it, the problem here is a disagreement with the default value specified in the schema. If so, this isn't an authoring tool issue, and should be discussed in with the plugin maintainers (i.e. framework guys).

We have an issue for a more generic feature in the AT which you may want to +1: https://github.com/adaptlearning/adapt_authoring/issues/1505
