### ISSUE TITLE
scroll position in page editor

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#1814]
## Expected Behaviour
scroll position in page editor should be persistent 

## Actual Behaviour
When you edit an element in the page editor and return back, scrollTop is set to 0.

## Steps to Reproduce
1. create course
2. add enough components so that scrollbars appear
3. edit a component
4. return to page editor

## Versions
  - Authoring Tool Version: 0.4.0
  - Operating System: All
  - Browser: All

**Comment by canstudios-louisem** [comment]
Is this a regression from 0.3.0

**Comment by taylortom** [comment]
Not sure, it may have been broken before then.

**Comment by canstudios-louisem** [comment]
I'm just wondering if it needs to be in 0.4.1 if not can we hold it until 0.5.0 as 0.4.1 should have been out weeks ago?

**Comment by taylortom** [comment]
I was happy to let it in considering it was such a small change, but don't want it to delay things.
