### ISSUE TITLE
Missing feedback on hidden hotspots

### ISSUE THREAD

**Issue by RhGray** [adaptlearning/adapt_authoring#1816]
## Expected Behaviour 
Feedback to be shown when they click on the feedback button either after an error or at the end

## Actual Behaviour 
Clicking on the feedback button doesn't do anything. Only thing that happens is the mark made turns either to a green tick or a red cross

## Steps to Reproduce
1. select hidden hotspots
2. select area on picture to use as the hidden hotspot (only 1)
3. enter text into feedback
4. save
5. preview

## Versions
  - Authoring Tool Version: Adapt Builder
  - Framework Version:
  - Operating System: Windows 7 
  - Browser: Internet Explorer 11

**Comment by taylortom** [comment]
Hi @RhGray, you've got 'Adapt Builder' listed as the version - are you using Learning Pool's hosted app?

**Comment by RhGray** [comment]
I'm using the web based version that Learning Pool gave us access to if that helps? I'm fairly new to all of this

**Comment by taylortom** [comment]
Ah ok. That's a separate product to the open-source, so you're best contacting them directly. The hidden hotspots component is also proprietary to Learning Pool, so there's not much the open-source team can do I'm afraid.

**Comment by RhGray** [comment]
Thanks for your help

Rhiannon Gray
Development Specialist
Integrated Workforce Development Team
Strategy and Improvement
Children’s Integrated Services
Nottingham City Council
4th Floor Loxley House
Station Road
Nottingham
NG2 3NG



Email: rhiannon.gray@nottinghamcity.gov.uk<mailto:rhiannon.gray@nottinghamcity.gov.uk>
Tel: 0115 8764821

[cid:image001.png@01D37283.AF1B71D0]
