### ISSUE TITLE
Install script doesn't take into account all config.json values

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1828]
## Expected Behaviour
Script should use all values in `config.json`, removing the need to input these values again.

## Actual Behaviour
Script prompts the user for inputs from the `inputData.features` inputs onwards.

## Steps to Reproduce
1. Run through install script, choosing `y` when asked to use `config.json` values

## Versions
  - Authoring Tool Version: 0.4.0

**Comment by canstudios-louisem** [comment]
How important is this for 0.4.1 or can it be pushed back to 0.5?
