### ISSUE TITLE
Custom LESS should be validated prior to course build

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1830]
## Expected Behaviour
It would be nice if we could validate the custom LESS prior to building a course, and therefore give the user a useful error.

I don't think it makes sense to try and catch this during the course build process later on, as it'd need some modification of the framework's grunt process.

## Actual Behaviour
You're able to save the invalid LESS, and are then shown a generic error when you later try to build the course.

## Steps to Reproduce
1. Add invalid LESS to Project settings > Custom LESS
1. Save
1. Attempt to preview

**Comment by tomgreenfield** [comment]
Validation of Less before compilation into CSS isn't really feasible; [Ace](https://ace.c9.io/build/kitchen-sink.html) certainly doesn't offer it.

May be more productive if we have better logging of errors into SweetAlert, e.g. doing something with:
```shell
Fatal error: {
 "type": "Parse",
 "filename": "src\\theme\\57079b40794fc3a4029e30f2\\less\\zzzzz.less",
 "index": 11,
 "line": 1,
 "callLine": null,
 "column": 11,
 "extract": [
  null,
  "@fake-mixin;",
  null
 ],
 "message": "directive options not recognised"
}
```

**Comment by taylortom** [comment]
Look into if we can lint/validate using backbone-forms

**Comment by lc-thomasberger** [comment]
Validating before build is a bit tricky, as most less errors will depend on the selected theme. For instance, certain variables or mixins are not defined in the selected theme.

For error handling on build, a feature to skip the custom less would be nice in case it breaks a build.

**Comment by canstudios-scottd** [comment]
Verified on as passed on testing.
