### ISSUE TITLE
Component media preview/holder image is missing

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1835]
## Expected Behaviour
After selecting an asset in component editor a holding image or preview should be shown along with remove asset button. 

## Actual Behaviour
The image is missing e.g
<img width="273" alt="screen shot 2018-01-13 at 11 17 33" src="https://user-images.githubusercontent.com/6452430/34905901-4584d876-f85a-11e7-9b0e-ee81177ae910.png">

## Steps to Reproduce
1. Add any component which uses an asset.
2. Select any asset for the component

Same issue if FFMpeg is used or not. Reproduced in media and graphic component.

## Versions
  - Authoring Tool Version: tag/v0.4.1-rc.1
  - Framework Version: v2.2.3
  - Operating System: Mac OS 10.13.2
  - Browser: Chrome 63

**Comment by lc-thomasberger** [comment]
I can only replicate this with the media component and only for the video-type Asset fields. The thumbnail for the poster image renders fine.

**Comment by dancgray** [comment]
Sorry @lc-thomasberger you're right, it's only video asset fields.

**Comment by lc-thomasberger** [comment]
Cool, thanks Dan for confirming. 
I think it is just an issue with the url: `http://localhost:5000/api/asset/serve/5a26c8f714a840e1d0c2edea` instead of `http://localhost:5000/api/asset/thumb/5a26c8f714a840e1d0c2edea`
