### ISSUE TITLE
Deleting submenu leaves orphaned view and courseassets

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1837]
## Expected Behaviour
In the menu editor deleting a submenu that contains pages should delete all articles, block, components and courseasset records for those pages. The menu editor view should also render correctly.

## Actual Behaviour
Records for contentObject, article, block and component are removed. However courseasset records for components containing media assets are not removed, leaving orphaned records.

Also the menu editor display is not correct:
![screen shot 2018-01-15 at 09 39 02](https://user-images.githubusercontent.com/6452430/34938809-851d219a-f9e1-11e7-998b-6bc251618352.png)

## Steps to Reproduce
1. Create a course with a submenu
2. Add a page to that submenu that contains a media/graphic component with corresponding asset selected.
3. Delete the submenu using either the trash button or cog/delete.

## Versions
  - Authoring Tool Version: tag/v0.4.1-rc.1
  - Framework Version: v2.2.3
  - Operating System: Mac OS 10.13.2
  - Browser: Chrome 63

**Comment by dancgray** [comment]
Deleting the submenu (trash button or cog/delete) gives client side console error:

Uncaught TypeError: Cannot read property 'get' of undefined editorMenuView.js:136

**Comment by lc-thomasberger** [comment]
Also the selected state is a bit buggy

**Comment by lc-thomasberger** [comment]
Looks like the orphaned courseassets was already an issue with previous versions. The collection is cleaned up once you delete the course.
I would focus on the view rendering and keep the courseassets cleanup once you remove a contentobject for later, as I think this should be handled in the backend?

**Comment by dancgray** [comment]
I have created a seperate issue for orphaned courseassets.  #1843
