### ISSUE TITLE
Install does not populate config.json with all user input values  

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1842]
## Expected Behaviour
When installing the user entered values for:
useffmpeg
smtpConnectionUrl - SMTP server
smtpService - SMTP service 
smtpUsername - SMTP username
smtpPassword - SMTP password
fromAddress - Sender email address
rootUrl - The url this install will be accessible from 

Should be saved to /conf/config.json.

## Actual Behaviour
These values are missing from config.json. Also the master tenant display name is populated with the master tenant name value in mongo tenants.

## Steps to Reproduce
1. create a clean install of the authoring tool entering values for all options

## Versions
  - Authoring Tool Version: tag/v0.4.1-rc.1
  - Framework Version: v2.2.3
  - Operating System: Mac OS 10.13.2
  - Browser: Chrome 63

**Comment by dancgray** [comment]
Also see https://github.com/adaptlearning/adapt_authoring/issues/1828

**Comment by taylortom** [comment]
Fixed in #1829
