### ISSUE TITLE
Prompt module in install script should accept boolean values

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1850]
## Requested Feature
Prompt by default accepts y/n as the input for boolean values. We ideally need to also allow true/false so that an existing config.json can be used without any pre-processing hacks (see below).

## Current Workaround
https://github.com/adaptlearning/adapt_authoring/pull/1829/commits/326d641b027252e56ba0af836c557d490ca9ab9a#diff-f16acefe4b6553580c43edab685f50f3R234

**Comment by taylortom** [comment]
I can't see a nice workaround for this. The prompt module is set up to either accept strings or booleans. Mixing these causes issues when it comes to applying overrides (which we do via the existing config.json).

Possible options: 
- Leave as is with the string replacement
- Switch to using true/false input instead on 'y/n'

**Comment by canstudios-louisem** [comment]
I've run into some issue with the prompt module as well. In 0.4.1 we broke CLI input but even if I fix it if pass data via CLI arguments it doesn't go through the before function.

It also seems to be a dead project no releases for over a year and no responses on the issues I would be all for moving to something else or taking the prompt module (its just one small file) and bringing it into the code base and fixing our issues in it.

**Comment by taylortom** [comment]
Thanks Louise!

Does anyone have any preference as to whether we switch to something better supported (perhaps [Inquirer.js](https://github.com/SBoudrias/Inquirer.js)) or include the prompt code in core?

**Comment by canstudios-louisem** [comment]
I prefer to use NPM modules if we can as some else has done the work for you but whichever is easier really.

**Comment by taylortom** [comment]
Cool, if we do go with that, I say let's push this to the next release, as is quite a big new change.

**Comment by lc-thomasberger** [comment]
I would also suggest to use a already available packe instead of fixing / hacking a custom one. Inquirer looks beautiful.

**Comment by taylortom** [comment]
Replaced with #1908
