### ISSUE TITLE
pluginDependencies in plugin bower files should work

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#1858]
## Affected Area
It should be possible to add a `pluginDependencies` object to the bower.json of any plugin and have the plugins listed in it pulled into the build. Eg. The hotgraphic component should be able to ensure the narrative component gets included by listing it in its pluginDependencies.

## Requested Feature
At the moment the pluginDependencies are ignored by the authoring tool. Instead in the outputmanager.js file there is a hardcoded hack which adds the narrative component if the hotgraphic is present, and adds the mcq if the gmcq component is present.

## Use Case
New plugins with dependencies can be developed.

## Additional Information
The hack was added in these PRs:
https://github.com/adaptlearning/adapt_authoring/issues/1033
https://github.com/adaptlearning/adapt_authoring/issues/1038

**Comment by tomgreenfield** [comment]
Related: https://github.com/adaptlearning/adapt_authoring/issues/1179#issuecomment-219396729.

**Comment by canstudios-nicolaw** [comment]
I'm aware this could be a temporary/partial solution, but it feels better than leaving the hack in place. I think it could be a while before any changes are made which would make this completely irrelevant. And in the meantime this would fix pluginDependencies for everyone.

I'm not proposing a big change, we are just testing the changes at Can but we have replaced the hack with some code that looks into the bower.json files of included plugins and adds their pluginDependencies to the list of included plugins.

If anyone has any thoughts please let me know.

Thanks

**Comment by taylortom** [comment]
Agree that it’s not ideal. 

We haven’t done anything on this before as we’ve never really had a solid solution for framework dependencies. @oliverfoster is looking at this in the near future, so may have recommendations?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oliverfoster** [comment]
v4 of adapt should provide a solid solution for this, by using bower properly. then we can revert from pluginDependencies to dependencies in the bower.json
After that we'll want to drop bower and move over to package.json and npm etc...
