### ISSUE TITLE
Remove requirement for users to install ffmpeg manually

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1860]
Moving comments on #850 to a separate issue

@lc-thomasberger:

> I would recommend to always show an image for assets as it is very tedious to work with assets that have no thumbnail. If there is no thumbnail generated, I would fallback to the original image and use this.
>
> also recommend that for simple thumbnail creation from uploaded images we should not only depend on ffmpeg as it requires the user to manually install ffmpeg.
> There are quite some nice npm packages available that could be used under the hood and installed with npm during setup.
>
> https://www.npmjs.com/package/jimp
> https://www.npmjs.com/package/sharp

**Comment by lc-thomasberger** [comment]
We might actually handle thumbnail creation entirely on the client with canvas. This would reduce cost on the server and remove an extra dependency on the backend.
Animated gif's for previewing videos can be a limitation though. I would recommend building a collage of sample images instead of creating an animated gif. There are libraries that encode gif's on the client though:
https://github.com/jnordberg/gif.js
https://github.com/yahoo/gifshot

**Comment by canstudios-louisem** [comment]
I have quite recently done some client-side resizing of images [pica](https://github.com/nodeca/pica) and canvas and was not massively impressed by the quality you get. There are better algorithms for doing it serverside.

**Comment by lc-thomasberger** [comment]
That's true, canvas can produce terrible images. Not sure if high-quality thumbnails is our number one concern regarding thumbnail images.

When we stick with server-side image processing we need a package that's easy to install on all platforms. I had troubles installing Sharp on my Windows-Machine, so others will have too and that is bad. So I assume the only real option we have is jimp as it is a plain JS implementation. It is however not the fastest.

**Comment by canstudios-louisem** [comment]
We don't have bulk upload, and it's a one-off task so I would not worry about performance too much obviously if its taking minutes per image then we may have to think about it more.

**Comment by lc-thomasberger** [comment]
Bulk upload will be a future feature of Assetmanager update.

Without ffmpeg, how do you think we should handle video preview generation? The beauty about a browser implementation is that we can handle video and canvas directly.

**Comment by canstudios-louisem** [comment]
What if we still kept FFmpeg but implement jimp as a fallback for images and possibly canvas for video? rather than just not generating anything

Do you know how performant canvas would be for low-end pc's or tablets, especially if they start to upload video's?

As for serverside performance, we currently do the thumbnail generation as part of the upload process before the server responds to the user. There is no reason we couldn't fire that off as a separate process rather than waiting for it to finish right away. That would also help make bulk upload faster for whatever implementation we went used.

**Comment by lc-thomasberger** [comment]
That's exactly the approach I was thinking. To me it does not make sense to use ffmpeg for Image thumbnail generation and do nothing at all if it is not available. 
We should use Jimp for images without any further configuration- This will improve UX for users and will make installing a bit more leaner. If you need video preview you will need to install ffmpeg, which is fine if you are on a production environment.

Regarding Canvas speed, not sure, but I think it won't be an issue. We could use a Webworker to process the files in the background and send them to the Sever once they are generated.

We should keep client side process in the pipeline at least for the AssetManager-rewrite.

**Comment by canstudios-paulh** [comment]
FWIW import can cause bulk upload of assets.
