### ISSUE TITLE
Adding front end plugins requires editing the app.js

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1866]
## Expected Behaviour
Adding a plugin to the `frontend/plugins` folder should just work as `plugins.js` file can be built and used to require the plugin into the tool

## Actual Behaviour
The `plugins.js` is ignored and you need to edit the `core/app.js` [here](https://github.com/adaptlearning/adapt_authoring/blob/dc04351192d62c6e6f6520e33eee1478a01d672d/frontend/src/core/app.js#L48) 

## Versions
  - Authoring Tool Version: 0.4.1

**Comment by lc-thomasberger** [comment]
This will probably require some changes to scriptloadig and maybe also a grunt task.
I think it is best to move to Webpack in the future and remove requirejs and grunt. Therefore I think we should not invest to much time in this issue and fix it when we change the build process.

Switching to Webpack gives us way more options. Codesplitting and easier bable integraiton for ES2015 and support for Preact / Vue.js.
