### ISSUE TITLE
HACK | TODO | FIXME

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1867]
The whole authoring tool is riddled with these as comments most of them don't have related issues, so they are not being tracked. 

Some of them are minor, should be removed and have an issue raised for them. Others are somewhat more serious and need to be looked at.

It does concern me that some have "sneaked in" quite recently and no one thought to raise them when writing them, creating the pr that pushed them or reviewing the PR. I think people need to stop and think if they write a `//HACK` or `//FIXME` in the code base "should I be fixing this" or "has the code I've written that creates this issue put the code base in a better state than when I left it.

I suggest we start by listing these out and looking first at the `//HACK` then `//FIXME` and '//TODO` comments. Along with checking all PR's more thoroughly for these especially the big pr's I'm sure that's how most have got in and I know I've reviewed those so I must have missed them as well.

**Comment by taylortom** [comment]
It might also be useful to write a CI process that we can run to fail if any of these are found

**Comment by canstudios-louisem** [comment]
I had a look if someone else had one and couldn't find one but yes it would be a good idea.

**Comment by taylortom** [comment]
Have submitted a PR with a potential addition to the automated tests

**Comment by lc-thomasberger** [comment]
I think we can address some /most of the backend issues during the backend refactor Milestone.

Building on top of @taylortom Frontend restructure I think we should have another go and update the Frontend to leverage preact + redux or vue + vuex and use webpack for the build. I think with the current Frontend it is extremely hard to add new features and provide an app like user experience. 

Also, the Frontend sometimes behaves to Adapt focused. For instance the Page editor can only render the current Framework structure (ABC). If we plan to update the Framework to be more modular and flexible (Version 4), the AuthoringTool will fail.
