### ISSUE TITLE
Tenant courses always build in the master tenant temp folder

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1877]
## Expected Behaviour
The preview should use the adapt_framework folder within the temp/[tenant Id] folder. 

Also see this [issue](https://github.com/adaptlearning/adapt_authoring/issues/1757)

## Actual Behaviour
The master tenant temp folder is always used due to master tenant Id being hard coded in this [line](https://github.com/adaptlearning/adapt_authoring/blob/tenant-management/lib/application.js#L406)

## Steps to Reproduce
1. Use tenant-management branch
2. Add a new tenant and add a user for that tenant
3. Log in at that tenant user and create and preview a course.
4. Preview builds in master tenant temp folder. Log output as follow:

info: [16 Feb 2018 10:59:29 +00:00] Event:rebuildCourse triggered for Tenant: [new tenant Id] Course: [correct course Id]
info: [16 Feb 2018 10:59:29 +00:00] Writing build to /source/adapt/adapt_authoring/temp/[master tenant Id]/adapt_framework/courses/[new tenant Id]/[correct course Id]/build/.rebuild

## Versions
  - Authoring Tool Version: tenant-management branch
  - Framework Version: v2.2.5
  - Operating System: macOS 10.12.6
  - Browser: Chrome 64

**Comment by lc-thomasberger** [comment]
[Here](https://github.com/adaptlearning/adapt_authoring/blob/tenant-management/lib/tenantmanager.js#L241) should be a return before calling the callback. The tenantmanager allways create a tenant-filesystem even though it is not a master tenant.
