### ISSUE TITLE
Install should not fail if a plugins framework requirement does not match the framework installed

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1890]
## Expected Behaviour
Installing the AT should not fail if one of the plugins installed from adapt install is not compatible with the framework version installed.

It should just not install the plugin and log an error.

## Actual Behaviour
AT install fails with the following error.
```
ERROR: Unable to install adapt-contrib-spoor (undefined) as it is not supported in the current version of the Adapt framework (2.2.5)

Failed to create master tenant. Please check the console output.
```
Spoor v2.1.4 version number matches the adapt.json version defined in adapt.json in FW v2.2.5 but the [required Framework version](https://github.com/adaptlearning/adapt-contrib-spoor/blob/v2.1.4/bower.json#L4) defined in spoor bower.json is FWv3

## Steps to Reproduce
1. Download AT v0.4.1 and install using a framework tag/branch (v2.2.5) that installs a plugin (spoor v2.1.4)

## Versions
  - Authoring Tool Version: v0.4.1
  - Framework Version: v2.2.5

**Comment by taylortom** [comment]
Not sure of the best solution here, as we should really be able to rely on the values in the adapt.json and package.json files. If we try to add some defensive code for this, the question becomes which values should we trust. 

At the very least, we should probably give a slightly more relevant error message.

**Comment by lc-thomasberger** [comment]
If the latest version of the plugin is not compatible with the FW, the AT should try to find a plugin that matches the FW version. If there is no compatible version, it should log an error and proceed. We might also prompt the user to enter a compatible version tag.

**Comment by canstudios-louisem** [comment]
Ive added this to the milestone feel free to remove it if you want to defer it. Just don't want it to be forgotten.
