### ISSUE TITLE
Ability to re-order array's

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1895]
## Affected Area
Course editor

## Requested Feature
The ability to reorder array's 

## Current Workaround
Delete the content and re-enter it.

**Comment by taylortom** [comment]
Think this is a duplicate of #1430 :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by canstudios-louisem** [comment]
I thought we had one somewhere but couldn't find it :+1:
