### ISSUE TITLE
HTML Escaping

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_authoring#1899]
# BUG Template

## Expected Behaviour
HTML created in the editor should come out as fully formed html

## Actual Behaviour
HTML is escaped in most situations

## Steps to Reproduce
1. Add `<div class="stylish">This is a div</div>` to editor
1. Appears as `&lt;div class=&quot;stylish&quot;&gt;This is a div&lt;/div&gt;` in the JSON

## Versions
  - Authoring Tool Version: All
  - Framework Version: All
  - Operating System: All
  - Browser: All

## References
- [(Cross_Site_Scripting)_Prevention_Cheat_Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.236_-_Sanitize_HTML_Markup_with_a_Library_Designed_for_the_Job)
 - [HtmlSanitizer](https://github.com/mganss/HtmlSanitizer)
 - [Bleach](https://github.com/ecto/bleach)

**Comment by tomgreenfield** [comment]
Fixed in https://github.com/adaptlearning/adapt_authoring/pull/1924.
