### ISSUE TITLE
New version of extension (Component, Theme) should be updated in existing course autoamtically 

### ISSUE THREAD

**Issue by derhuebiii** [adaptlearning/adapt_authoring#1905]
When I upload a new version of a template/component I need to re-insert the component or re-select the theme so that it gets applied to my course.

## Expected Behaviour
After uploading and updating this should be applied automatically to my components. Otherwise I have to rebuilt all components or re-assign the template to each course.

## Actual Behaviour
No change to existing course.

## Steps to Reproduce
1. Upload an extension
2. Use it
3. Upload a new version of the extension
4. No update in existing course

**Comment by lc-thomasberger** [comment]
For new themes to be applied in a course you can toggle the value for "create sourcemaps". This will force a rebuild of the course. This should solve your issue for now.

In the long run, I think we should have a force build option next to the preview button. E.g. something like bootraps droddown button: 
![image](https://user-images.githubusercontent.com/11990374/37159954-61ed62d4-22ef-11e8-892c-3cb21d48b379.png)

**Comment by derhuebiii** [comment]
Thanks! Sounds like a good idea with the dropdown as it's not clear (not knowing the code) when and what really is re-built when pressing the preview button.
