### ISSUE TITLE
i is not a constructor

### ISSUE THREAD

**Issue by derhuebiii** [adaptlearning/adapt_authoring#1918]
# BUG Template

## Expected Behaviour
After installing the topNavigator extension and activating it, I cannot go to project settings.

## Actual Behaviour
Error "i is not a constructor"

## Steps to Reproduce
1. install extension topNavigator
2. activate in course
3. go to project settings
![image](https://user-images.githubusercontent.com/22290552/37419702-5a4196a2-27b5-11e8-852b-d2c35ac1160a.png)

## Versions
  - Authoring Tool Version: latest on github (master branch)
  - Framework Version:
  - Operating System:
  - Browser:

# Feature Request Template

## Additional Information

**Comment by canstudios-louisem** [comment]
Any issues with plugins need to raised with the plugin author in this case [here](https://github.com/NayanKhedkar/adapt-topNavigator).
