### ISSUE TITLE
Update archive NPM package

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1930]
The archive dependency is massively out of date we should update it.

**Comment by canstudios-louisem** [comment]
Download also seems to be brokend

**Comment by canstudios-louisem** [comment]
This is a regression from 0.4.1

**Comment by tomgreenfield** [comment]
Hi @canstudios-louisem, I'm struggling to replicate this – is there anything I'm missing?

Environment in case you're wondering is:
* Chrome 65 on Windows 10
* Node v6.11.5
* `develop` commit 2656cf2771bcfd942d2787c1d55a41c065a6a1bc

**Comment by canstudios-louisem** [comment]
I should probably update this issue I think it was caused by an npm package that had been updated when it shouldn't have.

Its less critical than when i first thought but we should probably update that dependency anyway as its soooooooooooo old.
