### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1937]
## Affected Area
Upgrade

## Requested Feature
The ability to write scripts that will run on upgrade.

## Use Case
This will allow us to make changes to the DB structure and folder structure of the app without breaking existing installs.

## Current Workaround
None

## Additional Information
It would be useful to get this into the next version even if there are no migrations as it will mean we can use in the version after.

**Comment by canstudios-louisem** [comment]
Custom wrote new tracked files. I have it basically done just reviewing it internally and then I can show you. I think the PR will explain a bit more what I mean.

**Comment by taylortom** [comment]
👍

**Comment by canstudios-louisem** [comment]
This is also the first step for #1752
