### ISSUE TITLE
Framework 3

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1939]
## Affected Area
Framework

## Requested Feature
Framework 3.0.0 is out we need to support it

## Current Workaround
None

**Comment by tomgreenfield** [comment]
- [ ] Migrate completion criteria into Spoor ([reference](https://github.com/adaptlearning/adapt_framework/commit/5321a31efa873e6f36de4ecaacde070713ee3e47))
- [ ] Duplicate plugin-specific instruction text into core instruction text ([reference](https://github.com/adaptlearning/adapt_authoring/pull/1714#issue-138174487))

**Comment by taylortom** [comment]
No longer relevant
