### ISSUE TITLE
Expose authoring tool version in the HTML

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1944]
Would be nice to easily check the version of an authoring tool from the HTML. This could also be exposed via the JS and the config module, but it seems more useful for debugging to be able to check this without needing JS.

This could also be used to apply custom version-specific features/styling (not suggesting we do this in core, but can imagine it would be useful for custom work).

**Comment by tomgreenfield** [comment]
If you do want to expose this in the DOM, strongly suggest a `data-authoring-tool-version` attribute or similar, and place it as high up as possible, i.e. on `<html>`.

**Comment by taylortom** [comment]
+1 to data- attribute

**Comment by trueschool** [comment]
![I Like!](https://media.giphy.com/media/3o6ZtpvPW6fqxkE1xu/giphy.gif)
