### ISSUE TITLE
Remove unused user roles

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1950]
It seems pointless (and not to mention confusing to users) that we include role types that don't offer any difference in features. As any kind of proper role support isn't anywhere on the horizon, I vote we remove these. We might need to write a migration to remove old roles from the DB, and any assigned to existing users.

Roles affected:
- Tenant admin
- Product manager
- Authenticated user

**Comment by taylortom** [comment]
It's been agreed that this will come naturally as part of the server rewrite.

**Comment by canstudios-nicolaw** [comment]
As discussed in the stand up yesterday, I'm going to look at getting rid of Product Manager and Tenant Admin roles and writing a migration to convert any existing users of these types to Course Creators.
