### ISSUE TITLE
Tags input character limit

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#1952]
Adding a tag that's longer than the [imposed limit](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/modules/scaffold/views/scaffoldTagsView.js#L48) (30 chars) seems to break the editor. I don't have a particular issue with limiting the characters, but don't think it should break if the limit's exceeded. 

I vote we just remove this limit, as not sure why we'd want to limit it? If we opt to do this, we'll also need to look into the styling around the text box width, as this should probably be increased to accommodate longer tags.

![screen shot 2018-05-01 at 15 31 19](https://user-images.githubusercontent.com/1059083/39476714-db9be86e-4d54-11e8-9e29-8f73e6af4a74.png)

**Comment by tomgreenfield** [comment]
Please note that this editor now uses Selectize in the refactor branch.

**Comment by taylortom** [comment]
No loger applicable
