### ISSUE TITLE
Accessibility Button not activating on windows 10 touch screen

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#1957]
# BUG Template
Accessibility Button not activating on windows 10 touch screen

## Expected Behaviour
Press tab on preview of course should turn accessibility mode on and does on all computers except touch screen ones.

## Actual Behaviour
Nothing happens?

## Steps to Reproduce
1. Set Accessibility on and text reader support on
2. preview course
3. Press tab to turn accessibility on

## Versions
  - Authoring Tool Version: 0.4.1
  - Framework Version: 2.2.5
  - Operating System: Windows 10
  - Browser: Chrome & Firefox

**Comment by mike-st** [comment]
I should note weirdly Accessibility works fine in IE11 and Edge on Windows 10 touch screen computers

**Comment by oliverfoster** [comment]
This issue was moved to adaptlearning/adapt_framework#2066
