### ISSUE TITLE
Page level progress and assessment extensions conflict

### ISSUE THREAD

**Issue by zanis-timsans** [adaptlearning/adapt_authoring#1960]
# BUG Template
Page level progress indicator is incorrect when assessment extension is enabled
## Expected Behaviour
Page level progress indicator should display appropriate percentage of completed components and pages
## Actual Behaviour
When assessments extension is activated the page level progress doesn't show progress at all in main menu (the indicator stays at 0% for submenu and for pages menu it is either 0% or 100% - doesn't show the actual progress) and inside the page where there are 3 blocks with 1 component per each, progressindicator at the top divides it like there would be 4 components - 25% instead of 33%. This issue is gone when assessments extension is disabled. 
## Steps to Reproduce
1. Make a submenu with page level progress enabled 
2. Inside submenu make a page with page level progress enabled
3. Inside page make at least 2 components with assessment and page level progress enabled
4. In preview try completing assessment and keep an eye on progress in diferent views (submenu, menu, and inside the page)

## Versions
Authoring Tool Version: 0.4.1
Framework Version: 2.2.5
Operating System: Windows 10
Browser: Chrome & Firefox

**Comment by oliverfoster** [comment]
This issue was moved to adaptlearning/adapt_framework#2065
