### ISSUE TITLE
When we drag the CO from one position to other and the _sortOrder is not changing in the DB

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_authoring#1964]
# BUG Template: Superb template. Made it easy to explain it. 👍 

## Expected Behaviour
When we drag the CO from one position to other and change the _sortOrder should change automatically in DB for all the COs present in that course.

## Actual Behaviour
_sortOrder is not updated

## Steps to Reproduce
1. Create 3 content objects with complete ABC structure in them atleast one in each
2. Drag the third CO in middle
3. Preview the course / Refresh the AT page
4. The CO moves back to the third position

## Versions
  - Authoring Tool Version: 0.4.1
  - Framework Version: 3.0.0
  - Operating System: MacOS/Windows 10
  - Browser: Chrome

**Comment by taylortom** [comment]
I'm not able to replicate this bug using the latest develop branch code

**Comment by aniketdharia** [comment]
@taylortom ok will do a check in develop tonight if it is done we can close it. Thanks!

**Comment by ambadasavhad** [comment]
@aniketdharia , @taylortom I'm too not able to replicate this using the latest develop branch code.
