### ISSUE TITLE
Feedback Title in Multiple Choice Question not overrriding

### ISSUE THREAD

**Issue by macjules** [adaptlearning/adapt_authoring#1967]
I add a Multiple Choice Question. I create a Component title but I want the answer feedback title to be different. I add a different Feedback Title and save. When I view the preview and the feedback the Feedback Title is still the same as the Component title.

## Expected Behaviour
Feedback Title should replace the Component title.
## Actual Behaviour
Feedback Title does not replace the Component title.
## Steps to Reproduce
1.Add a Multiple Choice Question.
2.Create a Component title 
3.Add a different Feedback Title 

## Versions
  - Authoring Tool Version: v0.4.1
  - Framework Version: (node) v6.13.1
  - Operating System: MacOSX
  - Browser: Firefox, Chrome, Safari

![screen shot 2018-05-18 at 11 27 28](https://user-images.githubusercontent.com/1309781/40230629-198b6bb6-5a90-11e8-9a76-7f3104bac0ba.png)

**Comment by tomgreenfield** [comment]
Hi @macjules, you haven't specified your Adapt framework version but I assume it's 2.x. The custom feedback title functionality requires framework version 3 under the hood.

**Comment by macjules** [comment]
@tomgreenfield  Many thanks. Can we update the Readme to this effect?
