### ISSUE TITLE
export source fails

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#1974]
# BUG 

## Expected Behaviour
Export source should export the source code of the course.

## Actual Behaviour
It fails with Error "Failed to determine user's tenant!"

## Steps to Reproduce
1. create course
2. export source code 

## Versions
  - Authoring Tool Version: v5-rc1
  - Framework Version: 2.2.5
  - Operating System: Windows
  - Browser: Chrome / FF

**Comment by tomgreenfield** [comment]
Had a test and I cannot replicate this one in my environment. Created a course without changing anything and it exported fine. I'm using Node v8.11.2 on Windows 10.

Anything I'm missing?

**Comment by lc-thomasberger** [comment]
Unfortunately I did not test with Node v8.x.x. With node I can't replicate this error either.
