### ISSUE TITLE
Gruntfile: `authSource` should be `dbAuthSource `

### ISSUE THREAD

**Issue by LoicMahieu** [adaptlearning/adapt_authoring#1977]
In Gruntfile, the task [`migration-conf`](https://github.com/adaptlearning/adapt_authoring/blob/develop/Gruntfile.js#L256) refers to `config.authSource` but it should be `config.dbAuthSource` as the [database](https://github.com/adaptlearning/adapt_authoring/blob/develop/lib/dml/mongoose/index.js#L90) use that key.

Fixed in #1970

**Comment by canstudios-nicolaw** [comment]
This issue was brought forward to the 0.7.0 milestone because it was merged into develop rather than 0.6.1 previously. Need to merge into the release branch for 0.7.0
