### ISSUE TITLE
Database config: unable to specify query options

### ISSUE THREAD

**Issue by LoicMahieu** [adaptlearning/adapt_authoring#1978]
We would like to use MongoDB Atlas as mongodb backend. There are some issues with it:

- Use `SSL` as transport layer. So `ssl=true` should be passed as querystring of the connection string.
- Use of replica set. Currently, the config `dbReplicaset` is supported but Atlas also needs a `replicaSet=<shard>` in the querystring. (I don't know if it is stricly necessary).

The service recommends these kind of URI:
```
mongodb://<USER>:<PASSWORD>@project-name-shard-00-00-yw72i.mongodb.net:27017,project-name-shard-00-01-yw72i.mongodb.net:27017,project-name-shard-00-02-yw72i.mongodb.net:27017/test?ssl=true&replicaSet=project-name-shard-0&authSource=admin&retryWrites=true
```

There is already a few config about the database:
- `config.dbUser`
- `config.dbPass`
- `config.dbReplicaset`
- `config.dbName`
- `config.dbPort`
- `config.dbHost`

IMO there is 2 possibilities:

1. Add new config `dbQueryString` for being able to specify the querystring which will be appended to the connection string.
2. Add new config `dbConnectionUri` for being able to specify the whole connection string manually. Since `adapt_authoring` could use different database in runtime, we will have to parse the connection string for change the db name at runtime.

**Comment by dancgray** [comment]
I guess the question is what connection use cases do we want to support?

Most installs use a local MongoDB instance and I think this should be the default setup, with the install script defaulting to this unless the user is prompted (early) to go down a different path. However we should be accommodating more advanced setups such as MongoDB Atlas which I would also like to use. As this is for advanced users and there are quite a few ways to format this URI and lots of options the easiest way is via your dbConnectionUri.

So I'm in favor of your option 2 dbConnectionUri.  So install would have an option after the prompt for dbName, "Advanced database connection options Y/n (N)":

Default of N prompts for:
dbHost: Database host (localhost)
dbPort: Database server port (27017)
dbUser: Database server user
dbPass: Database server password
dbAuthSource: Database server authentication database (admin)  

Selecting Y prompts for:
dbConnectionUri: Optional database connection URI 
dbOptions: Database connection options (_the options part of createConnection(connectionString, options)_)

This would give advanced users full access to the connection URI and options. dbReplicaset becomes redundant.

**Comment by dancgray** [comment]
If I have retryWrites=true in the query string I get a lot of `UnhandledPromiseRejectionWarning: Error: cyclic dependency detected` issues. Could be mongoose [issue](https://github.com/Automattic/mongoose/issues/6109).

There is also the DNS seedlist format that can be used to connect to MongoDB Altas, the +srv modifier should automatically set ssl to true, e.g: mongodb+srv://username:password@testcluster.mongodb.net/dbname

This also has the retryWrites problem. Plus the new migration functions use an NPM module that does not support this format, shame as it's much simpler :(

**Comment by dancgray** [comment]
@LoicMahieu thanks for the contribution. Closing this issue as the change has been [added](https://github.com/adaptlearning/adapt_authoring/pull/2015) in v0.6.1.
