### ISSUE TITLE
Importing a course with new plugins fails

### ISSUE THREAD

**Issue by harlows** [adaptlearning/adapt_authoring#1982]
# BUG

## Expected Behaviour
Import a course with new plugins. New plugins should be installed in the authoring tool and should be enabled for the imported course. Corresponding plugin attributes should be present for the imported course.

## Actual Behaviour
Error is generated and the course is not imported although the new plugin is added to the AT plugin list.

## Steps to Reproduce
Import a course with new plugins (tested separately with [adapt-expose](https://github.com/danielstorey/adapt-expose) and [adapt-hotgrid](https://github.com/cgkineo/adapt-hotgrid) components).

## Versions
  - Authoring Tool Version: v0.5.0-rc.1
  - Framework Version: v2.2.5

## Current Workaround
1. Manually upload the new plugin to ../adapt_authoring/temp/[tenant_id]/adapt_framework/src/components/
2. Re-import course
3. Preview course

## Additional Information
Terminal shows:
/home/ubuntu/workspace/adapt_authoring/plugins/content/bower/index.js:589
                : currentUser.tenant._id.toString()
                                    ^

TypeError: Cannot read property '_id' of undefined
    at /home/ubuntu/workspace/adapt_authoring/plugins/content/bower/index.js:589:37
    at copyDirItems (/home/ubuntu/workspace/adapt_authoring/node_modules/fs-extra/lib/copy/copy.js:170:21)
    at err (/home/ubuntu/workspace/adapt_authoring/node_modules/fs-extra/lib/copy/copy.js:181:14)
    at fs.chmod.err (/home/ubuntu/workspace/adapt_authoring/node_modules/fs-extra/lib/copy/copy.js:122:12)
    at /home/ubuntu/workspace/adapt_authoring/node_modules/graceful-fs/polyfills.js:239:18
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by louisebennett** [comment]
I had the same issue. I then attempted to import the course again, and it did import, but the plugins themselves did not, leading to a long list of errors when I attempted to preview: 

error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/theme/adapt-theme-publicHealth/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-article-background/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-close/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-contents/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-detailed-feedback/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-goTop/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-google-analytics/bower.json'
error: [06 Jun 2018 09:29:51 +01:00] Error: ENOENT: no such file or directory, open '/kcl_adapt/adapt_authoring/temp/59f08714bcc8a21e0388ed7b/adapt_framework/src/extensions/adapt-hideNavigation/bower.json'

**Comment by dancgray** [comment]
@harlows, I only get this error if I'm using a version of node lower than v8. 

This authoring tool release needs node v8.x or later. Please see the [changelog](https://github.com/adaptlearning/adapt_authoring/blob/issue/1902/CHANGELOG.md). Apologies if this was not clear.

**Comment by harlows** [comment]
@dancgray Thanks, it was clear, but my use of nvm not so good. Changed to node v8.4 and all is well with the world. Sorry for the false issue.
