### ISSUE TITLE
import can create orphaned elements 

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#1986]
# BUG 

## Expected Behaviour
Import should only accept valid courses.

## Actual Behaviour
When id's can't be mapped, the element is still imported.
This may result in elements being not removed when there course is deleted.

## Steps to Reproduce
1. import a course with orphaned elements
2. search for "Cannot update 5a6aff09b382e6db06bd8c68._parentId, 5a6afeeeb382e6db06bd8c67 not found in idMap"
3. Delete the course, the orphaned element should still be stored in the database.

## Versions
  - Authoring Tool Version: v0.5.0-rc1
  - Framework Version: --
  - Operating System: --
  - Browser: --

**Comment by lc-thomasberger** [comment]
Is this something we should address in the import or must course authors make sure that they only import valid courses?

If an elements id's can't be mapped, it should not be imported an the import script should warn the users that there was an issue. It may proceed with the import though.

**Comment by canstudios-louisem** [comment]
I think if IDs cant be mapped import should stop, clean up and then pass a message to the user saying what ID could not be mapped.
