### ISSUE TITLE
Session secret should be auto-generated

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#2007]
# Feature 

## Affected Area
https://github.com/adaptlearning/adapt_authoring/blob/master/conf/config-sample.json#L5
install script
https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback

## Requested Feature
Instead of setting a (weak) default session secret, we should auto generate a secure random default session secret string when the install script is executed.
A user defined session secret string may be passed as cli argument or configuration option.

## Current Workaround
Users must type a secure sessions secret string whenever the install script is executed.

## Additional Information
Should we always use a auto generated session secret? 
Is it only used to encode sessions?

**Comment by tomgreenfield** [comment]
> Should we always use a auto generated session secret?

This sounds useful.

**Comment by lc-thomasberger** [comment]
@tomgreenfield it would make things easier than adding another cli-argument and handling it.

What do others think? I think auto generated session strings should be fine.

**Comment by taylortom** [comment]
Just added a similar comment to the PR :)
https://github.com/adaptlearning/adapt_authoring/pull/2049#issuecomment-413137592
