### ISSUE TITLE
Copy / Paste or Move Blocks and / or Components from one Page to another

### ISSUE THREAD

**Issue by SpacegoatHQ** [adaptlearning/adapt_authoring#2009]
In a recent Adapt Authoring Tool project I had to re-structure a complete course already built (by someone else). I had to move Blocks / Components from one Page to another. I realised these elements can only be moved within the same Page, but currently there's no functionality to move them across Pages.
I ended up recreating these Blocks and Components in their new location (Page) and delete them from the old location. This is quite time-consuming and ineffective.

**Comment by taylortom** [comment]
Have reworded #622 to encompass this
