### ISSUE TITLE
Change your own email via the profile view 

### ISSUE THREAD

**Issue by canstudios-joes** [adaptlearning/adapt_authoring#2021]
## Expected Behaviour

The email input on the profile page should be editable.

## Actual Behaviour

The email input only displays your current email address and can not be changed.

## Steps to Reproduce
1. Access the profile view by selecting your email at the top right of the dashboard.
1. Try to change the email displayed.

## Versions
  - Authoring Tool Version: 0.5.0
  - Framework Version: N/A
  - Operating System: Linux Ubuntu 14.04
  - Browser: Google Chrome

**Comment by lc-thomasberger** [comment]
@canstudios-joes any progress on this?

**Comment by canstudios-nicolaw** [comment]
@lc-thomasberger I will inherit this work as Joe no longer works here

**Comment by lc-thomasberger** [comment]
Thanks for the update @canstudios-nicolaw .
