### ISSUE TITLE
toBoolean not fired for cli arguments

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#2024]
# BUG 

When config options are passed in as cli arguments during installation, the [toBoolean](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/installHelpers.js#L29-L33) hook is not executed. This can break installation in `lib/mailer` as you can not disable certain config options.

## Expected Behaviour
Boolean config options should always be properly converted into boolean regarding of there input type.

## Versions
  - Authoring Tool Version: 0.5.0
  - Framework Version: --
  - Operating System: --
  - Browser: --

**Comment by lc-thomasberger** [comment]
I think the config module should handle the conversion of y/n into true/false.

**Comment by taylortom** [comment]
This is due a limitation of prompt -- we had the same problem with the config.json overrides
