### ISSUE TITLE
Database server user and Database server password prompts

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2029]
When installing the AT these two fields should have a prompt telling that it should be blank by default.

**Comment by dancgray** [comment]
I think these [two lines ](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/mailer.js#L29-L30)mean that they are required values if useSmtpConnectionUrl is false.

Not sure if that was an intended change but it should be made clear on install or their requirement removed.

**Comment by lc-thomasberger** [comment]
@simondate [both values](https://github.com/adaptlearning/adapt_authoring/blob/master/install.js#L82-L95) should have `""` ad default value.

**Comment by simondate** [comment]
@lc-thomasberger Could we rewrite it returns empty it prompts the user `default value is empty` is or something?

**Comment by lc-thomasberger** [comment]
@simondate we could append "(optional)" to the name. I agree with you that the experience for the current install script is not the best. But I would not spend too much effort on this as we will have the server-rewrite milestone in the new future. This may effect the installation as well.
There is also [this issue](https://github.com/adaptlearning/adapt_authoring/issues/1908) which may be related to your use-case.
