### ISSUE TITLE
Error using custom CSS/LESS in Adapt Authoring 0.5.0

### ISSUE THREAD

**Issue by str-sdg** [adaptlearning/adapt_authoring#2052]
# Error using custom CSS/LESS in Adapt Authoring 0.5.0

After installing latest version of adapt authoring (0.5.0) I have found that courses can't be previewed or exported if you have written any custom CSS/LESS.
"Error generating preview, please contact an administrator." is shown.
It was tested with a fresh install.

### Error
error: [24 Aug 2018 10:33:33 +02:00] null
error: [24 Aug 2018 10:33:33 +02:00] Error: Failed to determine user's tenant!
error: [24 Aug 2018 10:33:33 +02:00] Error: Failed to determine user's tenant!
### Info
info: [24 Aug 2018 10:33:31 +02:00] Event:rebuildCourse triggered for Tenant: XXXXXXXXXX Course: YYYYYYYYYY
info: [24 Aug 2018 10:33:31 +02:00] Writing build to /course/path/XXXXX/build/.rebuild
info: [24 Aug 2018 10:33:33 +02:00] Retrieving JSON
info: [24 Aug 2018 10:33:33 +02:00] No theme customisations, but custom CSS/LESS

## Steps to Reproduce
1. Create a simple course
1. Write some valid CSS/LESS in custom CSS/LESS field.
1. Click on preview

## Versions
  - Authoring Tool Version: 0.5.0
  - Framework Version: 2.0.5
  - Operating System: Ubuntu 16.04.4 LTS
  - Browser: Chrome, Firefox, Edge

## Additional Information
I found some bugs in your code after inspect it:
Several calls to database.js function getDatabase(next, **tenantId**, type) giving as second argument "**configuration.getConfig('dbName')**" which is not the tenantId.

## Affected Area
All courses.

## Current Workaround
Unknown

**Comment by taylortom** [comment]
Hi @str-sdg, thanks for logging the issue. 

Can you confirm what Node.js version you're using? I'm not able to replicate this on v8.

**Comment by str-sdg** [comment]
Thanks for your response @taylortom. It is running with node v6.14.2.

Regards.

**Comment by taylortom** [comment]
Ah, Node v8 is required from v0.5.0 onwards. Installing that should solve your issue.

**Comment by taylortom** [comment]
Thanks for the tip!

Have just looked into this, and we also allow access to the master tenant via the DB name as well as the _id (not sure why this is the case). See [lib/database.js#L430-L431](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/database.js#L430-L431)
