### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by jefkoslowski** [adaptlearning/adapt_authoring#2054]
Hi,

We are evaluating some authoring tools on our company, and this one caught our attention. On the changelog, I verified that it is still on a 0.5.0 version. Is this a production ready tool? It's designed to be used by a user without any programming skills?

Thanks!

**Comment by taylortom** [comment]
Hi @jefkoslowski, welcome to the community!

The tool's very much ready for production, and suitable for non-technical users. Being a server-based application, installation requires someone with experience deploying production sites (particularly with regards to securing the server/database). It's not recommended that this process is undertaken by a novice.

If you're looking to deploy on a single machine locally, the above doesn't apply (although the same installation process must be followed, so it's not recommended for non-technical users). Also note that installing locally will mean that content cannot be accessed by other users.

***

**Side-note:**

Although it's still _technically_ pre-release software, there are many companies using the tool in a production environment, and some who offer services around hosting the tool (including pretty much all of the collaborating companies in the Adapt core dev team). 

The fact that we haven't hit v1.0.0 yet just means that we've not yet got a product which we think covers the original requirements we laid out for our Minimum Viable Product. We re-evaluate these goalposts after every release to make sure that we're still aiming for something that's relevant to the market.

**Comment by jefkoslowski** [comment]
Hi @taylortom, thanks a lot! Your answer addresses all my concerns and more. Much appreciated.

**Comment by taylortom** [comment]
Great 😄
