### ISSUE TITLE
Import of course with SVG asset into AT 0.5.0 seems to yield an error

### ISSUE THREAD

**Issue by lars-moch** [adaptlearning/adapt_authoring#2065]
## Expected Behaviour
I import an exported course, containig an SVG asset, and I expected it to show up in the asset library.

## Actual Behaviour
The import fails with the error message;
`Failed to create image thumbnail: ffmpeg exited with code 1: /root/adapt_authoring/data/master/assets/46/af/46af89e59240177046a12a779a418289f4a7731e.svg: Invalid data found when processing input`

## Steps to Reproduce
1. Export a course with an SVG asset from an AT.
1. Import the course into AT 0.5.0.

## Versions
  - Authoring Tool Version: 0.5.0
  - Framework Version: 2.2.5
  - Node.js Version: 8.11.4
  - MongoDB Version; 4.0.2
  - Operating System: Ubuntu 16.04.5 (AT server)
  - Browser: Chrome, Win10

**Comment by lc-thomasberger** [comment]
This is a related to missing support for svg's in ffmpeg.
If you upload a svg, you get the same error.

Easy and quick fix would be to not create thumbnails for svg's at all. https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/filestorage/localfs/index.js#L352-L399

On the long run we need to improve thumbnail creation. See https://github.com/adaptlearning/adapt_authoring/issues/1860
