### ISSUE TITLE
Getting a UnhandledPromiseRejectionWarning on course in new 0.6.0 AAT

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#2087]
## Expected Behaviour
Use to not get any issues when running course in 0.5.0 AAT

## Actual Behaviour
Getting a UnhandledPromiseRejectionWarning on course in new 0.6.0 AAT

## Steps to Reproduce
1. create a course with all the default adapt components.
2. Select a theme/menu then preview the course
3. When course is running I get a grunt error 

## Versions
  - Authoring Tool Version: 0.6.0
  - Framework Version: 2.2.5
  - Node.js Version: 8.11.2
  - MongoDB Version: 
  - Operating System: windows 10
  - Browser: chrome

![error-in-authoring-tool0 6 0](https://user-images.githubusercontent.com/10455453/46085058-1f941b80-c173-11e8-9599-995dcc85a5dd.jpg)

**Comment by tomgreenfield** [comment]
Unable to replicate this in the same environment, @mike-st. Have you tried refreshing your node modules?
```shellsession
rm -r node_modules && npm install
```
