### ISSUE TITLE
Dashboard Grid links to Courses don't work on iOS 

### ISSUE THREAD

**Issue by SteveX** [adaptlearning/adapt_authoring#2097]
## Expected Behaviour
To open courses to edit/preview on iOS devices from the dashboard.

## Actual Behaviour
From the "Dashboard - viewing my courses" page tap a grid or list item to open a course, nothing happens. 

## Steps to Reproduce
1. Log in from iOS
2. tap a grid item.

## Versions
  - Authoring Tool Version: 0.5 / 0.6
  - Framework Version: 3.0 / 3.2
  - Node.js Version:
  - MongoDB Version:
  - Operating System: iOS
  - Browser: Safari and Firefox

**Comment by taylortom** [comment]
This is a known issue; the authoring tool currently only support any mobile devices
