### ISSUE TITLE
The Frontend modules should allow hooks

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#2103]
## Affected Area
Frontend views

## Requested Feature
Frontend views should trigger events that allow other plugins / modules to tap into. This is similar to the way we handle events in the Frontend.
https://github.com/adaptlearning/adapt_framework/wiki/Core-Events#core-events

## Use Case
Extend the tool with custom plugins / module.
Make the Frontend more modular.
Test new features. 

## Current Workaround
You have to amend other modules to add the hooks.

## Additional Information
Example events:
- preRender, postRender events for views
- preview window open with handle to window

**Comment by taylortom** [comment]
Anything that extends from [OriginView](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/views/originView.js)  should have a few generic events (preRender, postRender). Haven't tried using them myself, so can't confirm they work...

What events did you have in mind?

**Comment by lc-thomasberger** [comment]
@taylortom I will have a look at the OriginView.
