### ISSUE TITLE
Problem installing adapt-contrib-assessment

### ISSUE THREAD

**Issue by drmanthova** [adaptlearning/adapt_authoring#2111]
Hi, when I'm installing the adapt authoring tool on MacBook Pro I keep getting this error:

Failed to install adapt-contrib-assessment, Unable to install adapt-contrib-assessment (undefined) as it is not supported in the current version of the Adapt framework (2.2.6)

I tried to run the command sudo node upgrade but it says the authoring tool and the framework are update.

How can I solve this?

Thanks!

## Versions
  - Framework Version: 2.2.6
  - Node.js Version: 8.12
  - MongoDB Version: 4.0.3
  - Operating System: OSX 10.14
  - Browser: Safari

**Comment by tomgreenfield** [comment]
I can confirm v2.2.7 of the framework fixes this for me.

**Comment by drmanthova** [comment]
I confirm that installing the framework v2.2.7 resolves the issue.
Thank you.
