### ISSUE TITLE
Temp formidable upload files using disk space

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#2115]
We have a problem whereby files uploaded to the tool are clogging up the tmp folder (by default, [Formidable](https://github.com/felixge/node-formidable) uses the OS' default temporary files directory when processing uploads --  `/tmp` on linux). I've not been able to ascertain whether these files are left from unhandled errors, or some other reason.

Has anyone seen anything like this?

Aside from actually figuring out what's going on here, it may be useful to move the temp upload dir to the AT's temp folder, so it's a bit more obvious what files have been created by the AT.

**Comment by lc-thomasberger** [comment]
We may also try https://www.npmjs.com/package/tmp it should be able to cleanup files
