### ISSUE TITLE
A user's courses are 'orphaned' on user delete

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#2124]
## Expected Behaviour
Courses should still be accessible after the owner user is deleted. If a course hasn't been set to shared, this won't be the case.

## Possible solutions:
- Owner is changed (possibly to the user which deleted the original owner)
- Course is set to shared automatically on user delete
- All the user's courses are deleted along with the user
- Admin users are given access to all system courses (related to https://github.com/adaptlearning/adapt_authoring/issues/1922)

## Actual Behaviour
If a course isn't shared, and its original owner deleted, it won't be accessible via the UI.

## Versions
  - Authoring Tool Version: >= 0.3.0

**Comment by lc-thomasberger** [comment]
- Owner is changed (possibly to the user which deleted the original owner) <-- Should be the default. Need a way to transfer ownenship of courses though.
- Course is set to shared automatically on user delete <-- I would not recommend this.
- All the user's courses are deleted along with the user <-- We could add a checkbox in the UserManager when deleting a user.
- Admin users are given access to all system courses (related to #1922)
