### ISSUE TITLE
"Fatal error: please run above commands in adapt course directory." When I'm installing drag and drop plugin

### ISSUE THREAD

**Issue by juanfortuna** [adaptlearning/adapt_authoring#2136]
Hi to everyone! I'm just discovering this great tool, and I'm trying to install some plugins. The drag and drop plugin shows me this error message:
> Fatal error: please run above commands in adapt course directory.

And I'm looking for the directory, but I'm not sure which one is talking about. 

I appriciate your help since now, and sorry for my possible mistakes because I'm not a english native speaker.

**Comment by taylortom** [comment]
Hi @juanfortuna, 

It looks like you're trying to use the [adapt-cli](https://github.com/adaptlearning/adapt-cli) with the authoring tool (these don't work together). If you want to install a plugin in an authoring tool installation, you need to use the plugin management page in your authoring tool.

**Comment by lc-thomasberger** [comment]
Closing tickets due to lack of response
