### ISSUE TITLE
App only runs correctly when served from document root

### ISSUE THREAD

**Issue by lalitkarki** [adaptlearning/adapt_authoring#2137]
I have been trying serve adapt via nginx with url like `www.xxx.com/adapt`. Is there any configuration available to set base url path for adapt?

My configuration:
```
location /adapt/  {
  proxy_pass http://127.0.0.1:5000/;
}
```

**Comment by lc-thomasberger** [comment]
Hello @lalitkarki can you please post technical questions in the Adapt technical Forum?
https://community.adaptlearning.org/mod/forum/view.php?id=4

**Comment by tomgreenfield** [comment]
@lalitkarki, @oscarsiles, can this be closed now?

**Comment by oscarsiles** [comment]
> @lalitkarki, @oscarsiles, can this be closed now?

I am using 0.10 straight from this repo without any issues, so it can be closed as far as I know :). If there are any further issues I will submit a pull request with fixes.
