### ISSUE TITLE
configuring completionCriteria in AT.

### ISSUE THREAD

**Issue by muthuselvan86** [adaptlearning/adapt_authoring#2138]
## Affected Area
spoor plugin configuration in AT.

## Requested Feature
From the spoor plugin readme:
**NOTE:**  as of Adapt/Spoor v3 you will first need to configure the settings in the **_completionCriteria** object in config.json to specify whether you want course completion to be based on content completion, assessment completion, or both. (In earlier versions of Spoor these settings were part of the spoor configuration - but were moved to the core of Adapt so that they could be used by other tracking extensions such as xAPI.)

There is no way in AT to configure these fields.

## Use Case: 
Any course development with spoor plugin.

## Current Workaround: 
Manually include the _completionCriteria object after exporting the source.

## Additional Information
This is a issue with v3 spoor + adapt framework.

**Comment by lc-thomasberger** [comment]
@muthuselvan86 just to confirm, are you using Version 3 of the Framework?

Currently the AuthoringTool only supports Version 2.x of the Framework.

**Comment by tomgreenfield** [comment]
Authoring tool 0.6.3 surfaces configuration options available to the installed version of the framework.
