### ISSUE TITLE
Removing an asset from a component removes all other instances of that asset

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#2141]
## Expected Behaviour
Removing an asset should only affect that asset

## Actual Behaviour
If the same asset is used multiple times in a component all all records of that asset are removed from the courseassets collection for that component.

See scaffoldAssetView.js [#L116](https://github.com/adaptlearning/adapt_authoring/blob/develop/frontend/src/modules/scaffold/views/scaffoldAssetView.js#L116). Matches on componentID (contentTypeId), content type and asset name.
 
## Steps to Reproduce
1. Add the same image in a graphic components large and small image fields and save.
2. Replace the first image and save
3. Second image courseasset collection value is removed as well

## Versions
  - Authoring Tool Version: develop branch
  - Framework Version: N/A
  - Node.js Version: v8.12.0
  - MongoDB Version: v3.6
  - Operating System: N/A
  - Browser: N/A

**Comment by dancgray** [comment]
Can't think of anywhere where more that one asset is remove using scaffold? If that's the case should removeCourseAsset be limited to removing one courseassets record?

**Comment by canstudios-nicolaw** [comment]
I'm a little rusty but I can't remember anywhere where more than one asset should be removed at a time, so limiting removeCourseAsset to one record seems sensible to me
