### ISSUE TITLE
Any server error during file upload is not managed nor presented to the user

### ISSUE THREAD

**Issue by fabiobeoni** [adaptlearning/adapt_authoring#2143]
## Expected Behaviour
File upload generating an error (like exceeding max file size) must alert the user about the error. 

## Actual Behaviour
ON front-end UI, the upload progress bar reaches 100% but not error is displayed to the user. Client console logs a 500 error but then no alert popup is displayed to the user.

Error logged on server:

> Error: maxFileSize exceeded, received 209770286 bytes of file data

Error logged on client:

> Uncaught TypeError: Cannot read property 'message' of undefined
>     at Object.error (assetManagementNewAssetView.js:122)
>     at Object.options.error (jquery.form.js:211)
>     at fire (jquery.js:3143)
>     at Object.fireWith [as rejectWith] (jquery.js:3255)
>     at done (jquery.js:9311)
>     at XMLHttpRequest.callback (jquery.js:9713)

I also noticed that any error returned from the method `localFileStorage.processFileUpload` to the invoking method `assetmanage.postAsset` by the `callback(someError)` is not handled properly and actually brings the same issue of max file size exceeded error.

## Steps to Reproduce
Just try to upload an asset of more then 200MB (Formidable's default)

## Versions
  - Authoring Tool Version: 0.6
  - Node.js Version: 6.11.4
  - Operating System: Ubuntu 16.04, Win10
  - Browser: Any

![picture1](https://user-images.githubusercontent.com/16882089/49384856-3aa77c80-f71c-11e8-9c47-c778c7ab2dad.png)

**Comment by taylortom** [comment]
Agreed that this is definitely a problem, but this issue is a bit too vague to leave open. Happy to act on any specific cases you come across 😃
