### ISSUE TITLE
remove / update code for themeSettings in outputmanager

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#2167]
https://github.com/adaptlearning/adapt_authoring/blob/master/lib/outputmanager.js#L506-L726

There is currently no way to add themesettings?
Also themes do not only have one variables.less file.

I think the future theme editor should create a file with variables that is injected into the theme and overwrites the default theme variables.

See also #1774

**Comment by canstudios-nicolaw** [comment]
Hi @lc-thomasberger , 

I don't think this is causing any problems right now, and I will be changing this code anyway as part of the theme editing feature. 

If you haven't started work on this already, I think it would be worth moving it to the theme editing milestone (https://github.com/adaptlearning/adapt_authoring/milestone/36) and assigning it to me.

**Comment by taylortom** [comment]
@canstudios-nicolaw is this still relevant?

**Comment by canstudios-nicolaw** [comment]
@taylortom I would argue not - I moved this issue onto the 0.8.0 milestone as this code was going to be rewritten as part of the theme editing feature. The code has been updated, not sure if we still need this issue or if the testing that has happened on the main theme editing PR is sufficient.
