### ISSUE TITLE
rootUrl doesn't change the path (you can only serve the authoring tool from the domain root)

### ISSUE THREAD

**Issue by Gisleburt** [adaptlearning/adapt_authoring#2175]
This maybe a feature request depending on what the expected befaviour for rootUrl is.

## Expected Behaviour

Setting the `rootUrl` in `config.json` would allow you to change where the framework is server. For example:
```json
{
  "rootUrl": "https://example.com/adapt",
}
```
would serve the adapt static assets (css, js, etc) from `https://example.com/adapt`

## Actual Behaviour

`rootUrl` is only used for paths that would be used away from the application (such as from emails).

## Steps to Reproduce

Probably n/a, but ping me if needed.

## Versions
  - Authoring Tool Version: v0.6.1
  - Framework Version: n/a
  - Node.js Version: n/a
  - MongoDB Version: n/a
  - Operating System: n/a
  - Browser: n/a

**Comment by taylortom** [comment]
@Gisleburt I think the `rootUrl` is only used for emails (as you've probably deduced). The way assets are stored/served is determined by the `localfs` file storage module. If you're looking to host your assets on a different server to the node application (or they're _already_ on another server), you'll need to write an alternative plugin.

This particular feature isn't on the planned roadmap for the near future, but if you have the ability/capacity to do any of this work yourself, I'm sure the team would be willing to help out/advise :)
