### ISSUE TITLE
Autofill large/small assets leads to broken images

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2176]
## Expected Behaviour
When I create a graphic component I should be able to use the autofill functionality and then change one of the assets.

## Actual Behaviour
If I autofill an image in the graphic component, and then select another image for one of the fields, then one image will be broken. If I preview the course I see a broken image icon, and if I refresh the editor page I can see the broken image icon on the graphic component. 

In the preview network tab I can see that the URLs for the two images are different. The working image has "......./course/en/assets/......." and the broken image has "......../course/assets/..........."

## Steps to Reproduce
1. Add graphic component.
2. Use "Select an asset" for the large image.
3. Pick an image and use "Autofill"
4. Use "Select an asset" for the small image.
5. Pick an image and select "Done"
6. Preview course and change screen size, one of the images will be broken

## Versions
  - Authoring Tool Version: 0.6

**Comment by dancgray** [comment]
@canstudios-nicolaw are you removing the small image asset before step 4? If so I think it may be the same issue as #2141 .

**Comment by canstudios-nicolaw** [comment]
@dancgray Yes you're right - I will close this issue as it's a duplicate, my apologies!
