### ISSUE TITLE
Theme settings are lost when selecting same theme

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2179]
## Expected Behaviour

Theme settings are persisted when you select the same, currently-applied theme. Users regularly do this to force a rebuild when previewing a course.

## Actual Behaviour

Theme settings are set to `null` even when the selected theme has not changed.

https://github.com/adaptlearning/adapt_authoring/blob/c07a4bdd1e0dd5c729129efb2e4b3ed7d3d75f17/plugins/content/theme/index.js#L201-L203

## Steps to Reproduce
1. Load a theme with custom theme settings and set one/more of these at course level.
1. Go to Theme Picker and hit Save with the current theme still selected.
1. Observe that the custom theme settings have been reset.

## Versions
  - Authoring Tool Version: 0.6.1

**Comment by canstudios-nicolaw** [comment]
This was fixed and released in 0.6.2
