### ISSUE TITLE
Component paste-zone layout broken

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_authoring#2214]
![image](https://user-images.githubusercontent.com/11990374/52412619-9a851f80-2adf-11e9-9625-5774cc8d2a01.png)

## Versions
  - Authoring Tool Version: 0.6.2
  - Framework Version: -- 
  - Node.js Version: --
  - MongoDB Version: --
  - Operating System: --
  - Browser: --

**Comment by tomgreenfield** [comment]
FYI, to replicate this, create two blocks, one with a component, then use the copy button from the component's context menu.
