### ISSUE TITLE
Plugin globals not always shown in Project settings

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#2223]
The globals for some plugins aren't shown in **Project settings** > **Globals** as expected (I think this only affects component globals).

The culprit being we always check `targetAttribute` rather than the passed `propertyToCheck`, so they're never rendered by Scaffold.
See: [schemas.js#L47-L57](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/modules/scaffold/schemas.js#L47-L57)

**Comment by canstudios-nicolaw** [comment]
Please can you give an example of a plugin which this is a problem for? It will be necessary for testing

**Comment by taylortom** [comment]
Could replicate for every component I tested, examples: text, graphic, MCQ.

**Comment by canstudios-nicolaw** [comment]
:+1: thank you for the info
