### ISSUE TITLE
Cannot remove Spoor's required files from published course

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2235]
## Expected Behaviour

You should be able to remove Spoor completely.

## Actual Behaviour

If you have published a course with the Spoor extension at any point, its required files are always included in subsequent publishes.

## Steps to Reproduce
1. Add the Spoor extension to a course
1. Publish
1. Remove Spoor
1. Publish
1. Observe that Spoor's required files such as `imsmanifest.xml` remain in the publish

**Comment by moloko** [comment]
this isn't confined to spoor; any plugin that uses the 'required' folder to add files to the build (e.g. adapt-contrib-media) will have the same problem

I don't believe there's anything in place in the build process to 'clean' the build of files that have been removed from src

Same issue occurs if using the framework and CLI
