### ISSUE TITLE
Automatically add extensions only works for extensions with schema globals

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#2241]
## Expected Behaviour
All extensions enabled to automatically add to new courses should be added. See PR #1891 

## Actual Behaviour
Only extensions with globals defined in their schema are added.

## Steps to Reproduce
1. enable "Add to new courses by default?" on assessment, bookmarking or spoor 
2. Create a new course
3. Go to manage extensions for the new course.

## Versions
  - Authoring Tool Version: 0.7.0
  - Framework Version: v2.3.3 or v4.0.1
  - Node.js Version: 10.15.0
  - MongoDB Version: 3.6
  - Operating System: macOS 10.14.3
  - Browser: Chrome 72

**Comment by taylortom** [comment]
I'm not able to replicate this on `release/0.7.0`. Steps I took:
1. Select 'Add to new courses by default?' for assessment
2. Create new course
3. Assessment was already enabled

**Comment by lc-thomasberger** [comment]
I can replicate this.

**Comment by taylortom** [comment]
@lc-thomasberger which plugin did you test with?

**Comment by lc-thomasberger** [comment]
Assessment.
But I also selected all extensions and it did not add all extensions. I think assessment never got added.

**Comment by taylortom** [comment]
Ok so I can consistently get the above issue with assessment, but only when a lot of extensions are selected (in my initial tests, I only had about 4 selected).

**Comment by tomgreenfield** [comment]
For the record, I can replicate @dancgray's original issue.

**Comment by lc-thomasberger** [comment]
When I debug, it turns out that [results](https://github.com/adaptlearning/adapt_authoring/blob/release/0.7.0/plugins/content/extension/index.js#L321) is an empty array. The config item is not yet created in the DB.

When I use the manage extensions UI, the results array contains the config item from the DB.
