### ISSUE TITLE
Add test-cases for 0.7.0

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#2252]
See [documentation/02_authoring_tool/08_test_cases](https://github.com/adaptlearning/documentation/tree/master/02_authoring_tool/08_test_cases)

Please add any test-cases for features added in 0.7.0 to the description below.
_**Note**: the below are not necessarily in final form_
- [x] Breadcrumbs
- [x] Share course with users
- [x] Course force rebuild
- [x] User search/filter
- [x] Default plugins
- [x] Component list item duplication
- [x] Change own email via profile
- [x] Admins should be able to give new users a name
- [x] Admins should be able to send users a welcome email
- [x] Admins shouldn't be able to change the passwords of users
- [x] Admins should be warned that the reset password button will send an email

**Comment by canstudios-kent** [comment]
Test scripts created or edited to cover:
- [x]   Breadcrumbs:
 - Courses > "Course editor breadcrumbs".
- [x]   Share course with users:  
 - Courses - Sharing / Downloading Content > "Courses Sharing - Specific users".
- []   Course force rebuild
- [x]   User search/filter: 
 - User Management > "Filter users".
- [x]   Default plugins: 
 - Plugin Management > "Course default extensions".
- [x]   Component list item duplication: 
 - Courses > "Copying list items within a component".
- [x]   Change own email via profile: 
 - Login > "Change email address".
- [x]   Admins should be able to give new users a name: 
 - Edited "Adding New Users".
- [x]   Admins should be able to send users a welcome email: 
 - User Management > "Invite user".
- [x]   Admins shouldn't be able to change the passwords of users: 
 - Removed "Change password"; edited "Reset password emails".
- [x]   Admins should be warned that the reset password button will send an email: 
 - edited "Reset password emails".

Other test scripts:
- Ace Editor's syntax colouring is lost when code is uglified: Edited "Change the Primary Colour on a course".
- Custom CSS box should be resizeable: Edited "Change the Primary Colour on a course".
- Enable Admins to delete any shared course: Edited " Courses Sharing - Shared course".
- Expose authoring tool version in the HTML: Login > "Framework and authoring version".
- A user's courses are 'orphaned' on user delete: User Management > "Delete user - Orphaned courses - Share all courses"; "Delete user - Orphaned courses - Delete all unshared courses"; "Delete user - Orphaned courses - Transfer ownership to me".
- Add ability to search/filter user list: User management > "Filter users".

**Comment by canstudios-nicolaw** [comment]
@taylortom I have checked off the items and am closing the issue as @canstudios-kent has completed this. (He doesn't have permissions to check items off the list on the issue or close it)
