### ISSUE TITLE
Dashboard paging broken after deleting courses

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#2253]
## Expected Behaviour
On deleting a course, we need to do a fresh fetch to make sure the full amount of courses are shown. 

## Actual Behaviour
It's possible to break the paging by deleting enough courses to hide the scrollbar.

## Steps to Reproduce
1. Make sure you have enough courses to cause paging
1. Resize browser to fit a small number of courses (I had two rows of three)
1. Delete courses until you're down to a single row
1. Note no more courses are fetched, page must be refreshed to fix

**Comment by lc-thomasberger** [comment]
I am not sure if we should stick to the infinite scrolling approach.
Especially for Assets I think it is more usable to have pagination links. As this gives you a better overview about the amount of pages/ items are available. It is also much easier to navigate through a collection. A good example is github's issue page.

I think we should move to pagination links for Assets and Dashboard.

**Comment by taylortom** [comment]
Also see: https://github.com/adaptlearning/adapt_authoring/issues/1824

**Comment by canstudios-scottd** [comment]
Verfied as fixed on testing.
