### ISSUE TITLE
Roles with lesser permissions cannot see any shared courses

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2266]
## Expected Behaviour

All roles can see courses shared with everyone.

## Actual Behaviour

Roles other than `Super Admin` and `Tenant Admin` cannot see any shared courses.

Front end error received:
```console
jquery.js:9659 GET http://localhost:5000/api/shared/course?search%5Btitle%5D=.*.*&operators%5Bskip%5D=0&operators%5Blimit%5D=1&operators%5Bsort%5D%5Btitle%5D=1 500 (Internal Server Error)
```

## Steps to Reproduce
1. Share a course with all users
1. Log in as an authenticated user and navigate to the shared courses page

## Versions
  - Authoring Tool Version: 0.7.0
  - Node.js Version: 10
  - MongoDB Version: 3.2

**Comment by canstudios-nicolaw** [comment]
@tomgreenfield Are you looking into this or would you like me to pick it up?

**Comment by tomgreenfield** [comment]
Feel free to dive in. Thanks, @canstudios-nicolaw.

**Comment by canstudios-nicolaw** [comment]
:+1:  I'll start looking at this now

**Comment by canstudios-nicolaw** [comment]
@tomgreenfield I don't seem to be able to reproduce this.

I have logged in as a super admin, created a course, shared it with everyone (it isn't shared with any individuals), and logged out. I can then log in as a course creator or authenticated user and see the course on the shared courses dashboard and preview it.

As a product manager I can see the course on the shared courses dashboard but I can't preview it (I'm not sure if this is a regression).

I am on the release/0.7.0 branch of the authoring tool, and the issue/2345-legacy branch of the framework. Please could you provide some more details as to how you are reproducing this?

**Comment by tomgreenfield** [comment]
Can replicate consistently with the same branches.

@taylortom, can you shed any light?

**Comment by canstudios-nicolaw** [comment]
Is there any useful information in the logs?

I had a permissions issue looking at the shared dashboard when I had an old course floating around with a different tenant id, there is no chance you could have something like that?

**Comment by taylortom** [comment]
I could replicate this one yesterday, will have another test.

**Comment by tomgreenfield** [comment]
@canstudios-nicolaw, to replicate, ensure at least one course is shared with all users **and** shared with a defined user different to the authenticated user.

**Comment by canstudios-nicolaw** [comment]
I've got a fix for this but it's going to be in the PR for https://github.com/adaptlearning/adapt_authoring/issues/2271 as I came across this issue when testing that PR
