### ISSUE TITLE
Text misalignment under "Failed logins" and "Last access" headers

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_authoring#2276]
## Expected Behaviour
The text within the user list are aligned with their respective headers:
* Email address, Tenant, and Role are left-aligned.
* Failed logins, and Last access are center-aligned.

## Actual Behaviour
The text for the Failed logins, and Last access are not center-aligned with their headers. They are not left or right aligned either. 

## Steps to Reproduce
1. Navigate to User management. Notice that the text under "Failed logins" and "Last access" are further to the right of their respective headers.

## Versions
  - Authoring Tool Version: v0.7.0
  - Framework Version: v2.3.2

**Comment by canstudios-nicolaw** [comment]
I think that this could be closed without action.

I can see that the failed logins and last access columns have been centrally aligned deliberately. It's not clear to me that this is wrong. Attached are a couple of screenshots showing what this would look like with the central alignment removed. I think centrally aligning 'thinner' columns is a fairly common design.

![Screenshot from 2019-03-29 14:00:10](https://user-images.githubusercontent.com/25502448/55238011-61d60c80-522b-11e9-8175-706f24584bc6.png)
![Screenshot from 2019-03-29 14:00:23](https://user-images.githubusercontent.com/25502448/55238015-639fd000-522b-11e9-91bd-e8f1db5e8fc3.png)

**Comment by tomgreenfield** [comment]
> The text for the Failed logins, and Last access are not center-aligned with their headers. They are not left or right aligned either.

Last time I checked this _was_ true; there's some funky padding and other styling in there that should be looked at.

**Comment by canstudios-nicolaw** [comment]
You're right I was looking on the wrong server (sigh). It looks like display:flex is the culprit
