### ISSUE TITLE
Cannot change other users' passwords

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2280]
## Expected Behaviour

I should be able to change other users' passwords from user management.

## Actual Behaviour

I receive a duplicate user error:

![error](https://user-images.githubusercontent.com/922987/54035372-2490d880-41b1-11e9-995b-648db34d3545.png)

## Steps to Reproduce
1. Try to change another user's password from user management.

## Versions
  - Authoring Tool Version: 0.7.0
  - Node.js Version: 10
  - MongoDB Version: 3.2

**Comment by canstudios-nicolaw** [comment]
:+1: was just about to raise this
