### ISSUE TITLE
Authoring tool should have same field restrictions as framework

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2289]
Looking at accordian the authoring tool mandates item titles and body… but I dont think the framework needs them (they are only enforced by the AT front end). 

Eg. If I want to put an image in an accordion item I have to put text with it which is a shame. 

Can we look at removing authoring tool only restrictions to match the framework?

**Comment by Link2Twenty** [comment]
Isn't that caused by the schema?

https://github.com/adaptlearning/adapt-contrib-accordion/blob/master/properties.schema

having `"validators": ["required"],` tells AAT that the field is required.

**Comment by tomgreenfield** [comment]
@Link2Twenty is spot on; any schema suggestions are to be raised on the framework repo.
