### ISSUE TITLE
Tag preview not showing via upload asset from component

### ISSUE THREAD

**Issue by tomallpress** [adaptlearning/adapt_authoring#2300]
## Expected Behaviour
When uploading an asset via a component (not direct into the asset manager), you should be able to begin typing in the Tags box and see a preview of all similar tags.

It _does_ behave like this when uploading directly into the asset manager.

## Actual Behaviour
When typing you don't get the tag preview when uploading an asset from a component.

## Steps to Reproduce
1. Edit a component
2. Click on Select an Asset
3. Click on Upload new asset
4. Begin typing the name of a tag already created, in the Tags box.

## Versions
  - Authoring Tool Version: 0.7.0
  - Framework Version: 4.1.0
  - Node.js Version:
  - MongoDB Version:
  - Operating System: Windows 10
  - Browser: Chrome

**Comment by SteveX** [comment]
I don't see a preview of existing tags in upload either, and don't remember seeing it in any previous versions. (All browsers on a Mac, no errors in console.) Sorting by tag doesn't work either.
