### ISSUE TITLE
Invite / reset password terminology could be more helpful

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2304]
It has been reported that the invite email and linked password reset screen is slightly confusing for new users. @kineopete, would you mind detailing your favoured tweaks to the below?

#### Welcome to Adapt 
You have been invited to join by peter.smith@kineo.com

To log in, head to your [Adapt authoring tool](https://testing.kineoadapt.com)

If you do not know your password you should request a reset at: [https://testing.kineoadapt.com/#user/forgot](https://testing.kineoadapt.com/#user/forgot)

### Password reset

![reset](https://user-images.githubusercontent.com/922987/55874020-07bd3b80-5b89-11e9-89ac-94c939eb25ae.jpg)

**Comment by taylortom** [comment]
I feel like the user creation workflow could do with some refinement. In particular, it seems slightly odd that you have to enter all account details before you're able to send out an invite.

### 1. Invite
1. Navigate to user management
1. New sidebar button labelled 'Invite new user'
1. Clicking button prompts user to enter an email address, role and tenant
1. Email is sent out to new user which forces password change on first login
### 2. Manual creation
1. Navigate to user management
1. Click 'Add new user' to load existing form (password field should not be present if SMTP is configured)
1. Email is sent out to new user's email account with a link to force password reset on first login

In both cases, it would be nice to add an extra form page on first login to allow the new user to set their name and password, so the admin doesn't have to. Would also be nice to later hook this up to a brief tutorial or something to give users an introduction to the tool.

In terms of wording, something like:

> **Welcome to Adapt!**
>
> A new account has been set up for you at [https://testing.kineoadapt.com](). Please [click here]() to log in and set a password.
>
> If you did not request this account, please contact [Peter Smith]() for more information.

**Comment by kineopete** [comment]
Hey Tom,

I like your approach, and agree that this would be a better user flow than the current one.

If it would be more expedient, just a quick change to the wording in the welcome email would improve the current experience. I would suggest:

Welcome to the Adapt Authoring Tool

[username] has created a new account for you; your username is [emailaddress]

To start authoring courses please go here https://subdomain.domain.com/#user/forgot and create a new password.
