### ISSUE TITLE
Roles with lesser permissions cannot see asset tags list

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2306]
## Expected Behaviour

Course Creators should be able to see an auto-complete list of asset tags.

## Actual Behaviour

Super Admins can type to see an auto-complete list of tags but Course Creators cannot.

## Steps to Reproduce
1. Click to edit an asset in Asset Manager while logged in as a Course Creator.
1. Type in the tags field and notice there are no auto-complete entries.

## Errors
```console
GET http://localhost:5000/api/autocomplete/tag?term=m 403 (Forbidden)
```
```json
{"statusCode":"access-denied"}
```

## Versions
  - Authoring Tool Version: 0.7.1
  - Framework Version: 2.3.3
  - Node.js Version: 10.11
  - MongoDB Version: 3.2

**Comment by canstudios-scottd** [comment]
Testing Results:

This still occurs in the assets area for course creators:
![Screenshot from 2019-08-19 15-20-17](https://user-images.githubusercontent.com/48051609/63272958-eede3880-c294-11e9-8bc2-50a1d3bf6dd3.png)


Additionally, this also occurs in the courses project settings for course creators (including shared courses):
![Screenshot from 2019-08-19 15-19-30](https://user-images.githubusercontent.com/48051609/63272988-00bfdb80-c295-11e9-9aa3-59031d736f62.png)
