### ISSUE TITLE
Upgrade script should check for compatible framework updates

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2307]
## Expected Behaviour

The automatic upgrade functionality should check for updates in the currently installed framework's major range, e.g. instances running `3.4.0` should upgrade to `3.5.3` and instances running `4.0.0` should upgrade to `4.1.1`.

## Actual Behaviour

The update check for the framework is restricted to the version specified in package.json's `framework` field.

## Steps to Reproduce
1. Run `node upgrade` and press <kbd>↵ Enter</kbd> on both prompts.

**Comment by taylortom** [comment]
Think this is more of an enhancement than a bug, as the code should be limiting the app based on the value in `package.json` (which is `2`).

We've got two scenarios to cover here:
1. **New installs**: which version is pulled down.
1. **Upgraded installs**: what range should be used.

I'd prefer not to update `package.json` each upgrade, as this will likely lead to confusion; moving over to use a `config.json` value probably makes more sense.

**Comment by tomgreenfield** [comment]
If the major range for an upgrade was determined from the currently installed framework then I'd have fewer gripes now bumping to `4` for new installs.

Agree with using the config JSON; I'm not a fan of the stagnant `frameworkRevision` field that gets left behind in there at present.
