### ISSUE TITLE
Admins can see other users' unshared courses

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2312]
## Expected Behaviour

The shared courses view shouldn't show other users' unshared courses.

## Actual Behaviour

The shated courses view shows other user's unshared courses.

## Steps to Reproduce
1. Log in as a Super Admin and go to shared courses.

## Versions
  - Authoring Tool Version: 0.7.1
  - Framework Version: 2.2.3
  - Node.js Version: 10.11
  - MongoDB Version: 3.2

**Comment by canstudios-nicolaw** [comment]
I expect that this is an extension of this issue, but the search functionality appears to be broken for the shared courses dashboard, as does the sort.

**Comment by tomgreenfield** [comment]
As in https://github.com/adaptlearning/adapt_authoring/issues/2294? Can't myself replicate this myself on our 0.7.1 instances.

**Comment by canstudios-nicolaw** [comment]
I don't think I'll be able to reply properly today, but will investigate this further and try and post some more useful info later this week.

**Comment by canstudios-nicolaw** [comment]
@taylortom I know you mentioned in the call last week you would have a look at this? Did you get a chance to in the end? I can pick it up if not
