### ISSUE TITLE
Theme and Menu globals are broken

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_authoring#2313]
## Expected Behaviour
Globals defined in the theme and menu plugin schema should get pulled through to the project settings area in the authoring tool. 

## Actual Behaviour
They do not. They also do not appear in the exported course.json file.

## Steps to Reproduce
1. Add a globals attribute to either menu or theme
1. Load either plugin into the authoring tool and navigate to project settings

## Versions
  - Authoring Tool Version: 0.7.1
  - Framework Version: 4.1.0
  - Operating System: macOS Mojave 10.14.4
  - Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)

**Comment by guywillis** [comment]
Update required to adapt-contrib-boxmenu schema 'menu' value to fix the bug associated with the menu.

Theme bug still outstanding.

**Comment by tomgreenfield** [comment]
Reference: theme globals should just need similar fix to https://github.com/adaptlearning/adapt_authoring/commit/5abe2cfa8e5c6c15af4ff6ce7bdc94a699ffeafe.
