### ISSUE TITLE
Custom lock does not work when locking/unlocking course elements are in different submenus

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_authoring#2343]
## Expected Behaviour
Course elements that are custom locked should become accessible upon completing the required course elements.
## Actual Behaviour
When the required course elements are located in a different submenu and are completed, the locked course element remains inaccessible. The require course element unlocks once all other course elements that are in the same submenu as the required course element are completed. This also includes other submenus that are both nested above the required course elements  **and** nested below the locked course element.

## Steps to Reproduce
1. Create a course. Set the "Menu lock type" to "custom".
1. On level-1, add a page and a submenu.
1. Click the level-1 submenu. In this submenu (level-2), add a submenu and 2 pages.
1. Click the level-2 submenu. In this submenu (level-3), add 2 pages.
1. Copy only 1 page ID from the page in the previous step.
1. On level-1, enter the settings area of the page.
1. Under "Locked by", paste the page ID into the "Locked by" field.
1. Click "Save". Click "Preview".
1. Navigate to level-3. Complete the page from step (5).
1. Navigate back to level-1. Notice that the locked page is still inaccessible.
1. Completed the other accessible course elements. Navigate back to level-1. Notice that the page is now unlocked.

## Versions
  - Authoring Tool Version: v0.8.0
  - Framework Version: v2.4.0

**Comment by tomgreenfield** [comment]
I believe this is a the same as https://github.com/adaptlearning/adapt_framework/issues/2469, which was fixed in framework versions 3.4.8 and 5.2 respectively.

Feel free to reopen if any issue.
