### ISSUE TITLE
Theme editing issues

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_authoring#2358]
## Expected Behaviour

a) I should be able to select a transparent (rgba) colour for my theme
b) I should be able to specify a select option for a theme variable in the theme's properties schema

## Actual Behaviour

a) colour is saved as hex, so any alpha value selected using the colour picker is lost
b) a script error occurs as EditorThemingView assumes `fieldView.schema.inputType` is a string

## Steps to Reproduce
a) select a transparent colour in the theme editor, save and preview theme. 
b) create a theme with at least one property where InputType is `{ "type": "Select", "options": [...] }`

## Versions
  - Authoring Tool Version: 0.8.0
  - Framework Version: 4.2.0

**Comment by canstudios-nicolaw** [comment]
Part a) of this has been fixed on the bugpatch branch. This should be mentioned in any release notes etc.

**Comment by danielstorey** [comment]
Part b) should be fixed as well ;)

**Comment by canstudios-nicolaw** [comment]
Brilliant, I'll add a merged tag :)
