### ISSUE TITLE
Latest version of plugin not being detected in AT

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2366]
## Expected Behaviour
On 27 April 2019, version 2.2.0 of bookmarking was released (https://github.com/adaptlearning/adapt-contrib-bookmarking/releases).

I should be able to use this version in the AT.

## Actual Behaviour
My AT is running v2.4.0 of the framework (which is compatible according to the plugins bower), and has v2.1.3 of bookmarking installed. If I attempt to check for updates, then the latest release is not picked up. If I modify the framework's adapt.json to pull in version 2.2.0 of bookmarking specifically then I am still left with 2.1.3 after running the AT's upgrade script.

I haven't come across something like this before, so I'm not sure if it should be a framework issue.

## Steps to Reproduce
1. Go to plugin manager
1. Go to bookmarking
1. Click check for updates, see that no update is detected

## Versions
  - Authoring Tool Version: 0.8.1
  - Framework Version: 2.4.0

**Comment by tomgreenfield** [comment]
It's due to the [tag](https://github.com/adaptlearning/adapt-contrib-bookmarking/tags) being badly named (`v.2.2.0`).

**Comment by canstudios-nicolaw** [comment]
I thought it might be something like this... Is it possible/allowed to edit the tag?

**Comment by tomgreenfield** [comment]
I'd say delete the dodgy tag. Thoughts, @moloko?

**Comment by moloko** [comment]
sounds good to me @tomgreenfield

**Comment by canstudios-nicolaw** [comment]
I've not done this in Github before, it seems I will have to delete and re-create the release, is this what you are expecting?

**Comment by moloko** [comment]
@canstudios-nicolaw yes, totally. I don't mind doing this (seeing as it was my poor typing skills that caused this in the first place) just let me know!

**Comment by canstudios-nicolaw** [comment]
I have now re-released this with the correct tag and confirmed I'm seeing it in the AT :)
