### ISSUE TITLE
Theme editor: Error modal appears when course creator changes theme; Course creator cannot apply presets

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_authoring#2385]
## Expected Behaviour
Users that can make channges to courses should be able to change the course theme.

## Actual Behaviour
As a course creator, an error modal appears when applying a preset. THe modal says "Something went wrong while saving your data. Please try again.". This does not occur with a Super Admin.
A 500 error appears in the browser console.
The base theme is applied, but the preset is not.

## Steps to Reproduce
1. Log in as a course creator user. Navigate to Theme editor in a course.
1. Select a different theme with a preset. Click Save. Notice the error modal appears.
1. Preview the course. Notice that the base theme has been applied yet the preset has not been applied.

## Versions
  - Authoring Tool Version: v0.9.0
  - Framework Version:

**Comment by canstudios-nicolaw** [comment]
@tomgreenfield @dancgray I have fixed this for course creators. @canstudios-kent has pointed out to me that this is also happening for authenticated users. Do we want to fix this for authenticated users - I'm not sure what their permissions _should_ be?

**Comment by tomgreenfield** [comment]
Thanks for picking this up so quickly, @canstudios-nicolaw. I'm happy for this to be pushed to the next release if you are; I feel like this might need some thought.

**Comment by canstudios-nicolaw** [comment]
@tomgreenfield I'd like the fix for course creators to go into this release since course creators cannot use theme presets at the moment. I'd be happy for any authenticated user changes to go into the next release.

**Comment by canstudios-nicolaw** [comment]
@tomgreenfield @dancgray (Sorry because I realise I've been saying this a lot lately) any chance of some :eyes:? Or did you want to discuss on Monday Tom?

This is the last 0.9.0 issue, QA here have been through everything else now
