### ISSUE TITLE
HotGraphic component device:changed device:resize issue

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#2392]
## Expected Behaviour
When you adjust the screen size of your browser from mobile size to desktop manually it should adjust without creating duplicates of the component.

## Actual Behaviour
When you adjust the screen size of your browser from mobile size to desktop manually it duplicates the Hotgraphic component on the page each time you touch the browser window to resize it. I also have a narrative on the page with it so not sure if that is interfering with it too as Hotgraphic converts to narrative in mobile view.

## Steps to Reproduce
1. Preview a page with a Hotgraphic component and narrative component on it.
2. Resize your broswer window to a mobile size and let go. Now resize the window back to desktop size. Continue to do this a couple of times.
3. each time you resize the window the Hotgraphic component will duplicate itself and another will appear on the page.

## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: 4.2.0
  - Node.js Version: 10.16.0
  - MongoDB Version: 3.4.7
  - Operating System: Windows 10
  - Browser: Chrome

**Comment by canstudios-nicolaw** [comment]
Hi @mike-st 

This is an Adapt Framework issue rather than an Adapt Authoring issue

This issue has already been raised in the framework so I am going to close it here
Framework issue: https://github.com/adaptlearning/adapt_framework/issues/2435
