### ISSUE TITLE
Narrative: scroll bar appears in graphic area when Text area navigation is disabled and an item has attribution text

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_authoring#2405]
## Expected Behaviour
There shouldn't be a scroll bar within any item of a Narrative component.

## Actual Behaviour
When a Narrative component has text area navigation enabled and attribution text within at least one item, the graphic area of a Narrative item gains a scroll bar. This does not occur when all items within the Narrative component lack attribution text or when text area navigation is disabled.

## Steps to Reproduce
1. In a course, add a Narrative component. 
1. Navigate into the Narrative component's properties.
1. Enable "Move navigation to text area". 
1. Add a few items with attribution text. 
1. Click Save. Click Preview. 
1. Navigate to the Narration component. Notice that the graphic of the item has a scroll bar.

## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: 4.2.0

**Comment by tomgreenfield** [comment]
@canstudios-kent, this very much sounds like an issue with the plugin itself. Would you mind moving this to the [framework](https://github.com/adaptlearning/adapt_framework/issues/new) repository?

@guywillis, might be prudent to check this won't be an issue in the upcoming Narrative 6.

**Comment by canstudios-kent** [comment]
@tomgreenfield Issue closed and moved to framework repository. (https://github.com/adaptlearning/adapt_framework/issues/2509)
