### ISSUE TITLE
installation: missing translation key for app.productname

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_authoring#2410]
During my install of the authoring tool, the console reported:  
`missing translation key for app.productname` 
Installation was successful nonetheless.

## Versions
  - Authoring Tool Version: v0.9.0
  - Framework Version: v4.2.0
  - Node.js Version: v10.16.2
  - MongoDB Version: v4.0.1
  - Operating System: Ubuntu 18.04.1
  - Browser: Chrome Version 69.0.3497.100

**Comment by tomgreenfield** [comment]
Original intended string is:
> Now we need to set up a 'Super Admin' account. This account can be used to manage everything on your Adapt authoring tool instance.

As discussed in the weekly meeting, suggest we hardcode the reference to Adapt or amend to something generic.
