### ISSUE TITLE
Fix reading of asset type from schema

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2416]
## Expected Behaviour

As part of the scaffold refactor in version 0.6, we strived to standardise the schema input types. This included removing the need to scrub strings with regular expressions, and instead allowing an object to specfiy options. For an asset, the desired schema includes a `media` field:
```json
"_photo": {
  "type": "string",
  "default": "",
  "title": "Photo",
  "inputType": {
    "type": "Asset",
    "media": "image"
  },
  "help": "Select a photo"
}
```
## Actual Behaviour

Although the scaffold can already handle it, asset management errors with the new schema:
```console
assetManagementModalView.js:28 Uncaught TypeError: this.options.assetType.replace is not a function
```

There are also some tweaks needed to the new theme editor.

## Steps to Reproduce
1. Update an asset field to use the new `inputType`
1. Click _Select an asset_ on the form

## Versions
  - Authoring Tool Version: 0.9

**Comment by canstudios-nicolaw** [comment]
@tomgreenfield Please could you be a bit more explicit about step 1 on the reproduce instructions? Would help with testing

**Comment by tomgreenfield** [comment]
For example, this [input type](https://github.com/adaptlearning/adapt-contrib-accordion/blob/master/properties.schema#L92):
```json
"inputType": "Asset:image"
```
would be updated to:
```json
"inputType": {
  "type": "Asset",
  "media": "image"
}
```
