### ISSUE TITLE
Installation instructions: No ffmpeg option (Windows 10)

### ISSUE THREAD

**Issue by TimFrance** [adaptlearning/adapt_authoring#2418]
## Expected Behaviour
According to install instructions:
Note: FFmpeg is not used by default. When the question "Will ffmpeg be used?" N (i.e. no) will appear as the default. If FFmpeg is installed and you want to use it, type Y before pressing the Enter key.

## Actual Behaviour
There is no question on ffmpeg. Here is the console output

C:\Users\tbaker\Documents\adapt_authoring>node install

This script will install the application.
Would you like to continue?
> Continue? Y/n (Y)

We need to configure the tool before install.
Tip: just press ENTER to accept the default value in brackets.
> Server port (5000)
> Server name (localhost)
> Data directory path (data)
> Git repository URL to be used for the authoring tool source code (https://github.com/adaptlearning/adapt_authoring.git)
> Git repository URL to be used for the framework source code (https://github.com/adaptlearning/adapt_framework.git)
> Specific git revision to be used for the framework. Accepts any valid revision type (e.g. branch/tag/commit) (tags/v2.4.0)
> Master database name (adapt-tenant-master)
> Will you be using a full database connection URI? (all connection options in the URI) y/N (N)
> Database host (localhost)
> Database server port (27017)
> Database server user (only specify if using database authentication)
> Database server password (only specify if using database authentication)
> Database server authentication database (only specify if using database authentication)
> Will you be using an SMTP server? (used for sending emails) y/N (N)
Now we need to configure the master tenant.
Tip: just press ENTER to accept the default value in brackets.

> Set a unique name for your tenant (master)
> Set the display name for your tenant (Master)

Cloned https://github.com/adaptlearning/adapt_framework.git successfully.
\temp\5d5f661f27ad7231e0404814\adapt_framework switched to revision tags/v2.4.0
Node dependencies installed successfully.
Adapt framework plugins updated.
Master tenant created successfully.
Warning: Missing translation for key: "app.productname"

Now we need to set up a 'Super Admin' account. This account can be used to manage everything on your app.productname instance.
> Email address xxxx@yyyy.com
> Password *********
> Confirm Password *********

Web application built successfully.

Installation completed successfully, the application can now be started with 'node server'.

## Steps to Reproduce
1. Just install on Windows 10 
1.
1.
## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: ?? Downloaded today
  - Node.js Version: v10.16.3
  - MongoDB Version: Downloaded today
  - Operating System: Windows 10
  - Browser: Chome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by tomgreenfield** [comment]
Thanks for the issue; the outdated references to FFmpeg have now been removed from the wiki.

**Comment by johnniezen** [comment]
I thought FFmpeg was needed to show the thumbnails for the assets? Or is that now solved a different way?

**Comment by tomgreenfield** [comment]
@johnniezen, the mechanism was changed in https://github.com/adaptlearning/adapt_authoring/pull/2171.

**Comment by darioseidl** [comment]
@tomgreenfield Sorry, I'm confused. I'm setting up adapt for a client and they asked about generating thumbnails. 

In the pull request you mentioned, ffmpeg installation was added to the `install.js` script, but in this [commit](https://github.com/adaptlearning/adapt_authoring/commit/e139adf9f29820cbb037594b9076753554c28b60#diff-bca55137afc086582855731d4e7750b1c5988a6c5f3917f966e04d8b8c01ec59) it was removed again.

Is ffmpeg still needed to generate thumbnails? Should we install it manually again?

**Comment by taylortom** [comment]
@darioseidl the commit you linked is specifically related to the config option only, 
The changes made in https://github.com/adaptlearning/adapt_authoring/pull/2171 (i.e. including a local ffmpeg binary as a node module) still apply :)

If you're still having issues with thumbnails, there may be a separate issue.

**Comment by darioseidl** [comment]
Ah, I see, it's installed as a node module now, so it's not necessary anymore to ask about it in the install script or to install it manually. Thank you for clearing that up!
