### ISSUE TITLE
Installation npm vunerability warnings - Braces / Windows 10

### ISSUE THREAD

**Issue by TimFrance** [adaptlearning/adapt_authoring#2420]
## Expected Behaviour
No npm vunerability warnings
## Actual Behaviour
Run  npm install migrate-mongoose@4.0.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
  Low             Regular Expression Denial of Service
  Package         braces
  Dependency of   migrate-mongoose
  Path            migrate-mongoose > babel-cli > chokidar > anymatch >
                  micromatch > braces
  More info       https://npmjs.com/advisories/786
                                 Manual Review
             Some vulnerabilities require your attention to resolve
          Visit https://go.npm.me/audit-guide for additional guidance

## Steps to Reproduce
There appears to be two versions of the brace package in the Adapt installation
\node_modules\anymatch\node_modules\braces\package.json shows braces@1.8.5
\node_modules\braces\package.json shows braces@2.3.2

According to https://www.npmjs.com/advisories/786
Versions of braces prior to 2.3.1 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.
Remediation
Upgrade to version 2.3.1 or higher.

So it appears that the older version of braces at \node_modules\anymatch\node_modules\braces is the source of the problem.

see also https://github.com/adaptlearning/adapt_authoring/issues/2419
https://github.com/adaptlearning/adapt_authoring/issues/1745
@LouiseMcMahon

## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: 2.4.0
  - Node.js Version: v10.16.3
  - MongoDB Compass Community Version: 1.19.6
  - Operating System: Windows 10
  - Browser: Chome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by oliverfoster** [comment]
Hi Tim, could you please read and respond to my comments on your original issue before you make any more?

You have clearly identified a third degree module which has outstanding security warnings, as I had mentioned in my original comment, we have no control over those modules.

We will not be suppressing the security vulnerabilities.

**Comment by oliverfoster** [comment]
Please add these sub items to your original issue. They are the same issue and you have yet to respond to my original message.

**Comment by TimFrance** [comment]
Oliver

Sorry for the crossed wires, I was making the suggestions without
consulting my mails and I thought it was best practice to separate issues

Tim

**Comment by oliverfoster** [comment]
No worries :+1:
