### ISSUE TITLE
Installation npm vunerability warnings - lodash / Windows 10

### ISSUE THREAD

**Issue by TimFrance** [adaptlearning/adapt_authoring#2421]
## Expected Behaviour
no npm vulerability warnings
## Actual Behaviour
High            Prototype Pollution
  Package         lodash
  Patched in      >=4.17.11
  Dependency of   grunt-merge-json
  Path            grunt-merge-json > lodash
  More info       https://npmjs.com/advisories/782
  High            Prototype Pollution
  Package         lodash
  Patched in      >=4.17.12
  Dependency of   grunt-merge-json
  Path            grunt-merge-json > lodash
  More info       https://npmjs.com/advisories/1065

## Cause?
\node_modules\lodash\package.json contains:
  "_from": "lodash@^4.8.0",
  "_id": "lodash@4.17.15",

https://www.npmjs.com/advisories/782
Versions of lodash before 4.17.5 are vulnerable to prototype pollution.
The vulnerable functions are 'defaultsDeep', 'merge', and 'mergeWith' which allow a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.
Remediation
Update to version 4.17.11 or later.

https://npmjs.com/advisories/1065 same information and remedy as https://npmjs.com/advisories/782

## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: 2.4.0
  - Node.js Version: v10.16.3
  - MongoDB Compass Community Version: 1.19.6
  - Operating System: Windows 10
  - Browser: Chome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by oliverfoster** [comment]
Please add these sub items to your original issue. They are the same issue and you have yet to respond to my original message.
