### ISSUE TITLE
Installation npm vunerability warnings - fstream/ Windows 10

### ISSUE THREAD

**Issue by TimFrance** [adaptlearning/adapt_authoring#2422]
## Expected Behaviour
no npm vunerability warnings
## Actual Behaviour
High            Arbitrary File Overwrite
  Package         fstream
  Patched in      >=1.0.12
  Dependency of   unzip
  Path            unzip > fstream
  More info       https://npmjs.com/advisories/886

## Causes
Both versions of fstream are not recent enough

\node_modules\fstream\package.json
  "_from": "fstream@>= 0.1.30 < 1",
  "_id": "fstream@0.1.31",

\node_modules\bower\lib\node_modules\fstream\package.json
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me/)",
  "name": "fstream",
  "description": "Advanced file system stream things",
  "version": "1.0.11",

https://npmjs.com/advisories/886

Versions of fstream prior to 1.0.12 are vulnerable to Arbitrary File Overwrite. Extracting tarballs containing a hardlink to a file that already exists in the system and a file that matches the hardlink will overwrite the system's file with the contents of the extracted file. The fstream.DirWriter() function is vulnerable.

Remediation
Upgrade to version 1.0.12 or later.

## Versions
  - Authoring Tool Version: 0.9.0
  - Framework Version: 2.4.0
  - Node.js Version: v10.16.3
  - MongoDB Compass Community Version: 1.19.6
  - Operating System: Windows 10
  - Browser: Chome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by oliverfoster** [comment]
Please add these sub items to your original issue. They are the same issue and you have yet to respond to my original message.
