### ISSUE TITLE
Failed to build the web application

### ISSUE THREAD

**Issue by MakD** [adaptlearning/adapt_authoring#2431]
## Issue
Went through `npm install --production,` and `node install`, updates the plugins, creates master tenant and then fails. 

## Error Message
Failed to build the Web Application , (1)
Install will continue. Try again after installation completes using `grunt build:prod`
Install was unsuccessful. Please check the console output

## Running `grunt build:prod`
1. Fatal error in less.compile
2. timed out in connecting to fonts.googleapis.com

## Versions
  - Authoring Tool Version: 0.8.0
  - Node.js Version: LTS v10

**Comment by taylortom** [comment]
Hi, is this still an issue? I noticed you've been active in the Gitter chat.

**Comment by MakD** [comment]
Closing this Issue. Solved by commenting out the font import line in fonts.less, and re-building the application. Huge thanks to samumist (Zheng Xu) from glitter for helping me sort this.
