### ISSUE TITLE
preview error 

### ISSUE THREAD

**Issue by elbill** [adaptlearning/adapt_authoring#2432]
I am a new user. I have come up with issues before being able to use adapt authoring. Apologies if I'm missing basic knowledge.

## Expected Behaviour
I have a fresh installation on Ubuntu 18.04 LTS. Have been very careful and I'm pretty sure I installed properly all the required software.
Shows the same behaviour on a windows 10 installation.
I cant get it to preview. I get a pop up window with an error

![Screenshot_2019-09-17 Adapt authoring tool(1)](https://user-images.githubusercontent.com/23246886/65045915-51942400-d968-11e9-87f9-88a8efd075f4.png)

to replicate the issue I:
create a new empty course
add a submenu
try to preview

same error when trying to export
same error when trying to publish course with the difference that eventually you get the zip file.
no error in the server console

## Versions
  - Authoring Tool Version: current version
  - Framework Version: 4.3.0
  - Node.js Version: 8.10.0 (have tried newer versions with no luck)
  - MongoDB Version: current version
  - Operating System: ubuntu 18.04, have also tried windows 10 with exactly the same results
  - Browser: chrome, safari , opera, edge

I hop this is fixable as adapt seems to be a great tool. Thanks

**Comment by taylortom** [comment]
You're seeing that error because you've got a menu with no child items. You need to go into that menu and add items (e.g. a page).

**Comment by elbill** [comment]
thanks. I figured it our.
