### ISSUE TITLE
Asset tags are not preserved on import

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2439]
## Expected Behaviour
If I export a course which contains assets that have tags then the imported assets should have the same tags.

## Actual Behaviour
The imported assets do not have any tags.

## Steps to Reproduce
1. Create a course which contains an asset which has a tag
1. Export the course. In the assets.json you will be able to see the tag
1. Import the course. The imported asset will not have any tags.

The problem is with the import side rather than the export side. In importsource.js there is an addAssets function which contains line `var tags = formTags.slice();` I believe this is the problem.

## Versions
  - Authoring Tool Version: 0.10.0
  - Framework Version: 4.3.0

**Comment by dancgray** [comment]
@canstudios-nicolaw do you have an example of how to reproduce? I can see why you might be getting the issue but TBH cannot reproduce it myself. I have made a change [here](https://github.com/adaptlearning/adapt_authoring/commit/ebd70064ba5a17f509fea551dfb38a2c3edc04cc) that might fix it.

**Comment by canstudios-nicolaw** [comment]
@dancgray It looks to me like it's a race condition, I had the issue every time but perhaps I was just unlucky! I think this fix might work - I will give it a test now.

**Comment by canstudios-nicolaw** [comment]
@dancgray Yes that has worked :) Please could you PR it and we will get it in 0.10.2
