### ISSUE TITLE
Install script hangs when installing legacy framework

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2457]
## Expected Behaviour

Install script completes successfully when installing framework 2.4.0.

## Actual Behaviour

Install script hangs on:
```console
/ Updating Adapt framework plugin 'adapt-contrib-vanilla'
```

## Steps to Reproduce
1. `node install`

## Versions
  - Authoring Tool Version: 0.10.1
  - Framework Version: 2.4.0

**Comment by gtknowledgeshare** [comment]
Just ran into the same problem.

**Comment by gtknowledgeshare** [comment]
choosing the latest Adapt Framework version `tags/v4.4.1` worked.
