### ISSUE TITLE
Non-standard email addresses are allowed during installation.

### ISSUE THREAD

**Issue by fkcailiniyazi** [adaptlearning/adapt_authoring#2461]
## Expected Behaviour
Non-standard email addresse is not allowed.
## Actual Behaviour
We can set up user with Non-standard email addresse. Email addresse like _a.maimaiti  @ fkc.  com_ is accaptable. 
## Steps to Reproduce
1. Install node dependencies
2. Set up user with Non-standard email addresse

## Versions
  - Authoring Tool Version:  0.10.1
  - Framework Version: 2.4.0

![bug1](https://user-images.githubusercontent.com/54360982/67863707-b1174f00-fb24-11e9-9fcd-16bbf07e39d2.png)

**Comment by amaimaiti** [comment]
I think we should add email validation at **\plugins\auth\local\index.js**.

**Comment by tomgreenfield** [comment]
Internally, we actually tend to not use an email address as the super user's username. Suggest this is parked for now and included in the server rewrite if desired.
