### ISSUE TITLE
Using adapt with limesurvey project

### ISSUE THREAD

**Issue by gmisterk** [adaptlearning/adapt_authoring#2475]
Hi,

Is there any way to use Adapt with limesurvey project : http://limesurvey.org/

**Comment by moloko** [comment]
hi @gmisterk as this is a question rather than a feature request or a bug report please could you ask it in the [Adapt Community Forums](https://community.adaptlearning.org/mod/forum/view.php?id=4), ideally providing more detail about how exactly you envisage using it with Adapt.
