### ISSUE TITLE
Export source code of button missing

### ISSUE THREAD

**Issue by gmisterk** [adaptlearning/adapt_authoring#2476]
hi everybody,
I want to export a course (scorm) for Moodle
I don't see 'download', i have only a "export source' button. this download don't give me a correct scrom format for importation to moodle. 

Error in moodle : error/cannotdeletemoduleinstance

- adapt-spoor is active

thank you for any help

**Comment by tomgreenfield** [comment]
I suggest having a read of the revlevant [documentation](https://github.com/adaptlearning/adapt_authoring/wiki/Creating-a-Course#viewing-your-course).

Specifically:

> ### Publish (download)
>This function builds your course, and packages it as a zip file to download to your computer.<br>
If you've enabled the Spoor extension, the downloaded package will be SCORM 1.2 conformant, ready for uploading to the Learning Management System of your choice.<br>
If you are not using Spoor/SCORM, the contents of the zip file will need to be uploaded to (and run from) a web server.

**Comment by gmisterk** [comment]
thanks
it's publish button (and not export)
