### ISSUE TITLE
Option to customise the 'contact support' message with details of who to contact

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_authoring#2477]
## Affected Area
Reset password:
![contact support](https://user-images.githubusercontent.com/1249597/68781704-12b0e080-0630-11ea-858e-824cd91325b1.PNG)

## Requested Feature
Allow for the 'Contact support for help with restoring access to your account' message to be amended to include contact details. Perhaps during installation it could ask for details to be included here?
## Use Case
A course creator is locked out but does not know who to contact, they therefore assume it should be adaptlearning.org
## Current Workaround
I have to explain to them that the Adapt Learning Org does not manage any instances of the Adapt Authoring tool and that they need to get in touch with whoever set up/manages their AAT installation. This has happened at least three times in the past year and is only likely to increase.

**Comment by taylortom** [comment]
This would be a nice quick win.
