### ISSUE TITLE
Incompatible versions of plugins are targetted if range specified in adapt.json

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2479]
## Expected Behaviour

Targetted plugin versions are compatible with the installed version of the framework.

## Actual Behaviour

Installing the latest version of the framework (4.4.1) targets plugins only compatible with the upcoming framework 5 release and errors out like the below:
```console
Failed to install adapt-contrib-vanilla, Unable to install adapt-contrib-vanilla (undefined) as it is not supported in the current version of the Adapt framework (4.4.1)
```
Offending code:
https://github.com/adaptlearning/adapt_authoring/blob/859227bcbde3090b04735ccbda00c096d88996f0/lib/installHelpers.js#L585-L589

We should be able to always call `installLatestCompatibleVersion`, ignoring the incomplete range dependencies in `adapt.json`. The `installPlugin` method doesn't recursively check backwards for compatible versions.

## Steps to Reproduce
1. `node install`

## Versions
  - Authoring Tool Version: 0.10.2
  - Framework Version: 4.4.1

**Comment by oscarsiles** [comment]
I am also currently experiencing this - the changes in the adapt_framework project don't seem to have fixed it.
