### ISSUE TITLE
Hide Block Title by default

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2481]
## Affected Area

Creating blocks

## Requested Feature

Remove block Display Titles from showing on block creation.

## Use Case

Block titles are much less used then component titles. It makes sense they should be removed by default.

## Current Workaround

Going into every single block and deleting the Block Title attribute (slowing down course build).

**Comment by tomgreenfield** [comment]
The authoring tool now uses the [schema](https://github.com/adaptlearning/adapt_framework/blob/455d487675a48dc55a685b4988bb4d223b84d70d/src/core/schema/block.model.schema#L26) bundled with the framework. Suggest an issue is raised there if further action is needed.
