### ISSUE TITLE
It should be possible to run the upgrade script and skip installing latest node dependencies

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2498]
Each time the upgrade script is run it installs the latest node dependencies for both the authoring tool and the framework. 

It would be good if the upgrade script had the option to run without updating the node dependencies to reduce the testing time for managed systems.

There should be a new flag which can be passed to the upgrade script which skips the dependencies install. If the flag is not specified then the upgrade script will continue to work as it does now.

---

The installHelpers.js file contains a function `installDependencies` which is run for both the AT and FW. It removes the node_modules folder and runs npm install. I would hope it would be a case of skipping this function call if the option is set on the upgrade script. This may be an 'advanced' option - it is up to the person running the script to determine whether an npm install is required (eg new dependencies have been added) or not.

**Comment by tomgreenfield** [comment]
I believe this has been made redundant by #2505.
