### ISSUE TITLE
Source code placed in body tag is lost on redit

### ISSUE THREAD

**Issue by daledesilva** [adaptlearning/adapt_authoring#2517]
## Expected Behaviour
In a component, if _source_ is clicked in the body field  and html directly entered, the field should automatically default to show source the next time the component is edited.

## Actual Behaviour
When the component is re-edited, the body text field defaults to standard text editor and erases any source that was entered previously (or any source it can't interpret?).

## Steps to Reproduce
1. Create a Text component
2. In the text component, in the body field, click the _source_ button.
3. Paste in some generated code from here: https://lottiefiles.com/web-player
4. Save the component and note that the code works both in the editor and in preview.
5. Edit the component again and note that the body text is empty.
6. Click source and note that the body source is empty.
7. Click save component and note that the body field is overwritten as blank.

## Versions
  - Authoring Tool Version: 0.10.3
  - Framework Version: ??
  - Node.js Version: 14.4.0
  - MongoDB Version: 64_2012plus4.2.7
  - Operating System: Windows 10
  - Browser: Chrome

**Comment by tomgreenfield** [comment]
This is as-designed – the WYSIWYG editor [CKEditor](https://ckeditor.com) strips most HTML by default to minimise XSS vulnerabilities.

You might need to create a custom component for the Adapt framework to embed what you are looking at. There are always developers happy to answer any queries over on [Gitter](https://gitter.im/adaptlearning/general_chat) or the [forum](https://community.adaptlearning.org/mod/forum/view.php?id=4).
