### ISSUE TITLE
Reset not working

### ISSUE THREAD

**Issue by rakeshkumar749** [adaptlearning/adapt_authoring#2518]
### Subject of the issue/enhancement/features
"Reset when revisited?" drop down selection is not retained. after selecting soft or hard, drop down reset to false when come back to component and while previewing the course mcq is not reset when come back to page. please check this issue.

### Your environment
Adapt framework 5.6.0
adapt authoring 0.10.3
all
win10

### Steps to reproduce
select drop down "Reset when revisited?" to soft and hard, then save it and come back to component and its value changed to "false" automatically.

### Expected behaviour
it should retain the value which was selected, soft or hard.

### Actual behaviour
it is reseting every time to false.

**Comment by moloko** [comment]
@rakeshkumar749 this is an authoring tool bug so I have moved this to the authoring tool repository.

I can also confirm that I can replicate this issue in AAT v0.10.3/FW 5.5.1, if I select 'hard' in the dropdown:
![image](https://user-images.githubusercontent.com/1249597/85281111-5babfb80-b481-11ea-88e2-c4f74aee9906.png)
then save and go back in and it just resets to 'false':
![image](https://user-images.githubusercontent.com/1249597/85281228-86964f80-b481-11ea-929b-dfa1d598d797.png)

i believe @tomgreenfield has plans to look into this shortly
