### ISSUE TITLE
contentObjects sequence isn't proper in import and export

### ISSUE THREAD

**Issue by cksachdev** [adaptlearning/adapt_authoring#2538]
### Export scenario:
Pre-condition:
Create a course with 2 menu items, like below:
![image](https://user-images.githubusercontent.com/37770/91160247-c5958b00-e6e6-11ea-9fcf-ec47ae53b8bd.png)
![image](https://user-images.githubusercontent.com/37770/91160263-cc240280-e6e6-11ea-8445-ffba3250ec22.png)
Each page having just one text component.

Steps:
- Preview the course and check the sequence of `Adapt.contentObjects._byAdaptID`
- ```_.map(Adapt.contentObjects._byAdaptID, (co, key) => console.log(co[0].attributes.displayTitle) );```
Title should print in a sequence like below:
```
Parent1
Parent1 - Page1
Parent2
Parent2 - Page1
Parent2 - Page2
```
## Actual Behaviour
Sequence of contentObjects isn't proper, printing displayTitle for _byAdaptID prints like
```
Parent1 - Page1
Parent2 - Page1
Parent1
Parent2 - Page2
Parent2
```
![image](https://user-images.githubusercontent.com/37770/91160977-b8c56700-e6e7-11ea-8d86-268f39741ce3.png)

Same is reproducible when trying to import a course which contains menu and page in contentObjects. 

## Versions
  - Authoring Tool Version: 0.10.4
  - Framework Version: v5.2.0
  - Node.js Version: v14.7.0
  - MongoDB Version: v4.4.0
  - Operating System: macOS Catalina (10.15.6)
  - Browser: Chrome 84

**Comment by tomgreenfield** [comment]
> * `_.map(Adapt.contentObjects._byAdaptID, (co, key) => console.log(co[0].attributes.displayTitle) );`
Title should print in a sequence

This arguably _shouldn't_ be the case. The private `_byAdaptID` property just groups models by their ID. It cannot be replied upon to get an indication of the course structure, either with automatically-generated IDs from the authoring tool or with hand-typed IDs in JSON.

If you told us a bit about the problem you're trying to solve we could advise further with a solution.

For example, to print a sorted list of content object titles in a framework 5.2 course, you could utilise the following code:
```js
Adapt.course.getAllDescendantModels(true).forEach(function(model) {
  var type = model.get('_type');
  if (type === 'menu' || type === 'page') {
    console.log(model.get('displayTitle'));
  }
});
```

This gets easier in an upgraded framework (version 5.5 or later):
```js
Adapt.course.getAllDescendantModels(true).forEach(model => model.isTypeGroup('contentobject') && console.log(model.get('displayTitle')));
```

**Comment by cksachdev** [comment]
@tomgreenfield I have created a footer navigation component, which should allow the user to navigate to "Next", "Back" and "Go back to main menu". In order to achieve this, I needed the sequence of data in the order I am expecting.
```
Parent1
Parent1 - Page1
Parent2
Parent2 - Page1
Parent2 - Page2
```
I will try out the getAllDescendantModels method and let you know if it gives me the right sequence.
