### ISSUE TITLE
correct answer button not active on revisit

### ISSUE THREAD

**Issue by rakeshkumar749** [adaptlearning/adapt_authoring#2539]
## Expected Behaviour
on revisit, the "Correct Answer" buttons should be active on MCQ/MMCQ. if MCQ is "False" on drop down for revisit.
## Actual Behaviour
on revisit the mcq/mmcq, "Correct Answer" button is not active.
## Steps to Reproduce
1. attempt MCQ/MMCQ and go to menu or other page
2. come back on page where MCQ/MMCQ already attempted
3. Not able to check "My Answer" and "Correct Answer" buttons.

## Versions
  - Authoring Tool Version: 0.10.4
  - Framework Version: 5.7.1
  - Node.js Version: 12.17.0
  - MongoDB Version:6.14.4
  - Operating System: windows 10
  - Browser: Chrome, Edge, Firefox

**Comment by moloko** [comment]
this is an issue with the framework, not the authoring tool. sounds a lot like https://github.com/adaptlearning/adapt_framework/issues/2825
