### ISSUE TITLE
Users can change the passwords of other users

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2540]
It seems that when you create additional accounts on the latest version of the Authoring Tool they get shown the email address, first name and last name of another account. They can also change the password of this user!

## Steps to Reproduce

1. Admin account creates a new account
1. Log into the new account
1. Click on `logged in as: [new account]` to change the password
1. **The user is shown the details of another admin account.**
1. Change the password of the other admin account
1. The admin account cannot log in with their own password, but they can use this new password

## Versions
  - Authoring Tool Version: 0.10.4
  - Framework Version: 5.7.1

**Comment by deltanetdan** [comment]
I can reproduce this issue. Reversing [this](https://github.com/adaptlearning/adapt_authoring/pull/2516/) PR seems to fix the problem.

**Comment by moloko** [comment]
nice find @simondate

**Comment by moloko** [comment]
Looks like it gives you the account details of whoever created the account. Currently having lots of fun changing @guywillis password to random things ;-)
