### ISSUE TITLE
Linux permission error with jpegtran-bin

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2543]
This issue has been reported by on the forums by two different users ([1](https://community.adaptlearning.org/mod/forum/discuss.php?d=3929) [2](https://community.adaptlearning.org/mod/forum/discuss.php?d=3951)) so I thought it should probably be moved to a Github issue.

When doing of a fresh install of the AAT on Linux this issue seems to crop up. Always reporting an issue with just the NPM library jpegtran-bin, used in later versions of the FW. If you install an older version of FW (v5.3.0) it doesn't have any issues.

If the user tries to upgrade from an older version to a newer version the error message appears and cancels the install however when try to upgrade again or restart the server it says you are on the latest FW version (v5.7.1) see below.

<img width="685" alt="chrome_JsOpAIF5br" src="https://user-images.githubusercontent.com/1676635/100132870-ef915180-2e7d-11eb-8af6-e664be3f2a99.png">

<img width="681" alt="chrome_qMyWEqxX2y" src="https://user-images.githubusercontent.com/1676635/100133033-2a938500-2e7e-11eb-8225-b73bb9d5802b.png">

I also tried on Node version 12 (LTS) and the issue still persisted.

## Versions
  - Authoring Tool Version: Latest (0.10.3)
  - Framework Version: Latest (5.7.1)
  - Node.js Version: 14.14.0 & 12.20.0
  - Operating System: Debian 10 "Buster"

**Comment by moloko** [comment]
It's actually the Framework that's attempting to install jpegtran-bin (it's a dependency of imagemin-jpegtran) - pretty sure you'd get the same issue if attempting to do `adapt create course` on the same system. 

Any chance you could give that a try?

It's a tricky one cause really the issue lies with jpegtran-bin. All we can really do here is flag the issue to the developer of that npm package and/or take it out of the framework.

**Comment by moloko** [comment]
Possibly related? https://github.com/imagemin/imagemin/issues/256

**Comment by oliverfoster** [comment]
@simondate can you try installing with 

```js
  var child = exec('git checkout --quiet ' + frameworkRevision + ' && npm install --unsafe-perm=true --allow-root --loglevel error', {
```

at line https://github.com/adaptlearning/adapt_authoring/blob/e5d7b702695585021f406d54c979e393a163846c/lib/frameworkhelper.js#L55

**Comment by simondate** [comment]
@oliverfoster this still gives me the same error message.

**Comment by simondate** [comment]
@moloko I tried `adapt create course` and it installed fine and ran `grunt build` fine.

**Comment by islandtech** [comment]
@simondate We am running into the same issue.

**Comment by moloko** [comment]
@simondate @islandtech about to release FW v5.9.0 which we hope will solve this issue (also documented [here](https://github.com/adaptlearning/adapt_framework/issues/3002))

**Comment by taylortom** [comment]
@simondate does framework 5.9 fix this issue for you?
