### ISSUE TITLE
Course builds error about core plugins not being installed

### ISSUE THREAD

**Issue by unRARed** [adaptlearning/adapt_authoring#2546]
## Expected Behaviour

HTML containing one of a handful of component(s) should be rendered.

## Actual Behaviour

Loading animation never concludes.

## Steps to Reproduce
1. Create a course
2. Add either of these core components to it: `graphic`, `matching`, `mcq`, `gmcq`, `slider` (effectively, all the question/answer components. there's probably others with the same problem, but can personally confirm these)
3. Preview the course and navigate to where that component would render
4. Check dev tools, find error seemingly [from this adapt_framework code](https://github.com/adaptlearning/adapt_framework/blob/657fea688ffbc2ded888f882a514e443be4574fd/src/core/js/views/adaptView.js#L113)

<img width="1086" alt="Screen Shot 2021-02-13 at 2 17 37 PM" src="https://user-images.githubusercontent.com/1447940/107863102-46b41c00-6e06-11eb-8aa1-ae9d38cfaa6e.png">

Running `node upgrade` and specifying framework version `v5.9.0` appears to fix the `graphic` component but the other components still produce the same error. Maybe that one was only a false positive on my end.

## Versions
  - Authoring Tool Version: v0.10.5
  - Framework Version: v5.10.1
  - Node.js Version: v14.15.5
  - MongoDB Version: v3.6.8
  - Operating System: Ubuntu 19.10 server-side, MacOS 10.15.7 client-side
  - Browser: Brave (chromium 88.0.4)

**Comment by taylortom** [comment]
Apologies no one's gotten back to you about this @unRARed, is this still an issue?

**Comment by unRARed** [comment]
I ended up busy with other projects. I'll reopen if/when I'm able to get back to it. Thanks!
