### ISSUE TITLE
Forgot password option missing

### ISSUE THREAD

**Issue by barryjenkin** [adaptlearning/adapt_authoring#2550]
On AT login page, after making 3 unsuccessful login attempts, an alert appears saying my account is locked and I can unlock it by clicking the 'Forgotten your password?' button .. except there isn't one. Just the reset option available to super admins. Is this still to come or something I should be enabling during install?

**Comment by tomgreenfield** [comment]
Hi @barryjenkin, you need to have [SMTP](https://github.com/adaptlearning/adapt_authoring/wiki/Setting-up-SMTP) set up for the reset password email functionality to be enabled.

**Comment by fkcailiniyazi** [comment]
Hi @barryjenkin, you should enable SMTP settings during the installation.
