### ISSUE TITLE
Post install issues

### ISSUE THREAD

**Issue by christianswanepoel** [adaptlearning/adapt_authoring#2560]
I have installed the framework and can login - but all pages are blank besides plugin management
Any advice?

<img width="1676" alt="Screenshot 2021-05-11 at 16 11 33" src="https://user-images.githubusercontent.com/7249713/117832643-f4a05c80-b275-11eb-9067-242809ac6aae.png">

Startup log:
info [11 May 21 14:05:17 +00:00] configuration loaded from /home/adapt_authoring/conf/confi
g.json
info [11 May 21 14:05:17 +00:00] Supporting the following authentication types:
info [11 May 21 14:05:17 +00:00] - local
info [11 May 21 14:05:17 +00:00] Connection established: adapt-tenant-master
info [11 May 21 14:05:17 +00:00] Adapt authoring tool 0.10.5.
info [11 May 21 14:05:17 +00:00] Adapt framework 5.13.0.
info [11 May 21 14:05:18 +00:00] Server started listening on port 5000

- Reproducible on all browsers
- Node.js v14.16.1.
- Debian/ Ubuntu bullseye/sid
- mongod.service (running and enabled)

**Comment by riffnshred** [comment]
First time user here and same issue but on MacOS Mojave ! 

I'm not sure if this is useful but after running `npm install --production`, a bunch of dependencies had vulnerabilities. I ran `npm audit fix` and then `npm audit fix --force` and there are still some vulnerabilities that can't be fixed. 

See the log here: https://pastebin.com/gYCLS85b

**Comment by oliverfoster** [comment]
That comment is somewhat unfair don't you think? A small group of volunteers building a bit of software in a pandemic at the beginning of summer/winter.

Do you know how to debug node applications or browsers? Are there any console logs in the browser?

@riffnshred You can effectively ignore the vulnerability notices, the chances of the library being used in the very specific way the vulnerability is expressed are tiny and messing with the dependencies will probably cause you more issues than they'll solve. You're effectively updating a load of dependencies and then asking why the wider application doesn't work.

**Comment by christianswanepoel** [comment]
Apologies if I offended. 
I work on many small projects, but not used not getting any response, even with 2 confirmed cases and 17 days ago. I appreciate you taking the time to assist.

My errors:
1) Node doesn't log anything when clicking links, or startup errors
2) Browser console logs a 403 for /api/role, /api/tenant and 500 for /api/autocomplete/tag after login.
3) The 500 recourse non every site link

**Comment by riffnshred** [comment]
> Have you got your server running yet?

Not yet. I didn't poke around it much since then. 

@oliverfoster Im just following instruction right from the documentation and recommendation from the CLI. Got those errors popped, thought that might help with fixing the issue. Like I said, First timer here.

**Comment by christianswanepoel** [comment]
@riffnshred could you see if you get the same browser console errors as I do?

**Comment by riffnshred** [comment]
> @riffnshred could you see if you get the same browser console errors as I do?

yup exact same. 

I can't do much testing today, but did you have to use sudo for any commands at some point? I don't think I did on my end but the 403 errors sounds like access right issues.

**Comment by tomgreenfield** [comment]
> messing with the dependencies will probably cause you more issues than they'll solve

Please stick to the dependencies defined already; these are the ones that are tested and supported for production. I'm aware, for example, that any upgrade to the mongoose library will break the app.

**Comment by christianswanepoel** [comment]
@tomgreenfield so you saying I must reinstall and not update any dependancies and it might fix the issue?
(I am quite sure it failed to launch the app when I tried that)

**Comment by riffnshred** [comment]
Just reinstalled and that was it. All good now on my end. 

Thanks for the help.

**Comment by christianswanepoel** [comment]
Not as lucky:
Tried installing on Ubuntu 20 and 18 and CentOS 7 with Ubuntu 20 getting the closest, but no cigar :(

**Comment by oliverfoster** [comment]
Cool. In that case, I'll endeavour to spin up a VM on Tuesday and report back

**Comment by christianswanepoel** [comment]
@oliverfoster I can supply you a AWS server if it will help.

**Comment by christianswanepoel** [comment]
It seemed to work (I got one more line per screen in Gui) but then it went back to not working.
Seems to error on "Error: Failed to determine user's tenant!"

See logs:
```
sudo node server
info [02 Jun 21 09:04:44 +00:00] configuration loaded from /home/adapt_authoring/conf/config.json
info [02 Jun 21 09:04:44 +00:00] Supporting the following authentication types:
info [02 Jun 21 09:04:44 +00:00] - local
info [02 Jun 21 09:04:44 +00:00] Connection established: adapt-tenant-master
info [02 Jun 21 09:04:45 +00:00] Adapt authoring tool 0.10.5.
info [02 Jun 21 09:04:45 +00:00] Adapt framework 5.13.0.
info [02 Jun 21 09:04:45 +00:00] Server started listening on port 80
Error: Failed to determine user's tenant!
    at Object.getDatabase (/home/adapt_authoring/lib/database.js:416:19)
    at /home/adapt_authoring/plugins/content/tag/index.js:76:16
    at /home/adapt_authoring/lib/rest.js:115:7
    at Layer.handle [as handle_request] (/home/adapt_authoring/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/adapt_authoring/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/adapt_authoring/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/adapt_authoring/node_modules/express/lib/router/layer.js:95:5)
    at /home/adapt_authoring/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/adapt_authoring/node_modules/express/lib/router/index.js:335:12)
    at next (/home/adapt_authoring/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/home/adapt_authoring/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/adapt_authoring/node_modules/express/lib/router/index.js:317:13)
    at /home/adapt_authoring/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/adapt_authoring/node_modules/express/lib/router/index.js:335:12)
    at next (/home/adapt_authoring/node_modules/express/lib/router/index.js:275:10)
    at /home/adapt_authoring/lib/permissions.js:495:16
    at Layer.handle [as handle_request] (/home/adapt_authoring/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/adapt_authoring/node_modules/express/lib/router/index.js:317:13)
    at /home/adapt_authoring/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/adapt_authoring/node_modules/express/lib/router/index.js:335:12)
    at next (/home/adapt_authoring/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/adapt_authoring/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.EventEmitter.emit (domain.js:467:12)
    at SendStream.error (/home/adapt_authoring/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/adapt_authoring/node_modules/send/index.js:421:12)
    at next (/home/adapt_authoring/node_modules/send/index.js:735:16)
```

**Comment by oliverfoster** [comment]
@christianswanepoel it's really difficult when you don't answer my questions.

**Comment by christianswanepoel** [comment]
@oliverfoster the answer is yes - I assumed it was obvious as I stated I was in the GUI, also the logs included are from GUI interaction. To be clear GUI post login.

**Comment by oliverfoster** [comment]
Stupendous. I'll have a conversation with someone in the AAT team and let them know, that bit of the installer seems to be falling over because of a bug in the way child_process.exec works for some reason.

**Comment by oliverfoster** [comment]
I'm closing this for now as your immediate issue is fixed.

**Comment by christianswanepoel** [comment]
Thank you for your time. 
Yeah also it might be worth adding that some parts should be run as root/sudo (it seems)

**Comment by oliverfoster** [comment]
I don't think the sudo is required, it's just a coincidence here. I went through a session of testing different types of permissions relative to the locations of node and grunt-cli yesterday and the impact seemed mostly negligible.
