### ISSUE TITLE
Links not opening in popup window anymore

### ISSUE THREAD

**Issue by jayseventwo** [adaptlearning/adapt_authoring#2570]
## Expected Behaviour
Hi guys, we've discovered a possible new issue where text links set to open in a popup window no longer function correctly - they just go to the linked page in the same window as the course.

What is weird is if you click the links from within the Adapt author Tool back-end (where you can see them in the text area) they function correctly.

I've attached some screenshots to show that the popup JS "onclick" code no longer seems to get added to the link. I've also attached an error message we are now seeing in Chrome when clicking links.

I've also taken some screenshots to show you the back-end settings (which have always worked up until now).

## Actual Behaviour
When clicking a text link, the link opens in the same window as the course.

## Steps to Reproduce
Add a text link within a text component, preview /publish and click.

## Versions
Adapt authoring tool 0.10.5.

 Adapt framework v5.16.0

Note: the issue was actually first encountered by a team member running  Adapt framework v5.17.1 - I have yet to upgrade, but imported a course built in this version.

Chrome Version 94.0.4606.81 (Official Build) (64-bit) - also tested in firefox.

Node V14.17.5
![01 Link how it looks now](https://user-images.githubusercontent.com/3916665/137404307-5a1ebf73-2de4-465c-80e5-9e5a090288ad.jpg)
![02 Link how it should look](https://user-images.githubusercontent.com/3916665/137404312-5155d8a6-a310-44bc-a177-82922bbf30f6.jpg)
![03 Errror message when clicking link](https://user-images.githubusercontent.com/3916665/137404314-3687ee4e-ce6a-4c73-8fe8-74bc459d1281.jpg)
![04 Link works correctly from Author Tool backend](https://user-images.githubusercontent.com/3916665/137404316-9f4af3a9-cd9c-4561-8489-e2ab26bac6e6.jpg)
![05 Backend settings 01](https://user-images.githubusercontent.com/3916665/137404319-b278b0df-87a8-4e81-bfe7-9c71bd8a30a4.jpg)
![06 Backend settings 02](https://user-images.githubusercontent.com/3916665/137404321-101c4eb8-791e-4b87-9171-5fb83902a757.jpg)
![07 Backend settings 03](https://user-images.githubusercontent.com/3916665/137404322-22730057-c2a6-4335-9189-f156f7429cc5.jpg)

**Comment by jayseventwo** [comment]
I've also found that if the link works okay in a course, and then you publish to SCORM and then try to preview it again from the Author Tool, the link doesn't work correctly.

**Comment by jayseventwo** [comment]
Thanks, Simon. I've updated that line in "routes/index/index.hbs", and I can see the new editor version in the back-end, but the links still do not open in a popup window. I ran "grunt build" on the "adapt_authoring" folder - is that correct?

I've also tried running localhost in an Incognito browser, in case there were caching issues, but still no joy.

Appreciate your help on this - we have a number of courses ready to publish but are waiting for this issue to be resolved.

As an FYI, I've now updated my AT to 0.10.5, and the AF to 5.17.2. and have confirmed that line of code is still correct.

Edit: I've also just installed a fresh copy of the author tool etc. on a different PC, updated that code line and run "grunt build", but the link still opens in the same window.

**Comment by jayseventwo** [comment]
Hi Simon, I've just discovered that the popup does actually work at the page level text box, but does not if added to a component (in this case, a text box component).
![2021-10-21_13-20-35](https://user-images.githubusercontent.com/3916665/138200198-a16c38c9-4c4c-464d-993e-92c197777f05.png)

**Comment by jayseventwo** [comment]
Hi guys, just tested this and it looks like all is fixed now! Thanks again for looking into it - much appreciated.

**Comment by oliverfoster** [comment]
thanks @jayseventwo , great help

**Comment by taylortom** [comment]
This was released with [adapt_framework@5.17.5](https://github.com/adaptlearning/adapt_framework/releases/tag/v5.17.5)
