### ISSUE TITLE
upgrade node.js causing errors when trying to publish/rebuild courses

### ISSUE THREAD

**Issue by jayseventwo** [adaptlearning/adapt_authoring#2572]
## Expected Behaviour
Running node upgrade.js breaks the Author Tool.

## Actual Behaviour
When I run "node server", I got the message to run node upgrade.js.

After running that, I get the following error:

---

$ node upgrade.js
(node:10824) Warning: Accessing non-existent property 'count' of module exports
inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10824) Warning: Accessing non-existent property 'findOne' of module export
s inside circular dependency
(node:10824) Warning: Accessing non-existent property 'remove' of module exports
inside circular dependency
(node:10824) Warning: Accessing non-existent property 'updateOne' of module expo
rts inside circular dependency

This script will update the Adapt authoring tool and/or Adapt Framework. Would y
ou like to continue?
? Continue? Yes
? Update automatically? Yes

Software updates found.

\temp\6170907a135eb321607d03be\adapt_framework switched to revision v5.17.3
Failed to upgrade \temp\6170907a135eb321607d03be\adapt_framework to v5.17.3
ERROR: error: pathspec 'v6.0.3' did not match any file(s) known to git
child_process.js:866
throw err;
^

Error: Command failed: git checkout v6.0.3
at checkExecSyncError (child_process.js:790:11)
at Object.execSync (child_process.js:863:15)
at Object.<anonymous> (C:\Users\User\Desktop\test\adapt_authoring\temp\61709
07a135eb321607d03be\adapt_framework\gitmodules.js:67:16)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:76:12)
at internal/main/run_main_module.js:17:47 {
status: 1,
signal: null,
output: [ null, null, null ],
pid: 13464,
stdout: null,
stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adapt_framework@5.17.3 preinstall: `node gitmodules.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adapt_framework@5.17.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-10-24T21_42_34_9
39Z-debug.log

Upgrade was unsuccessful. Please check the console output.

---

Now when I run node server, no upgrades are mentioned, yet when I try to rebuild to preview or publish a course, I get the following error:

Command failed: grunt server-build:prod --outputdir=courses\6170907a135eb321607d03be\61709114dc4d1e3b401c6a7d\build --theme=617090ee135eb321607d03d9 --menu=adapt-contrib-boxMenu

---

I have tried this on two separate installs on two different PC's, both with the same issue.

## Steps to Reproduce
Run node upgrade.js
Upgrade fails
Run node server
Log in to localhost and rebuild a course, or publish
Fails with error message (see above)

## Versions
  - Authoring Tool Version: 0 10.5
  - Framework Version: 5.17.3 ( I think - whatever the latest is, as I have had to revert to 5.17.1 to get everything to work again).
  - Node.js Version:
  - MongoDB Version:
  - Operating System: Windows 10 Pro 21H1
  - Browser: Chrome 95.0.4638.54

**Comment by oliverfoster** [comment]
I've added to the code to make it backward compatible. 

References: 
* https://nodejs.org/api/fs.html#fsrmsyncpath-options 
* https://nodejs.org/api/fs.html#fsrmdirsyncpath-options
* https://github.com/adaptlearning/adapt_framework/pull/3253/commits/ebfbd544473f4fde84d33ee38ad332f611bb9af8

**Comment by polymurphic** [comment]
@oliverfoster - I switched to node 14 with nvm and a clean install of AUT went fine to the issue tag version.
The only problem i have with running node >12 is this error when starting the server:
(node:54427) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54427) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:54427) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:54427) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
info [01 Nov 21 10:46:36 +10:30] configuration loaded from /Users/timcavanagh/adapt_authoring_5/adapt_authoring/conf/config.json

This does not occur with node 12.x.x.

Apart from the issue above related to node 14 the fix is working fine, I imported a course and edited and created pages, blocks etc.

**Comment by oliverfoster** [comment]
Cool. Could you make a separate ticket for this new bug? I'm a framework development myself so it's a bit out of scope for me.

**Comment by jayseventwo** [comment]
Sorry guys, I've been a bit out of the loop about this issue due to some personal family issues - is it now fixed, as I am still getting errors when trying to runing "node upgrade,js" (please see output see below).

$ node upgrade.js
(node:2012) Warning: Accessing non-existent property 'count' of module exports i
nside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2012) Warning: Accessing non-existent property 'findOne' of module exports
 inside circular dependency
(node:2012) Warning: Accessing non-existent property 'remove' of module exports
inside circular dependency
(node:2012) Warning: Accessing non-existent property 'updateOne' of module expor
ts inside circular dependency

This script will update the Adapt authoring tool and/or Adapt Framework. Would y
ou like to continue?
? Continue? Yes
? Update automatically? Yes

Software updates found.

\temp\6170907a135eb321607d03be\adapt_framework switched to revision v5.17.7
Failed to upgrade \temp\6170907a135eb321607d03be\adapt_framework to v5.17.7
ERROR: From https://github.com/adaptlearning/adapt-contrib-core
 - [deleted]         (none)     -> origin/ADAPT-8394-issues-with-fillintheblanks
-attempts-remaining-on-page-reload
 - [deleted]         (none)     -> origin/issue/2967-b
 - [deleted]         (none)     -> origin/issues/2973
error: Your local changes to the following files would be overwritten by checkou
t:
        js/fixes.js
        js/reactHelpers.js
        templates/header.jsx
Please commit your changes or stash them before you switch branches.
error: The following untracked working tree files would be overwritten by checko
ut:
        js/fixes/reactHelpers.html.js
Please move or remove them before you switch branches.
Aborting
child_process.js:866
    throw err;
    ^

Error: Command failed: git checkout v6.0.5
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at Object.<anonymous> (C:\Users\User\Desktop\test\adapt_authoring\temp\61709
07a135eb321607d03be\adapt_framework\gitmodules.js:87:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:76:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5152,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adapt_framework@5.17.7 preinstall: `node gitmodules.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adapt_framework@5.17.7 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-11-14T21_44_15_1
18Z-debug.log


Upgrade was unsuccessful. Please check the console output.

---

I've also attached the log output file.

Thanks!

[2021-11-14T21_44_15_118Z-debug.log](https://github.com/adaptlearning/adapt_authoring/files/7534748/2021-11-14T21_44_15_118Z-debug.log)

**Comment by polymurphic** [comment]
Hmm seems like a different issue than the original issue i posted which related to

 fs.rmSync(dirPath, { recursive: true, force: true });

I see in your log that git is saying you have uncommitted changes - maybe you have made some changes?

**Comment by jayseventwo** [comment]
Hi Tim, this install is just a test Author Tool install I now use to make sure updates do not break the courses we have already built. I've not done anything other than create a basic one-page course, so unsure where I can look for an uncommitted change?

Just looking at the previous comments I now see I need to upgrade node and also make the required code changes from here: https://github.com/adaptlearning/adapt_framework/commit/ebfbd544473f4fde84d33ee38ad332f611bb9af8 

I'll try that when I get a chance.

Thanks

**Comment by crishood** [comment]
Hello I have this issue too, could you solve it?  I still getting this error when I try to previsualize my course 
Command failed: grunt server-build:prod --
