### ISSUE TITLE
Node v14.x warnings with mongodb driver

### ISSUE THREAD

**Issue by polymurphic** [adaptlearning/adapt_authoring#2578]
This related to the not fixed part of #2572

## Expected Behaviour
Warnings are being generated when running node 14.x with the current release of AUT.
Apparently the fix is to upgrade node modules mongodb and mongoose.
Reverting to node v12 prevents this problem but the recommendation is to use node v14 for the new framework upgrade process.
## Actual Behaviour
info [10 Nov 21 10:57:31 +10:30] Supporting the following authentication types:
info [10 Nov 21 10:57:31 +10:30] - local
(node:38222) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38222) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:38222) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:38222) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
info [10 Nov 21 10:57:31 +10:30] Connection established: adapt-tenant-master5
info [10 Nov 21 10:57:32 +10:30] Adapt authoring tool 0.10.5.
info [10 Nov 21 10:57:32 +10:30] Adapt framework 5.17.7.
info [10 Nov 21 10:57:32 +10:30] Server started listening on port 5000

## Steps to Reproduce
1. use node v14
2. Run node server for AUT

## Versions
  - Authoring Tool Version: 0.10.5
  - Framework Version: 5.17.7
  - Node.js Version: v14.18.1
  - MongoDB Version: 5.0.3
  - Operating System: Mac OS X 11.6.1
  - Browser: Chrome

**Comment by taylortom** [comment]
Will be fixed as part of https://github.com/adaptlearning/adapt_authoring/issues/2583
