### ISSUE TITLE
Support to install script without break to user input

### ISSUE THREAD

**Issue by joaogarcia-iteris** [adaptlearning/adapt_authoring#2579]
## Affected Area
Self-hosted App

## Requested Feature
Add support to input params on install's script.

## Use Case
Thia is a realy helpfull feature when use CI/CD tools 

## Current Workaround
Setup locally and deploy config files

## Additional Information
Here's an example:

```bash
node install --default --adminemail="xyz@bla.com" ...
```

And at install script read args:

```js
const [ deafult, adminemail ] = process.argv;

if (!default) {
  # ask for info
}

if (!adminemail ) {
  # ask for info
}
...
```

Helpfull link: https://nodejs.org/en/knowledge/command-line/how-to-parse-command-line-arguments/

Regards, JP

**Comment by taylortom** [comment]
Hi @joaogarcia-iteris, this is actually already possible.

```bash
node install --suEmail xyz@bla.com --suPassword ******** --suRetypePassword ********
```

You'll find a full list of the values in [install.js](https://github.com/adaptlearning/adapt_authoring/blob/master/install.js#L240-L262).

**Comment by joaogarcia-iteris** [comment]
Hi @taylortom, can this issue be add as new task to document this funcionality?

**Comment by joaogarcia-iteris** [comment]
I find it: https://github.com/adaptlearning/adapt_authoring/wiki/Configuring-the-Authoring-Tool#command-line-install-options
