### ISSUE TITLE
Server selection timed out

### ISSUE THREAD

**Issue by Papadzul** [adaptlearning/adapt_authoring#2601]
No luck on my installation
found this error all the time:

error [14 Jan 22 19:39:23 -07:00] Server selection timed out after 30000 ms
error [14 Jan 22 19:39:23 -07:00] failed to set app.db

**Comment by taylortom** [comment]
That's not an error message I've seen before. Could you please give a bit more context to the issue? (and maybe any other log messages around the error to help us in our understanding)

Thanks :smile:

**Comment by RobertPeek** [comment]
Hi @taylortom i've got this eror too when trying to install the latest version of the Authoring tool locally:

![image](https://github.com/adaptlearning/adapt_authoring/assets/7251995/f79d6728-1b16-4a29-afe7-d6965b9596b4)

I've followed all the steps outlined in the WIKI and MongoDB is running.

Any help would be greatly appreciated.

**Comment by oliverfoster** [comment]
Change config file dbhost field to 127.0.0.1
