### ISSUE TITLE
The ability to use ES6 in the frontend of the adapt authoring tool

### ISSUE THREAD

**Issue by koenignicolas** [adaptlearning/adapt_authoring#2613]
## Affected Area
Build process and frontend

## Requested Feature
The ability to use ES6 in the frontend of the Adapt authoring tool

## Use Case
As a developer I would like to use all the nice capabilities of ES6 also in the frontend of the Adapt authoring tool.

## Additional Information
Currently, if one uses ES6 in the frontend one gets an error in the build process. The issue is with the uglify task, which is part of the requirejs -> compilation step.
An easy fix would be to install npm package: grunt-contrib-uglify
and then in the Requirejs compliation set the property: optimize="none" 
and then add uglify as its own grunt task.

**Comment by taylortom** [comment]
This isn't something we're going to fix in the current authoring tool, but will be possible in v1.0.0 (see details on this release [here](https://github.com/adapt-security/adapt-authoring/discussions/419))
