### ISSUE TITLE
FW v5.19.x doesn't seem to work with the AAT

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2618]
## Expected Behaviour

I did a fresh install of the AAT and when I got to compile a course I got unspecified error message. I tried reinstalling it multiple times and other usual issue fixes like [this](https://github.com/adaptlearning/adapt_authoring/issues/2566)  and nothing happened.

It was only when I specified a non FW v5.19.X version (I tried 5.19.0 and 5.19.1) and tried 5.18.7 that worked.

## Steps to Reproduce
1. Do a fresh install of the AAT
1. Attempt to preview a course
1. An error is thrown at the build stage

![image](https://user-images.githubusercontent.com/1676635/163596182-21975763-41b4-4b37-b965-22c37b111a5b.png)

## Versions
  - Authoring Tool Version: 0.10.5
  - Node.js Version: 12.22.1
  - Operating System: Debian Buster (Unix)

**Comment by taylortom** [comment]
I've just tested this in the v0.11.0 branch and I can't replicate the issue there, and it's working for me there. Can you give that a test if you get a chance and let me know if you're still seeing issues :)

**Comment by simondate** [comment]
Hi @taylortom , I've tried with the latest 0.11.0 authoring tool and still getting issues with an AT I've upgraded to that version.

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/179503015-a1861533-4362-4131-9438-fb071bcd76c5.png)
theme has invalid handlebars

**Comment by simondate** [comment]
I think this error was caused as I was previously installing with `sudo` and it appears that was causing issues with npx. I have now changed the AAT to run without sudo (by chown-ing all the files) and I have been able to use later versions
