### ISSUE TITLE
Framework update doesn't update src/core

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_authoring#2628]
## Expected Behaviour
src/core should be deleted before running `installDependencies`
https://github.com/adaptlearning/adapt_authoring/blob/7ccd9915b5611e9e1fac0e9c7e4b700a38ee9613/lib/installHelpers.js#L467-L470

## Actual Behaviour
A git reset is performed, but this will not update src/core
https://github.com/adaptlearning/adapt_authoring/blob/7ccd9915b5611e9e1fac0e9c7e4b700a38ee9613/lib/installHelpers.js#L537

## Steps to Reproduce
1. update an AAT with a separated src/core

## Versions
  - Authoring Tool Version: current
  - Framework Version:  >=[5.17.0](https://github.com/adaptlearning/adapt_framework/releases/tag/v5.17.0)
  - Node.js Version: any
  - MongoDB Version: any
  - Operating System: any
  - Browser: any

**Comment by taylortom** [comment]
Will get this into the v0.11.0 release
