### ISSUE TITLE
Export build error using latest framework release

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#2637]
## Expected Behaviour
Should be able to build a FW v5.22.3 course exported from the authoring tool.

## Actual Behaviour
grunt build or dev fails with the following error

`Error: ENOENT: no such file or directory, open '.browserslistrc'

Warning: Task "javascript:compile" failed. Use --force to continue.`

Export REGEX is excluding all hidden file [here](https://github.com/adaptlearning/adapt_authoring/blob/release/v0.11.0/plugins/output/adapt/export.js#L66).

## Steps to Reproduce
1. Install FW v5.22.3 in the authoring tool
2. export a course
3. run npm install and build the course locally

## Versions
  - Authoring Tool Version: master or release/v0.11.0 branch
  - Framework Version: v5.22.3
  - Node.js Version: v14.19.3

**Comment by taylortom** [comment]
Yeah just come up against this one, seems we've always ignored all . files due to a default value in the zipping module we use
