### ISSUE TITLE
core `_globals._extensions`

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_authoring#2691]
The following objects are not displayed in the AAT UI, or included in the published _course.json_:
https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/course.model.schema#L337-L408

This causes rendering issues with the `_navOrder` added in https://github.com/adaptlearning/adapt-contrib-core/commit/a3db66fa35fc7c66ede4977cc401a92c29bb8a5d.

Other plugins successfully merge objects into `_globals._extensions` but anything included in core itself seems to be excluded. Unlike the namespace setup for extensions and components, the relevant objects for core should be merged directly into `_globals`.

**Comment by swashbuck** [comment]
@taylortom @danielghost Does this issue need to be closed? I saw that #2692 (linked to on this ticket) has been merged but this ticket is still open.
