### ISSUE TITLE
Force rebuild isn't run when new course is created

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2696]
## Expected Behaviour

When a new course is created and the author press Preview Course, a build command should be run to ensure that the files are available.

## Actual Behaviour

 At the moment when the learner presses Preview Course, the author only sees a 404 error page. This seems to indicate the server is only running a quick refresh rather than a proper full rebuild.

## Steps to Reproduce
1. Install a new Authoring Tool and create a new course
1. Run Preview Course
1. The preview window will open and a 404 error will appear

![chrome_NwobVKUiDg](https://user-images.githubusercontent.com/1676635/220620686-fc1af8c7-f970-45ec-89b3-b1371d234c50.png)

It should be noted that this can easily be resolved if the author manually chooses 'force rebuild' when they first attempt to build the course.

## Versions
  - Authoring Tool Version: 0.11.1
  - Framework Version: 5.26.0
  - Node.js Version: 14.16.1
  - MongoDB Version: MongoDB shell version v4.2.1
  - Operating System: Debian 10
  - Browser: Chrome 109

**Comment by danbuntu** [comment]
+1 on a brand new install on adapt on a new ubuntu 22.04 server

In my case clicking force rebuild  caused it to spin around for a bit and then popped up an error has occurred message. Clicking force rebuild again then made the course work

**Comment by Ant6009** [comment]
+1 Just updated to Adapt authoring tool 0.11.1. and Adapt framework 5.27.0. on Mac Ventura 13.0.1

Force rebuild works as expected and once that has been done preview also works as expected.

**Comment by simondate** [comment]
Likely related to this - https://github.com/adaptlearning/adapt_authoring/issues/2540
