### ISSUE TITLE
Imported courses ownership

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2697]
## Expected Behaviour

When an author imports a course (import account), they should be the owner of the course.

## Actual Behaviour

The course that gets imported becomes owned by the AT installation account (Installer account). The import account cannot see the account.

## Steps to Reproduce
1. Create a new AAT
1. Log into the installer account and add a new user as a super admin (import account)
1. Log into the import account and import a course
2. The course is not visible to this importer
3. Log into the installer account and the course is visible on their dashboard.

## Versions
  - Authoring Tool Version: 0.11.1
  - Framework Version: 5.26.0
  - Node.js Version: 14.16.1
  - Operating System: Debian 10

**Comment by danbuntu** [comment]
+1 I can confirm this is happening on my fresh install

**Comment by simondate** [comment]
I've also noticed that the user profile screen shows you are logged in as the installer account

![image](https://user-images.githubusercontent.com/1676635/220631771-de95df2e-3c5d-4477-911f-50be2324b66c.png)

**Comment by simondate** [comment]
@cksachdev -

> *  domain is not supported in mongodb driver 4 and above.
> *  This issue is caused by the `connect-mongodb-session` module, version 3.1.1, which the AAT uses MongoDB driver 4, which is causing the issue. **Reverting back to version `2.4.1` of this module fixes the issue**.
> *  It doesn't mean that collectively any dependency shouldn't be using mongodb driver 4 and above. We are using mongoose 5.7.3 with connect-mongodb-session 2.4.1

**Comment by simondate** [comment]
I will apply this change to my own trial server and look for volunteers to help me test it further.

**Comment by simondate** [comment]
Seems to have been an issue 3 years ago (but was fixed then) https://github.com/adaptlearning/adapt_authoring/issues/2540

**Comment by simondate** [comment]
On a production AT with 15+ users I reverted the Mongoose version back to `5.8.13`, which was the version reverted back to in the above issue and they have reported that everything seems to be working fine.

I'll create a PR for this version and once done I think everything will be ready for a 0.11.2 release.
