### ISSUE TITLE
handlebars:compile is throwing an error preventing download of course

### ISSUE THREAD

**Issue by RyanMindAtlas** [adaptlearning/adapt_authoring#2699]
## Expected Behaviour
Course is Downloaded

## Actual Behaviour
When you click the Publish course button an error is thrown.

Oops, something went wrong!

Command failed: grunt server-build:prod --outputdir=courses/62f3b09d494d861a34212f4c/63c6361650565f5ca519ef84/build --theme=62f3b122494d861a34212f67 --menu=adapt-contrib-boxMenu

Running the command directly on the server shows that it breaks on handlebars:compile

**_Running "handlebars:compile" (handlebars) task
>> 1 file created.
Warning: Unexpected token ? Use --force to continue.

Aborted due to warnings._**

Running with --force compiles but this is not possible through the GUI

## Steps to Reproduce
1. Enter course
2. Click the Publish Course button

## Versions
  - Authoring Tool Version: Master
  - Framework Version: Master
  - Node.js Version: v10.24.1
  - MongoDB Version:
  - Operating System:
  - Browser: Chrome

**Comment by simondate** [comment]
Your node version is in compataible. You should be using Node 12 or 14.

It might be worth using a tool like NVM to change Node version.
