### ISSUE TITLE
CK Editor not loading correctly

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#2751]
## Expected Behaviour

CK Editior is not loading correctly meaning that 'TextArea' fields are not interactable

![image](https://github.com/adaptlearning/adapt_authoring/assets/1676635/415f7ba9-b9c4-4b03-9147-48f1420af11f)

[Also reported here in Gitter](https://app.gitter.im/#/room/#adaptlearning_adapt_authoring:gitter.im/$JtH23jiAlrGPYujLXUFMqBrbFC_GtDpCSI1XJgFwZ1M)

Issue seemed to have been introduced in AAT 0.11.2. Likely an issue with a npm dependecy.

Issue can be fixed by just refreshing the page, but it's not really a great experience for the user!

**Comment by simondate** [comment]
I've only seen this once or twice myself, but a few of my clients who are using the AAT on a daily basis have reported it. The screenshot which I shared on that issue was originally shared by @nachocinalli, earlier the Gitter [AT chat room](https://app.gitter.im/#/room/#adaptlearning_adapt_authoring:gitter.im/$JtH23jiAlrGPYujLXUFMqBrbFC_GtDpCSI1XJgFwZ1M).

I know that at the last minute we bumped the 0.11.2 release from using Node 12/14 to Node 16/18. My guess is that issue was tied to that?

**Comment by oliverfoster** [comment]
Client side errors are very unlikely to be related to the server side architecture.
Here's the related issue on ckeditor: https://github.com/ckeditor/ckeditor4/issues/4390

You're going to need to figure out how to replicate it. I can't. I therefore can't fix it.

**Comment by simondate** [comment]
Response from my client who reported this -

"Yes, it just seems to be random unfortunately. Mostly happens with ‘Text' or ‘MCQ’ components but not consistently."

Again, this does not seem to occur every time, so I appreciate it's not the easiest to debug. Perhaps someone else can provide input?

The issue shared on [CKEditor's github seems to be fixed in 4.17.0](https://github.com/ckeditor/ckeditor4/issues/4390#issuecomment-942944667) and we use [4.16.2](https://github.com/adaptlearning/adapt_authoring/blob/e0952e0462d72a8d87bc048f92a13197c02a3a89/routes/index/index.hbs#L9), so it might just be as simple as updating the library?

I'm still curious as to why this only seemed to have started happening since the 0.11.2 release?

**Comment by oliverfoster** [comment]
Try https://github.com/adaptlearning/adapt_authoring/pull/2752 ?

**Comment by nachocinalli** [comment]
Switching to version 4.17.0 didn't work for me. The error persists, but I don't know how to debug it better. 
Windows 11, Chrome, AAT 0.11.2, node 16.15.0.
Trying to edit a MCQ component.
I added a console.log in this file: modules/scaffold/backboneFormsOverrides.js
![imagen](https://github.com/adaptlearning/adapt_authoring/assets/1735078/4166c638-c95d-47b2-b3a3-b3221b72dc67)

**Comment by oliverfoster** [comment]
Please try https://github.com/adaptlearning/adapt_authoring/pull/2752/files

You'll need to `grunt build` the client-side after making those changes.

**Comment by nachocinalli** [comment]
It worked! Thank you very much!

**Comment by oliverfoster** [comment]
Please approve the pull request https://github.com/adaptlearning/adapt_authoring/pull/2752

**Comment by oliverfoster** [comment]
@simondate could you test and approve please?

**Comment by simondate** [comment]
I'm off work until Friday but can try then.

**Comment by simondate** [comment]
I've just applied the branch to a client's Authoring Tool, so they can help test it.

I've just refreshed a component page ten times in a row and haven't noticed it (yet), so looking promising!
