### ISSUE TITLE
Unsupported Architecture

### ISSUE THREAD

**Issue by kennardjr** [adaptlearning/adapt_authoring#2762]
Hi all, 

I have successfully installed the Adapt Authoring tool a while back ago. Today when i wanted to open it, i received "Unsupported Architecture" message. I tried to troubleshoot and run "Node Upgrade", but still received a same error message. 

I decided to re-install it, and after following all instruction, issue persists.

here's the info: 
MacOS: Sonoma 14.4.1 (23E244) run on M1 Pro
Git: 2.45.0
Node: 16.20.2 (also tried 18.20.2 and 22.0.0)
Grunt: 1.4.3
Mongodb: 7.0

After i clone the Adapt_Authoring Project, Install the Required npm Packages and Run the Install Script (i.e., Node Install) 

i received this error: 

(node:16962) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16962) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:16962) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:16962) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Unsupported architecture.

does anyone encountered the same issue, or know how to fix it? thanks!

**Comment by oliverfoster** [comment]
You can ignore the warnings:

```sh
(node:16962) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
(node:16962) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:16962) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:16962) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
```

`Unsupported architecture` probably means that you're running node naively on the m1 arm processor. you need to install the x86/x64 version of node and have it emulate an intel/amd processor. some of the dependencies we use were not compiled for your processor.
