### ISSUE TITLE
CKEditor started to show a warning - Needs a quick replacement

### ISSUE THREAD

**Issue by cksachdev** [adaptlearning/adapt_authoring#2772]
## Expected Behaviour
CKEditor which is used to edit the Body in almost all entities started to show warning message.

"This CKEditor 4.16.1 version is not secure. Consider upgrading to the latest one 4.24.0-lts"

![image](https://github.com/adaptlearning/adapt_authoring/assets/37770/9cceb7c9-7429-464d-b1cf-6bef893e0602)

## Actual Behaviour
There shouldn't be a warning and editor should work as expected.

## Steps to Reproduce
1. Open any component and focus on Editor view of body property

Note:
A quick way to suppress the warning is by adding `versionCheck:false` in `frontend/src/modules/scaffold/backboneFormsOverrides.js` line 71.

**Comment by sebj8** [comment]
(remember to use `npx grunt build:prod` after change src)

**Comment by oliverfoster** [comment]
Ref: https://github.com/ckeditor/ckeditor4/security/advisories/GHSA-fq6h-4g8v-qqvm
