### ISSUE TITLE
Able to direct learners to content on the basis of error patterns

### ISSUE THREAD

**Issue by svenlaux** [adaptlearning/adapt_authoring#287]
Wish list item from Lisette:
It would be very nice to make error pattern analysis this allows you to determine whether students are making consistent mistakes. And also to make Learning Paths as a result of this analysis. Thus, when a student/pupil makes consistent mistakes he is given the right instructions, based on those mistakes. To do this one has to design questions and answer alternatives to make this possible. For example: someone learns basic computations. After instruction he is given some exercises. By doing those basic computations one can make for example three kinds of mistakes. Let’s call them (creatively :-) ) A,B and C. For the first question, one chooses answer alternative 1 if one doesn’t get it and is making errors of type A. For the second question, the same holds true for alternative 3. For the third question, idem for alternative 1. So if a student chooses alternatives 1,3,1 in succession he consistently makes error type A . If so, I would like to alter the learning path for this student to give him feedback and instruction about the specific error. It would be nice if the program does this automatically for the learner. So, not just telling him to read article x, but directly lead him to article x.

**Comment by brian-learningpool** [comment]
@svenlaux, I believe this is more suited to an extension rather than anything that is part of the authoring build.

**Comment by taylortom** [comment]
I'll move this to the framework JIRA, as don't think it applies to the authoring tool.
