### ISSUE TITLE
Able to include enhanced accessibility features with content (select background colours, text font, size changes)

### ISSUE THREAD

**Issue by svenlaux** [adaptlearning/adapt_authoring#288]
From Darren:
Options to include enhanced accessibility features with content (user ability to select different background colours, text font, size changes within the content).

**Comment by brian-learningpool** [comment]
ARIA support is coming with version 2.0 of the framework.  There will be an option to turn accessibility on or off, and background colours, text, etc. can be controlled via the theme.

**Comment by taylortom** [comment]
Are the accessibility updates enough to close this?
