### ISSUE TITLE
Able to create a course by importing a MS PowerPoint or Word document

### ISSUE THREAD

**Issue by svenlaux** [adaptlearning/adapt_authoring#292]
From Darren:
Ability to import a PowerPoint, word document, etc. to create a skeleton course which can then be enhanced within the authoring tool

**Comment by brian-learningpool** [comment]
@svenlaux, I'm going to have to close this ticket.  The technical effort to import a skeleton course from multiple disparate file formats beyond the capacity of the current team.  

I think the project has reached the stage where it's quite quick and easy to sketch out skeleton courses and time would be better spent on improving the UI experience, ironing out any minor issues, and providing import/export functionality in a valid authoring tool format.
