### ISSUE TITLE
Should be able to delete assets

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt_authoring#463]
Because we don't want to allow assets that are in use to be deleted, we need to use reference counting.

**Comment by brian-learningpool** [comment]
@dennis-learningpool, how about in lieu of reference counting we allow performing a soft delete?

**Comment by dennis-learningpool** [comment]
Works for me

**Comment by markl55** [comment]
@brian-learningpool Is the plan to then clean-up the soft deleted assets in a scheduled task?

**Comment by brian-learningpool** [comment]
@markl55, the tricky part is that existing courses may have assets associated, so any 'hard' delete of a 'deleted' asset could result in a broken course, e.g. images missing, etc.

To actually tidy these up would most likely involve iterating over the 'deleted' assets in the assets collection, and checking every single course to make sure they're not used.

**Comment by taylortom** [comment]
This has been partly addressed in https://github.com/adaptlearning/adapt_authoring/pull/805

**Comment by brian-learningpool** [comment]
Tidying up 'soft' deleted assets in a cron-type script makes sense.

**Comment by taylortom** [comment]
See https://github.com/adaptlearning/adapt_authoring/issues/682
