### ISSUE TITLE
Unable to edit extensions on Internet Explorer

### ISSUE THREAD

**Issue by rlafferty05** [adaptlearning/adapt_authoring#523]
Opening the block or component editor while having an extension enabled for that block/component (e.g. pageLevelProgress on a component) sometimes gives the following error in Internet Explorer 10 (and possibly other versions):

SCRIPT438: Object doesn't support property or method 'jsoneditor'

The block/component can still be edited, but the extension won't show up.

**Comment by brian-learningpool** [comment]
jsoneditor has been removed.
