### ISSUE TITLE
plugin properties displayed in reverse

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_authoring#579]
Appears that the properties of plugins do not follow the order in properties.schema, but appear in reverse instead. Appears to be the case, too, when optional items are added in components such as accordian via modal. If this is the case, it will be counter-intuitive for plugin developers who want required properties at the top and optional properties toward the bottom.

**Comment by taylortom** [comment]
+1 for being able to specify attribute order in some way, this can be quite illogical at times. A few examples:

- Body and instruction texts should come one after the other (and appear in general?)
- Question options come after feedback texts
- Text input prefix comes after suffix
- Narrative strap-line and title

**Comment by brian-learningpool** [comment]
+1, this due to the fact that JavaScript does not guarantee property order.  It would be great to get a fix for this.

**Comment by darylhedley** [comment]
The order only gets messed up on this because it is iterated over twice maybe three times before it hits the form. I'd suggest splitting the db schemas up away from the properties for the form editing. This way we can just pass down the form schemas and not the db ones. With greater separation becomes greater power - but more maintenance.

**Comment by brian-learningpool** [comment]
We should absolutely split the properties from the backend schemas.  I think our backend schemas are also too heavy, e.g. with regards to things like field labels, etc. these should come from a language pack.

**Comment by tomgreenfield** [comment]
Ordering resolved in #1140.
