### ISSUE TITLE
Make 'Save and edit' the highlighted interaction on component creation screen

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#583]

**Comment by brian-learningpool** [comment]
@taylortom, were you referring to the creation of components here?

**Comment by taylortom** [comment]
@brian-learningpool sorry yep, have updated description.

**Comment by taylortom** [comment]
Further to this, a number of people have mentioned that the placement of the button in the top left to be unintuitive; it doesn't seem to follow any other web conventions, which place 'save' type interactions at the bottom right (or in some cases the top right). 

Your eye never naturally falls to the top left upon filling out a form, rather it is usually the last place someone looks.

It makes sense to place buttons such as 'Add a new asset' at the top left, as you can assume that action is the first a user will take on the current page. Saving on the other hand, is usually the last.

**Comment by simondate** [comment]
The idea of actions being on the left seems to be quite a high level decision made at the start of the project. Watch [this video](https://youtu.be/6qzOMCIlzt4?t=9m41s) from almost 2 years ago.

Regarding if we should change it, I really think this would be something too ambitious in the 0.2.0 release. Could we leave this ticket open but move it to another milestone?

**Comment by taylortom** [comment]
I think we just focus on the core issue of the ticket, ignore that later comment of mine.

**Comment by simondate** [comment]
The original issue seems to have been fixed.
