### ISSUE TITLE
Preview loads main.html

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#588]
...which loads the course in an iframe, and so isn't responsive. The scrollbar also doesn't work.

**Comment by brian-learningpool** [comment]
@taylortom, this is something we may improve with support for version 2.0 of the framework.  Do you have any thoughts?

If we done link to main.html we'll get the SCORM version of the course at index.html, which will throw JS errors about not being able to connect to the LMS.

**Comment by taylortom** [comment]
I think leaving this for the v2.0.0 update is fine. 

Ollie's set up a SCORM harness html file in the new spoor which allows you to test basic tracking without an LMS - we could use this instead (there's also talk of swapping this in the default build when you have spoor installed, so that we get rid of those annoying 'not connected to LMS' messages completely).

**Comment by taylortom** [comment]
Fixed in https://github.com/adaptlearning/adapt_authoring/commit/b81d576a6d8ad75b388b29001dd4d5a72e1cb8ef
