### ISSUE TITLE
Uploading OGV fails

### ISSUE THREAD

**Issue by MartinSandberg** [adaptlearning/adapt_authoring#599]
Trying to upload video files (big buck bunny) to sandpit but this fails with no error message. The mp4 can be uploaded fine...

**Comment by taylortom** [comment]
Can't replicate this now.

**Comment by taylortom** [comment]
Need to check the upload limit to see if that's affecting this

**Comment by taylortom** [comment]
Can't replicate, closing. If you encounter this again @MartinSandberg, please reopen :)
