### ISSUE TITLE
Strange 404 after trying to run the authoring tool

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_authoring#605]
I have gone through the steps to install the tool but get the `GET http://localhost:5000/api/authcheck 404 (Not Found)` error.
Also `node server` starts on 5000 port not 3000 as in WIKI instruction

**Comment by taylortom** [comment]
The wiki has been amended to link to the new instructions in the README. Can you see if this fixes your problem?

**Comment by LukaszGrela** [comment]
It helped, but still it is bit incomplete, e.g. what values you should set in the installation process. I can see now the login page but it asks for an email, is it the `smtpUsername`? For the smtpService I have chose `none` and left other smtp fields empty.

**Comment by taylortom** [comment]
The script should have explained each option as it went through. Just pressing enter will take the default option given in brackets. The only the required values are the default username and password. This is what you enter on the login screen.

**Comment by LukaszGrela** [comment]
Yes, and my problem is that I've used "user" and not "user@doma.in" :) as login page was requiring email
