### ISSUE TITLE
Wikiprovements

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_authoring#606]
I'm sure there are lots of areas in the wiki that can be improved, as well as new pages that should be added. Please use this ticket to submit any suggestions.

**Please submit each suggestion as a separate comment, so we can track them more easily.**
- [ ] Why is there a `plugins` folder?
- [ ] What are the files in the root directory
- [ ] What are each of the folders
- [ ] What is `dml`?
- [ ] The `routes` folder (`lang` in particular)
- [ ] Where does data go
- [ ] Why `frontend/src` no `build`?
- [ ] What's in `frontend/src/core/app`
- [ ] Front-end modules

**Comment by chucklorenz** [comment]
Move installation instructions from README to its own page.

**Comment by chucklorenz** [comment]
Ensure installation instructions emphasize required version of nodejs (and other prerequ's).

**Comment by hamishdewe** [comment]
Is there any documentation on how to add new users for Adapt Builder. I haven't been able to find any and am currently stuck with a single user.

**Comment by chucklorenz** [comment]
@hamishdewe no, sorry, currently the authoring tool only works with one user. Adapt Builder is the name of an implementation of the authoring tool available through Learning Pool. If you are using their product, it is possible that it can accept more than one user (I don't know), but you would need to contact them directly.

**Comment by KristofferBroberg** [comment]
Hi,

Installation got stuck at:

> Set a unique name for your tenant (master) Christobal
> Set the display name for your tenant (Master) Christobal

Any ideas? Was it incredibly stupid of me to use the same name? Forgive a complete beginner.

**Comment by johnniezen** [comment]
Followed the procedure yesterday to install on an Ubuntu 14.04 LTS system. All works good, great explanation. However some link to the required versions could be benificial to newbies, like myself.

**Comment by ohmytohfu** [comment]
The file adapt-contrib-trickle is not supported by the latest version of the framework according to my installation error. I will have to create the adapt framework during node install and then remove adapt-contrib-trickle from the adapt.json manually from the framework folder. 

The installation will fail if adapt-contrib-trickle is not removed as it will not prompt you to enter the super user email and password.

**Comment by leroymg** [comment]
Hi good clear instructions. We ran into an issue setting up and discovered it was due to firewall settings preventing connection to git (npm install -g adapt-cli was failing).

The following command fixed it: 

git config --global url.https://github.com/.insteadOf git://github.com/

**Comment by JoelLatimernz** [comment]
Thanks for the Clear instructions! Could you add a section on how to secure the webapplication using SSL (HTTPS) for future setups please?

Thanks in advance

**Comment by taylortom** [comment]
Ho @JoelLatimernz we try to avoid documenting external processes and third-party software. Installing an SSL certificate is a pretty straightforward system admin task, and you'll be able to find various tutorials to do this.

What I will do is see about adding a link out to some third-party documentation for future users :)

**Comment by JoelLatimernz** [comment]
@taylortom Thanks Tom, in the end, I secured the web app with our Firewalls web server. It would be useful to have a link to SSL 3rd party link and a link to 3rd party Windows Service https://www.npmjs.com/package/windows-service 

Thanks for your replies! :)

**Comment by Aswino** [comment]
Hello, When I follow your procedure on a windows 2012 server, and get to the final step of node install I get following: ERROR: fatal: To many arguments. Any idea how to troubleshoot this?
I used the v6.x LTS release of Node.js as descibed =/

**Comment by blackducktraining** [comment]
Hello. First attempt to load today. All seemed to go well. When I run the last command "node server", I never see listening on port 5000 as the instructions indicate. All the other messages seem positive (scroll to bottom of below). I cannot reach the server on port 5000. Any thoughts?




Cloned https://github.com/adaptlearning/adapt_framework.git successfully.
/temp/5a5d111b313bee614f75a00f/adapt_framework switched to revision tags/v2.2.3
Node dependencies installed successfully.
Adapt framework plugins updated.
Master tenant created successfully.

Now we need to set up a 'Super Admin' account. This account can be used to manage everything on your app.productname instance.
> Email address ***************
> Password *********
> Confirm Password *********

Web application built successfully.

Installation completed successfully, the application can now be started with 'node server'.

[jbeaudoin@edu-docker01 adapt_authoring]$ node server
(node:22596) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
info: [15 Jan 2018 15:39:56 -05:00] configuration loaded from /home/jbeaudoin/adapt_authoring/conf/config.json
info: [15 Jan 2018 15:39:56 -05:00] Supporting the following authentication types:
info: [15 Jan 2018 15:39:56 -05:00] - local
info: [15 Jan 2018 15:39:56 -05:00] Adapt authoring tool v0.4.0 (v0.4.1-rc.1 is now available).
info: [15 Jan 2018 15:39:56 -05:00] Adapt framework 2.2.3.
info: [15 Jan 2018 15:39:56 -05:00] Run node upgrade.js to update your install.
info: [15 Jan 2018 15:39:56 -05:00] Connection established: adapt-tenant-master

**Comment by neuroticimbecile** [comment]
Good day!
Thank you for the instructions.
I'm installing on a server with the following:

    [root@lms ~]# cat /etc/redhat-release 
    CentOS release 6.10 (Final)

    [root@lms ~]# git --version
    git version 1.7.1

    [root@lms ~]# node --version
    v8.12.0

    [root@lms ~]# npm --version
    6.4.1

    [root@lms ~]# ffmpeg --version
    ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers
      built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-16)
    [root@lms ~]# mongod --version
    db version v4.0.3
    git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
    OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
    allocator: tcmalloc
    modules: none
    build environment:
        distmod: rhel62
        distarch: x86_64
        target_arch: x86_64

    [root@lms ~]# grunt --version
    grunt-cli v1.3.1

I made it all the way through steps 1, 2, and 3.
However, when I got to step 4, I got the following warnings upon running "node install"

    ...
    > Are you using ffmpeg? y/N (N) Y
    > Will you be using an SMTP server? (used for sending emails) y/N (N) 
    Now we need to configure the master tenant. 
    Tip: just press ENTER to accept the default value in brackets.

    \ Starting server
    (node:21094) DeprecationWarning: current URL string parser is deprecated, and will be removed in a 
    future version. To use the new parser, pass option | Starting server

Anyway, when running "node server", I get the following warnings and errors:
and all I see on the browser is a broken image icon.

    [root@lms adapt_authoring]# node server
    info: [11 Oct 2018 18:04:08 +08:00] configuration loaded from /root/adapt_authoring/conf/config.json
    info: [11 Oct 2018 18:04:09 +08:00] Supporting the following authentication types:
    info: [11 Oct 2018 18:04:09 +08:00] - local
    error: [11 Oct 2018 18:04:09 +08:00] Check for updates failed, Error: Cannot determine framework version
    Error: /root/adapt_authoring/temp/adapt_framework/package.json: ENOENT: no such file or directory, open '/root/adapt_authoring/temp/adapt_framework/package.json'
    (node:24791) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
    info: [11 Oct 2018 18:04:10 +08:00] Connection established: adapt-tenant-master
    (node:24791) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
    warn: [11 Oct 2018 18:04:10 +08:00] - Course Creator doesn't exist, cannot update
    warn: [11 Oct 2018 18:04:10 +08:00] - Product Manager doesn't exist, cannot update
    warn: [11 Oct 2018 18:04:10 +08:00] - Authenticated User doesn't exist, cannot update
    warn: [11 Oct 2018 18:04:10 +08:00] - Tenant Admin doesn't exist, cannot update
    warn: [11 Oct 2018 18:04:10 +08:00] - Super Admin doesn't exist, cannot update
    Warning: Missing translation for key: "app.loading"
    Warning: Missing translation for key: "app.productname"
    (node:24791) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
    Error: Cannot find module '/root/adapt_authoring/routes/lang/en.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /root/adapt_authoring/routes/lang/index.js:14:15
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)

    Warning: Missing translation for key: "app.loading"
    Warning: Missing translation for key: "app.productname"
    Error: Cannot find module '/root/adapt_authoring/routes/lang/en.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /root/adapt_authoring/routes/lang/index.js:14:15
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)

Any suggestions on how to diagnose and fix this?
Thanks.

**Comment by taylortom** [comment]
@neuroticimbecile it looks like the install script has failed, I'd suggest running that again, and checking it completes successfully (you should see a message to confirm this).

Closing this issue, as it shouldn't be used for general debugging advice.

**Comment by neuroticimbecile** [comment]
Hi Tom,

Good day!
Thank you for your reply.
I'm sorry for posting an inappropriate message to the project's github
issues area.
May you please point us to a forum where these kinds of issues are
discussed?

Thank you very much.

Regards,
-eric

**Comment by taylortom** [comment]
Hi Eric, 

The best place in the first instance is either the [community tech forums](https://community.adaptlearning.org/mod/forum/view.php?id=4), or in the [adapt_authoring room](https://gitter.im/adaptlearning/adapt_authoring) on Gitter 😄
