### ISSUE TITLE
Published package with rogue content

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_authoring#625]
After publishing simple test course I've found that the course/en folder contains extra assest e.g. pdf, video, images all of which contained assets from test course

**Comment by taylortom** [comment]
Can't replicate. Can you confirm that this is still an issue?
(tested using develop branch)

**Comment by LukaszGrela** [comment]
Shame that I wasn't specific, I can't replicate it as well but I have a feeling that it could be a left over from previous publish, and simply build folder accumulates files without removing those that are not used anymore.
