### ISSUE TITLE
Can't publish/preview courses

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_authoring#627]
I've installed the authoring tool and created the sample course, I've set up single section with single page and a text component, this appears in grunt console when I save the component (text component)

`warn: [08 Apr 2015 08:53:22 +01:00] Unexpected value for "data" parameter when updating component by 551d41d040a320bc247bfbd6`

And when I try to preview new course I got this error popup:
`Error generating preview, please contact Administrator`
and in grunt console

    info: [08 Apr 2015 08:54:36 +01:00] Retrieving JSON
    info: [08 Apr 2015 08:54:36 +01:00] All assets processed
    info: [08 Apr 2015 08:54:36 +01:00] 3.1. Ensuring framework build exists
    info: [08 Apr 2015 08:54:36 +01:00] 3.2. Using theme: adapt-contrib-vanilla
    info: [08 Apr 2015 08:54:36 +01:00] 3.3. Using menu: adapt-contrib-boxMenu
    info: [08 Apr 2015 08:54:36 +01:00] grunt server-build --outputdir=courses\551d40f340a320bc247bfbbc\5524de4abb39fd9024482276 --theme=adapt-contrib-vanilla --menu=adapt-contrib-boxMenu
    error: [08 Apr 2015 08:54:40 +01:00] exec error: Error: Command failed:
    error: [08 Apr 2015 08:54:40 +01:00] Error: Command failed:
    error: [08 Apr 2015 08:54:40 +01:00] Error: Command failed:

when eventually the preview tab will appear (after first error popup) then console log states:
`Uncaught SyntaxError: Unexpected token <`

The publish button generates zip but without adapt stuff in it e.g. `adapt.css` or `adapt.min.js`

**Comment by LukaszGrela** [comment]
https://community.adaptlearning.org/mod/forum/discuss.php?d=641#p3000

This was due to the custom component had some issues. Can the error logs be more clear when previewing/publishing?

**Comment by taylortom** [comment]
Duplicate.
