### ISSUE TITLE
extra menu level

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_authoring#628]
Create new course
Add section
add page in that section (add some components into the page)
preview the course

The menu level 1 as expected appears, click on the view button the next menu level appears (unexpected) after which if you click the view button expected content is displayed.

**Comment by LukaszGrela** [comment]
![adapt_menu_editor](https://cloud.githubusercontent.com/assets/7643591/7042253/5ae0cbe8-ddd8-11e4-9acd-da821bdf2c18.png)

**Comment by LukaszGrela** [comment]
![adapt_preview](https://cloud.githubusercontent.com/assets/7643591/7042262/7cf218ea-ddd8-11e4-8a7f-167f3e72af9b.png)

**Comment by brian-learningpool** [comment]
@LukaszGrela, this is as expected.  A 'section' is equivalent to a 'menu' contentObject in the framework .
