### ISSUE TITLE
Locked out of account and forgot your password link not working?

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_authoring#633]
Hi got a bit of a funny situation I put the wrong password into logon for my adapt authoring tool account. I went and re-entered the proper password in and I am getting this message in red now... "Your account is locked out, please contact an administrator to un-lock it". The "Forgot your password?" link doesn't work either in git bash I am getting this error "ERROR: connect ECONNREFUSED". Need help, can anyone get me back in my account?

**Comment by finbartracey1** [comment]
Hi Mike, 
Do you have access to the database?
If so find the collection users and set the failedLoginCount =0 for your userid.

This should solve the issue.

**Comment by mike-st** [comment]
Thanks so much! Not sure why but didn't think about that. Worked liked a charm! I used Robomongo and it fixed it like you said. Quick question if I wanted to add an extra user in this way is there anything I should keep in mind? Was thinking of adding a content editor type role.

**Comment by finbartracey1** [comment]
Hi mike, glad you got it sorted. 
The problem with adding users directly via the users collection in the db is the hashed password.

**Comment by mike-st** [comment]
Good point! I was thinking of using the same password for the other user. If I copy and paste the info I was hoping to get it to work, but that may not work I guess. Is there any other way of adding users in the pre-release that you know of or is this something I should wait on for the actual release? Thanks again so much for you help.
