### ISSUE TITLE
Course assets issues

### ISSUE THREAD

**Issue by finbartracey1** [adaptlearning/adapt_authoring#649]
1. If you upload an asset called myFile.png and one called myFile.PNG (the same image), it seems to cause problems with publish/preview.

2. If you unassociated an asset with a component, it is not removed from the courseassets collection in MongoDB.

**Comment by brian-learningpool** [comment]
Regarding 1, I think we can get around this by outputting the hashed unique filenames.

**Comment by finbartracey1** [comment]
part 2 - Addressed by this PR:  https://github.com/adaptlearning/adapt_authoring/pull/655
