### ISSUE TITLE
Restore display of "Tags" for projects/assets in thumbnail view

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt_authoring#650]
Tags were previously removed from thumbnails for projects and assets on the dashboard, as they could cause the vertical size of the thumbnail to grow, and thus throw off the grid layout for the dashboards.

We need to find a way to reintroduce the tags without affecting the layout. Tony Finlay suggested a horizontal scrolling element to list tags, and which would scroll when the tags list was long enough to start to wrap.

**Comment by brian-learningpool** [comment]
+1
