### ISSUE TITLE
IE9: "loading wheel of death" issue when using Asset selector

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt_authoring#666]
A colleague raised a bug relating to the Asset management modal view in IE9

Steps to reproduce:

1. When adding a graphic asset to a component, click on the asset selector Icon to bring up the asset manager modal view.

2. Instead of selecting an asset, just click the Cancel button

3. The loading wheel of death appears.

**Comment by darylhedley** [comment]
I've just taken a look at this in IE9 and IE10. This doesn't seem to be happening. The loading screen of death doesn't appear at all. I've also checked this with the new asset selection PR here:

https://github.com/adaptlearning/adapt_authoring/pull/665
