### ISSUE TITLE
Refactor courseassets collection

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#680]
The `courseassets` collection has not really changed over the development cycle and I feel the current implementation of selecting assets, via the Scaffold code, is not served well by the model.

For example, the `_contentTypeId` and `_contentTypeParentId` properties are too specific.  The `_contentTypeId` can store things like the component `_id` value.  The problem is that when a course is copied, this identifier gets out of sync.  

A better solution would be to use reference counting.

**Comment by taylortom** [comment]
Duplicate
