### ISSUE TITLE
Asset management: unable to add .pdf or .docx files to a course (M - v0.2)

### ISSUE THREAD

**Issue by lucyhodge** [adaptlearning/adapt_authoring#684]
Expand beyond only enabling images to be added.

**Comment by taylortom** [comment]
This is already possible. There is an issue however, when attempting to add documents using a popup version of the asset manager (e.g. in the case of adding items to the resources extension).

**Comment by brian-learningpool** [comment]
@taylortom, can you elaborate on the issue with adding documents for something like the Resources extension?

**Comment by taylortom** [comment]
Not an issue for me now.
