### ISSUE TITLE
Publishing: no error messages provided (M - v0.2)

### ISSUE THREAD

**Issue by lucyhodge** [adaptlearning/adapt_authoring#685]
When publishing, users may have broken pages with no knowledge of what's wrong or how to solve it. Cross-over issue with the framework.

**Comment by taylortom** [comment]
One such issue occurs if adding a component which has mandatory fields (e.g. narrative).

Steps to reproduce:
- Add a narrative to a block using the interface (*do not edit*)
- Publish the course before any settings have been changed

**Comment by brian-learningpool** [comment]
@taylortom, I think the framework needs to shoulder more defensive programming practices with regards to this too, e.g. on how it handles missing attributes, or missing assets.

**Comment by taylortom** [comment]
Related: https://github.com/adaptlearning/adapt_authoring/issues/627

**Comment by taylortom** [comment]
@brian-learningpool I agree, although I think the builder should prevent you from publishing/saving if you haven't filled out all required fields.

@darylhedley's feature request here would help too: https://github.com/adaptlearning/adapt_authoring/issues/811

**Comment by taylortom** [comment]
Form validation has been fixed, so this should catch some errors

**Comment by taylortom** [comment]
Leaving this open as it's a wider problem that needs addressing

**Comment by taylortom** [comment]
Fixed in https://github.com/adaptlearning/adapt_authoring/pull/2264. @adaptlearning/authoring-tool-push do we think this is a suitable solution?

**Comment by canstudios-nicolaw** [comment]
@taylortom I don't think this was fixed by #2264.

If there are components with missing fields the grunt build completes and the preview opens, it's only if the user clicks on a page containing that component that the page load hangs.

**Comment by taylortom** [comment]
Right yeah. Runtime issues should maybe have a framework solution (I've looked into capturing console errors etc. but not sure this is necessary).

Happy to close this one

**Comment by canstudios-nicolaw** [comment]
Agreed, I think this is a framework issue

**Comment by taylortom** [comment]
I'll leave this one for @tomgreenfield to close on confirmation of our comments above 😄
