### ISSUE TITLE
Ensure compatibility with 4.2 node.js

### ISSUE THREAD

**Issue by lucyhodge** [adaptlearning/adapt_authoring#690]
Ensure compatibility with later versions, and implement a quarterly review.

**Comment by dancgray** [comment]
Preview and publish errors seem to be in file storage plugin here:
https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/filestorage/localfs/index.js#L133

fs.createReadStream returns an error if options is not a string or object.

Should we pass just the defaults?
