### ISSUE TITLE
Do we want to allow all asset types in AssetManagementModalView?

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#711]
Currently, only 'other' assets are displayed. I can imagine it being useful to also link to images etc. here.

Any thoughts?

**Comment by darylhedley** [comment]
I think the scaffoldAssetView should really handle this. So if you want all types of assets (mainly thinking about resources here) you should be able to put Asset instead of Asset:other as the type in the schema file. Will add this in
