### ISSUE TITLE
Dashboard courses UI interaction inconsistent with rest of app

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#712]
It isn't clear that dashboard courses need to be double-clicked to be opened. Other areas require you to double click **or** use the cog icon to edit, while the course dashboard only allows double click. Additionally, the course buttons have the same blue styling as all other single-click buttons in the course, which confuses things further.

**Comment by brian-learningpool** [comment]
Tom, are you saying that it's confusing because there isn't a plain 'Edit' link?   We do have 'Edit settings' and 'Edit course'

**Comment by taylortom** [comment]
Sorry, have only just seen this. I don't think these apply anymore.
