### ISSUE TITLE
Order of left and right components in mobile view depends on order added

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#718]
Say I have 2 blocks each with 2 components inside.
If I create them in this order
BLOCK 1
ADD COMPONENT 1 FIRST   |  ADD COMPONENT 2 SECOND
BLOCK 2
ADD COMPONENT 1 SECOND   |   ADD COMPONENT 2 FIRST

Then in mobile view I get the following structure -

BLOCK 1
COMPONENT 1
COMPONENT 2
BLOCK 2
COMPONENT 2
COMPONENT 1

There does not seem to be any way to correct this once the components are in place, other than deleting and readdding

**Comment by brian-learningpool** [comment]
Hi Helen,

Thanks for posting the steps to re-create.  I see the issue you're referring to and believe it's due to a bug in the framework.  I'm going to raise a ticket there to reference this.

**Comment by hmaffin** [comment]
Fantastic – thank you!

**Comment by brian-learningpool** [comment]
If you run a `git pull` on the `master` branch of the adapt_framework checkout inside your /temp/{tenantId}/adapt_framework folder this will resolve it for you.
