### ISSUE TITLE
Any <span> tag added in the wysiwyg editor is removed when going in to re-edit

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#719]
If I add a <span> tag to the body text of a text element in the text component (using the source button in the wysiwyg editor), for example for tooltips - if I go in afterwards to make other changes to the body text the span tag and it's closing tag have disappeared and need re-adding.

**Comment by brian-learningpool** [comment]
I believe this is an issue with the configuration of the CKEditor control we're using.  This should be fixable.
