### ISSUE TITLE
Confirmation when deleting an item such as a narrative item or question stem 

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#720]
I found it all to easy one day to hit the little orange X on a narrative item and lose all the content of it without any way to reinstate.

Can we have a confirmation box appear when we click on the orange Xs so this can't happen as easily?!

**Comment by brian-learningpool** [comment]
I think this enhancement makes sense.  Something similar to the prompt when deleting an article, block or component should suffice.
