### ISSUE TITLE
Spelling mistake on matching question

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_authoring#725]
Hi all,

It's a bit pedantic but there is a spelling mistake on the matching question component.

When you are adding a matching item the window opens and allows you to enter all the possible matching options. It currently reads as 'Mathing Options:' instead of 'Matching Options:'

**Comment by darylhedley** [comment]
Yep this has now been updated here
https://github.com/adaptlearning/adapt-contrib-matching/pull/67
