### ISSUE TITLE
issue with Phantomjs package install on some systems

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt_authoring#726]
See this thread: https://community.adaptlearning.org/mod/forum/discuss.php?d=778

It appears that phantomjs may be causing issues with some systems. 

Phantom may no longer be used in the tool, so perhaps should be removed from package.json. In any case, it should at least be moved to devDependencies, instead of dependencies.

**Comment by brian-learningpool** [comment]
The `package.json` has been updated so running `npm install --production` removes the need for CasperJS/PhantomJS.
