### ISSUE TITLE
Add background images to components

### ISSUE THREAD

**Issue by sandervanzijl** [adaptlearning/adapt_authoring#727]
In the authoring tool, it would be really fantastic if it were to be possible to set a background image per page /article/block/component. This is now only possible by editing a theme. ideally the theme can be used over multple courses, so should not contain references to course specific images.

this way it would be possible, without any css coding, to use an image as the background for the course, then another image for the background of the article, and even images for the background of text etc.

off course some extra controls are needed such as setting transparency etc etc.

**Comment by brian-learningpool** [comment]
This very feature is something which is in the roadmap for version 1.0.

**Comment by lc-thomasberger** [comment]
I would not recommend to add background images directly to a page/article/block/component. 

Instead themes should provide classes that apply images / colors to those elements.
The theme editor would then allow you to customize those classes by changing the color or by updating the image.

**Comment by sandervanzijl** [comment]
if there is going to be a theme editor, then yes you could use the theme editor.
but in the opensource version there is no theme editor (sofar).

Also I do not agree that course specific images should be in a theme. A theme should be usable in many courses. Take for example a company developing multiple courses. They want to use the same theme for every course to create the same look and feel, but they also want to use images. So the theme just takes care of the basic look and feel of every course stuff, and the course specfic layout is done in the course itself.

an other option would be to have multiple themes. one general theme for all courses and one theme for the specific course. but this is a matter of implementation.

**Comment by taylortom** [comment]
See prototype for ongoing work: https://github.com/adaptlearning/adapt_authoring/pull/1499

**Comment by taylortom** [comment]
This is fixed in #1116.
