### ISSUE TITLE
Adapt v2.0 - Make Publish/Preview with new framework Gruntfile

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#735]
The Gruntfile in the framework has changed and the code in the output plugin will require changing to support this.

NOTE: It should be possible to still work with version 1.x also, if the user has not upgraded.

**Comment by taylortom** [comment]
What's needed in the server-build task? Currently consists of the following:
https://github.com/adaptlearning/adapt_framework/blob/develop/Gruntfile.js#L592-L593

**Comment by brian-learningpool** [comment]
The `server-build` task is required to compile/build the JS, CSS and everything else required for a course to render, except the actual course JSON.  

The course JSON gets dropped into the correct folder during the publish/preview.

**Comment by brian-learningpool** [comment]
Resolved in #801.
