### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by pattyland** [adaptlearning/adapt_authoring#739]
Is there an (official) demo system where you can use this tool right now?

**Comment by brian-learningpool** [comment]
Yes, there is a demo system here (http://sandpit.adaptlearning.org/), but you will have to be pre-approved for access.  You can visit this thread on the community site for more information:
https://community.adaptlearning.org/mod/forum/discuss.php?d=585

**Comment by hmaffin** [comment]
You could try the framework test demo and the downloadable source files at https://community.adaptlearning.org/course/view.php?id=4 for now - or just download the framework or builder from the adapt_learning repo as per your preference. Hope that helps.

**Comment by pattyland** [comment]
@hmaffin Thanks, but I want to try the authoring tool, not the framework. The link from @brian-learningpool is what I looked for, but not really convenient for a presentation I would like to make in my company. I think I'm gonna make an installation

**Comment by hmaffin** [comment]
That's fine I use the tool too. If you go to https://github.com/adaptlearning/adapt_authoring and follow the instructions it's pretty easy, and go to the community at 
https://community.adaptlearning.org/mod/forum/view.php?id=4 if you need any help
