### ISSUE TITLE
Narrative component needs mobile version of instructions/body

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#753]
The same as Hot Graphic does - as it would be good to be able to switch the text that is given to include click the + sign for example.

**Comment by zenduo** [comment]
Hi, this feature has been included in the component update as part of the v2 Framework release.

**Comment by hmaffin** [comment]
Brill. I work in the Authoring Tool though :)

**Comment by taylortom** [comment]
Instruction is indeed now included. 

I'm not aware that there is such thing as mobile body text - is this a feature request?

**Comment by hmaffin** [comment]
Hot Graphic has "Mobile body text" so that you see one set of instructions for when it's a hotgraphic and a different set for when you are in mobile mode as a narrative (as suddenly you don't have to "explore the image" for example so it works well.

In a narrative it's quite straight forward to tell them to swipe or click through in large mode but in mobile I think it would be good to change the instructions to remind them to click on the + to see more. 

So perhaps you're right - a feature request instead...

**Comment by taylortom** [comment]
![screen shot 2015-09-17 at 11 01 29](https://cloud.githubusercontent.com/assets/1059083/9930425/825debd8-5d2b-11e5-9777-cc0c5681c419.png)

**Comment by hmaffin** [comment]
Presume that's framework? Don't have that in Authoring tool v0.1.1. Presume it will come though :)

**Comment by taylortom** [comment]
Closing this, as fixed in later version.
