### ISSUE TITLE
authoring tool reports v2 frmwrk but node upgrade does not upgrade to v2

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_authoring#771]
I ran `node upgrade` (also `node upgrade.js`) as prompted by the authoring tool.
After "Checking for Adapt Framework upgrades...", prompt quickly returns. 

![image1](https://cloud.githubusercontent.com/assets/9489014/9050668/00981ffc-3a16-11e5-86f6-f31765010e95.png)

**Comment by darloboy101** [comment]
I've also had this when trying to upgrade to use 2.0 with the authoring tool. Mentioned it on the Adapt technical discussion forum -- where seems a couple of others have already flagged.

**Comment by brian-learningpool** [comment]
Resolved in `develop` with #801
