### ISSUE TITLE
Running preview in the authoring tool should run grunt dev not grunt build so we can have...

### ISSUE THREAD

**Issue by darylhedley** [adaptlearning/adapt_authoring#811]
SOURCE-MAPPING!

**Comment by taylortom** [comment]
@darylhedley do we need anything more than this? https://github.com/taylortom/adapt_framework/blob/develop/Gruntfile.js#L609-L612

(with references changed here: https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/output/adapt/index.js#L158-L160)

**Comment by taylortom** [comment]
Ollie's new LESS task should now also give us LESS sourcemaps :tada:
