### ISSUE TITLE
Resource link save errors

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#820]
1 - Click save on the top ‘save link’ button and get following error in browser console:
 Uncaught TypeError: Cannot read property 'get' of undefined

Save has no effect and there is no error or action shown in the builder. 
No error on command line.

![screen shot 2015-09-10 at 10 09 19](https://cloud.githubusercontent.com/assets/6452430/9793285/a3acf4a4-57dc-11e5-82ad-29f3ffdd37d1.png)

2 - When adding a resource item
 Click OK without entering required fields (error messages displayed correctly on screen)
Enter external link and required fields, click save on the links
The buttons view is not changed and remains on save/cancel with required error messages.
Information saves OK though, no errors in console or command line.
![screen shot 2015-09-10 at 14 46 28](https://cloud.githubusercontent.com/assets/6452430/9793434/4f530b72-57dd-11e5-8c80-ff28cb026d71.png)

**Comment by taylortom** [comment]
I'm unable to replicate 1. Which code were you using?

**Comment by taylortom** [comment]
Actually, I can replicate - if you include the `http://`, then it works fine

**Comment by taylortom** [comment]
Concerning issue 1: how do we want to deal with this? should we validate urls, and warn if there's no http prefix, or automatically prepend this?

**Comment by taylortom** [comment]
There seem to be two issues here:

1. [This handlebars helper function](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/app/helpers.js#L205-L219) isn't parsing URLs properly - any urls which don't contain a forward-slash throw a JS error, so www.github.com wouldn't work, whereas http://www.github.com and www.github.com/adaptlearning would. 
1. There is a further issue whereby any URLs which **do** contain a slash, but not the `http://` will be appended to the current URL (i.e. `http://localhost:5000/preview/55f0121b611794f343bd7d98/55f012d5ad7bb4e5440cf54e/www.google.com/`), meaning that following the link from the framework output doesn't work.
 
I'm not sure what the best action here is, probably some validation to check for the `http://`?

@darylhedley any thoughts on this?

**Comment by brian-learningpool** [comment]
I think a better solution would be to use a RegEx on `http(s)://` to determine if the asset is external.
