### ISSUE TITLE
Add error handling to schema.pluginLocations

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#831]
If a schema's uploaded which is missing one of the locations, you're unable to enable that extension in the tool with no explanation why. Would be good to catch this, and log an error message.

Side note/possible alternative: remove the need to specify every location even when not used (i.e. config, course, content object, article, block, component).

**Comment by brian-learningpool** [comment]
Good point, Tom.  The code should at least log an error and ideally be robust enough to handle this.
