### ISSUE TITLE
Install fails on Win8.1 at Step 4 on Wiki when 'node install' is run

### ISSUE THREAD

**Issue by davewallace** [adaptlearning/adapt_authoring#838]
Install happens, no dependency errors occur, and I'm running node v0.10.33 however I get the following error:

`
Completed the npm install.

Installing plugins for the Adapt framework.
 'adapt' is not recognized as an internal or external command,
operable program or batch file.

ERROR: 1
ERROR:  1
Framework install failed. See console output for possible reasons.
`

**Comment by dennis-learningpool** [comment]
Hi @davewallace - the error 
```
'adapt' is not recognized as an internal or external command,
operable program or batch file.
```
suggests that the adapt-cli dependency has not been installed, or is not available to the account that you are currently using. To fix this run the command
````
npm install -g adapt-cli
````
Please also make sure you have installed the other dependencies (including grunt-cli) outlined here: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin#1

If this fixes the above issue for you, please mark this issue as closed.

**Comment by davewallace** [comment]
@dennis-learningpool Thanks for that, yep it did solve the issue, though I had already done aw days before so it was installed globally not locally, same with the grunt dependency. I'll mark it closed though, yep.
