### ISSUE TITLE
Add 'system information' view

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#847]
Which displays data such as:
- Tool version
- Framework version

I thought of possibly appending this to the user profile screen.

**Comment by brian-learningpool** [comment]
This information is visible when starting server.js.

**Comment by dennis-learningpool** [comment]
Still useful to be able to see it from the frontend, I think.

+1 for this

**Comment by taylortom** [comment]
Yeah, I was thinking more for the non-tech end users, to help with troubleshooting etc.

**Comment by taylortom** [comment]
Duplicate of #1072
