### ISSUE TITLE
Handlebars.helpers.isAssetExternal: bad scope reference

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#855]
Get a runtime error here: https://github.com/adaptlearning/adapt_authoring/blob/issue/829/frontend/src/core/app/helpers.js#L218

**Comment by danjah** [comment]
Is this related to editing an existing hotgraphic component? I received the attached error, referring to isAssetExternal when trying to re-edit a hotgraphic component.

![adapt_edit_hotgraphic_error](https://cloud.githubusercontent.com/assets/788798/10009507/1c127eec-6132-11e5-9fff-519c228a6d2a.png)

**Comment by taylortom** [comment]
Yep
