### ISSUE TITLE
Allow for multiple device preview

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#858]
Would be nice to be able to preview courses in different screen ratios (i.e. desktop/tablet/mobile) without having to resize the window.

This is linked to #588.

See highlighted buttons for an example.
![device-preview](https://cloud.githubusercontent.com/assets/1059083/10017948/7c7664a4-612a-11e5-9cb4-bdedf34d2a96.png)

**Comment by brian-learningpool** [comment]
Couldn't this be handled by one of the pages bundled with the framework?

**Comment by taylortom** [comment]
This has been moved to the framework.
