### ISSUE TITLE
Broken preview and publish after deleting asset

### ISSUE THREAD

**Issue by jpablo128** [adaptlearning/adapt_authoring#863]
# Description
If you delete an asset from the asset manager, the (soft) deletion is correctly applied in the 'assets' collection, but it is NOT applied in the 'courseassets' collection of the DB. Thus, when previewing or publishing, the reference to the asset still exists in the course, but the asset is not accessible (because it's soft-deleted), so there's an error (it doesn't find what it thinks should be there...)
I've been using Robomongo to see what's going on in the DB.

I'm using branch 'develop' of the authoring tool, 
commit: a8f8a4b69bc5fac6968ea4e03eb723fc2446a3ec
the system is an Ubuntu 14.04 (it's really an lxc container with ubuntu 14.04, running in an Ubuntu 14.04 host).

# Steps to reproduce
0. Create minimal course, just 1 page, whatever minimalist thing that you can preview.
1. Add an image using the asset manager (new asset appears in the 'assets' collection)
2. Somewhere in the course, e.g. in a page, use that asset
3. You should be able to preview the course normally
4. Delete the image using the asset manager. The corresponding asset in the 'assets' collection has the property '_isDeleted set to true, so the asset doesn't show up in the asset manager any more -correct-). BUT, the corresponding asset in the 'courseassets' collection still has the property '_isDeleted' set to 'false'
5. Try to preview. You should get an error box in the browser, that just says 'Error:' (with no message).
The errors I see in the server console are:
```
info: [23 Sep 2015 10:03:14 +00:00] Retrieving JSON
TypeError: Cannot read property 'filename' of undefined
    at /home/pabby/adapt_authoring/lib/outputmanager.js:642:70
    at Promise.<anonymous> (/home/pabby/adapt_authoring/lib/assetmanager.js:241:18)
    at Promise.<anonymous> (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/home/pabby/adapt_authoring/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/home/pabby/adapt_authoring/node_modules/mongoose/lib/query.js:1016:22)
    at Object._onImmediate (/home/pabby/adapt_authoring/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

I've noticed that if I delete the corresponding document in the 'courseassets' collection, thus cleaning up the erroneous asset reference in the course, things work ok, e.g. I can preview and publish the course.

**Comment by jpablo128** [comment]
Also, I noticed that setting the property '_isDeleted' to true (by hand) in the corresponding document of the 'courseassets' collection is not enough to get rid of the error...

**Comment by brian-learningpool** [comment]
@jpablo128, thank you for raising this bug and providing the detailed steps to re-create.  I've confirmed the issue and hope to have a patch soon.

**Comment by jpablo128** [comment]
Thanks to you @brian-learningpool , I'm getting started with AdaptLearning, and it's great. You guys have done amazing work here!

I've noticed too that you can manually delete the reference to the broken asset in the course... (this was not obvious to me throughout my testing ...) but a big course with many asset references.. can be difficult to fix by hand. Thanks.

**Comment by brian-learningpool** [comment]
Thanks for the kind words @jpablo128.  I have a fix ready which should be merged into `develop` shortly.

We're always on the lookout for other people who can contribute to the project in whatever way they can, if you would be interested?

**Comment by jpablo128** [comment]
Thanks. I've started with Adapt recently (I'm an experienced eLearning 
person though).  I'm more of a python guy  for the backend ( I do know 
js, but I use it in the
frontend basically) so... the tech stack of Adapt has lots things that 
are new to me ... I'm reading parts of the Adapt source code, trying to 
understand things (particularly,
how to do extensions -because of interest in xAPI- ) ... so I'll do what 
I can... :)
One thing I've noticed is ... all things Adapt are in English... haven't 
seen resources in Spanish (my native language) ... it's crossed my mind 
to write one or more blog posts about Adapt in Spanish... to kind of 
spread the word... any thoughts?
kind regards

     jPablo

**Comment by brian-learningpool** [comment]
Some blog posts in Spanish would be excellent.  We actually have an open ticket #768 to add a Spanish language pack to the authoring tool also.

We're hoping to start work soon on xAPI as an alternative to our Spoor/SCORM plugin.  You experience would be welcome here.  Even if you don't feel like coding right away though, as a developer quality bug reports are always appreciated. :+1:
