### ISSUE TITLE
Ability to change component layout once created

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#870]
You can currently work around this issue by move it to a new block, then move it back in the correct position.

**Comment by sandervanzijl** [comment]
to add a little comment: it would be terrific if a user could just click and hold the component and drag it to  another layout, without the need to create a new block for temporary placement. this functionality could include automatic swapping. off course there would be limits to what is possible. for example if a component is now positioned on the left, it can only be positioned as a middle component when there is no right component.

**Comment by hmaffin** [comment]
I'd love to see this as an option in the edit menu of a component so for example a left block can be made into a full block (assuming no right block exists) with one click.

**Comment by markl55** [comment]
Hi,

https://community.adaptlearning.org/mod/forum/discuss.php?d=1129

Mockup!
![at component pos](https://cloud.githubusercontent.com/assets/1193345/12321055/ff224ed6-baa3-11e5-944e-5232fdee1de8.png)

Discussion on the design of this feature is in the forum. This action seems to be used quite frequently so we've moved the action that re-position's the component out of the cog and directly onto the header bar of the component. With the result that it only takes one click to re-position the component. Ideally the options would also exist in the properties cog.

**Comment by dancgray** [comment]
+1 for the implementation from @markl55. Was the additional swap functionality in the first block intended?

**Comment by markl55** [comment]
Hi @dancgray added for consistency, so that you could switch the left one to the right or the right one to the left (essentially the same thing though as it switches the two of them around).
