### ISSUE TITLE
Image validation

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#871]
Size guide/check when using an image in a component.

**Comment by brian-learningpool** [comment]
@taylortom, can you please clarify the requirement here?

**Comment by taylortom** [comment]
This came from a community member, have forwarded them the link for comment.

**Comment by sandervanzijl** [comment]
sorry that it took me so long to respond to this.

Some components like narrative work best when images have certain sizes. 
the component could check/give advise on the size of the picture you are trying to use. Also when image sizes are used that are not the same, this can result in weird display results. there could be a warning indicating that image sizes are not the same.

other problems we had with images where for example the automatic resizing. we upload an image, but adapt decides that the width is used to display this image. so it enlarges the image to fit a certain width. this can make the image a lot taller. in our case the image of a remote control is a lot taller than it is wide. it would be very nice of the imagesize was checked for these kind of issues, or when the user can enter some size restrictions for example.

**Comment by jasonbutler** [comment]
Default placeholder images at preferred dimensions could be prepopulated in each component  - therefore the sizes for S/M/L in a graphic for example, would allow users to correct appropriately sized assets

**Comment by taylortom** [comment]
Think this should be replaced with https://github.com/adaptlearning/adapt_authoring/issues/2292
