### ISSUE TITLE
Re-work Notify code to standardise user feedback messages

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#874]
There are places in the code where we have a mix of code using the Notify plugin, and others using alerts, etc, so this change will included standardising:
* `alert()`
* `confirm()`

This may require either overriding these functions or replacing the instances.  I've suggested overriding the functions because of some third-party libraries (specifically Backbone Forms) which I'd prefer us not to hack.
 
Something like [SweetAlert](http://t4t5.github.io/sweetalert/) looks promising.

**Comment by brian-learningpool** [comment]
@dancgray, would you be able to pick this up?

**Comment by dancgray** [comment]
@brian-learningpool, looks like @taylortom has done a stack of work for this.
https://github.com/adaptlearning/adapt_authoring/pull/869. Will give it a good test.

**Comment by taylortom** [comment]
See here for the overrides:
https://github.com/adaptlearning/adapt_authoring/blob/18ce88517429677efe4e4198bca3439c1c4540e6/frontend/src/core/notify/plugins/alert/index.js#L81-L82

**Comment by taylortom** [comment]
@dancgray's looking into replacing the old references to notify

**Comment by dancgray** [comment]
@taylortom, I have replaced all of the old notify references. However I have an issue with this line: https://github.com/adaptlearning/adapt_authoring/blob/notify-rework/frontend/src/core/editor/menu/views/editorMenuItemView.js#L215

Sweetalert does not run the callback on cancel meaning that this line never gets called.

**Comment by taylortom** [comment]
Found an identical issue here: https://github.com/t4t5/sweetalert/issues/431
Callback works correctly if it's an anonymous function -.-
