### ISSUE TITLE
Support optimised framework build process

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#875]
The bulk of the work is on [this ticket (#723)](https://github.com/adaptlearning/adapt_framework/issues/723) in the framework but there will most likely be code changes (build flags, etc.) required on the authoring tool.

**Comment by brian-learningpool** [comment]
The plan is to augment the build process by adding the following to the `config.json` output.
```
build: {
  includes: [

  ]
}
```
Note that the theme and menu must be added to the `includes` array.

**Comment by brian-learningpool** [comment]
@taylortom, If you could test this with the latest `develop` branch that would be great.

**Comment by taylortom** [comment]
Work outstanding on this:
- Sort issue with spoor/main.html
- Fix plugin dependency (i.e. MCQ <- GMCQ)

**Comment by taylortom** [comment]
Have added links to my last comment.
