### ISSUE TITLE
Upgraded AT (v0.1.2 ) "Cannot find module en.json" when "node server" run.

### ISSUE THREAD

**Issue by danjah** [adaptlearning/adapt_authoring#879]
Post upgrade, when I run `node server`, I see the anticipation messaging: https://gist.github.com/danjah/0aa7ab2a9e4a9a8008a2  and so running http://localhost:5000 does load up a UI, but it's stuck on 'Loading...' and fails in console like so: `GET http://localhost:5000/lang/en 500 (Internal Server Error)`

I notice that there is no file called `en.json` in `routes\lang\` but there is a file called `en-application.json`, and when renamed to `en.json`... everything then works just fine.

**Comment by brian-learningpool** [comment]
Hi @danjah, did you by chance switch from `develop` to `master`?  

You should be able to resolve this if you run `grunt build:dev` or `grunt build:prod`, then launch the server again.

**Comment by danjah** [comment]
@brian-learningpool I did indeed, and so now I have, and everything works fine - thanks Brian.
