### ISSUE TITLE
Verify installation pre-requisites

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#880]
I've had a few occasions where my database connection has fallen over unbeknownst to me, causing the install to hang when it tries to initialise the db. Depending on hardware and internet connection, this can be several minutes into the install.

Would be good to have some kind of check for this very early on (before clone/npm install of the framework preferably).

**Comment by brian-learningpool** [comment]
I agree this would be good to have.  Perhaps we should add a function that tests all the pre-requisites?

**Comment by brian-learningpool** [comment]
Actually, we definitely should have a function that verifies all the pre-requisites.

**Comment by brian-learningpool** [comment]
Pre-requisites:
* Node.js version
* MongoDB is installed and can be connected to
* Dependencies are installed (Grunt, etc.)
* GitHub is accessibile

**Comment by lc-thomasberger** [comment]
node version check is related to https://github.com/adaptlearning/adapt_authoring/pull/2038

**Comment by lc-thomasberger** [comment]
With the current way how we handle configuration settings and do the setup we are only able to check the following prerequisites at the start of the installation (with no detailed config settings available):
- installed node version ( #2038 )
- git installed
- grunt-cli installed
- connection to github-api possible

As users can specify a custom connection-url for mongo-db, a check if mongodb is installed locally does not make sense.
Also during installation a custom git-url for the repositories can be specified. Previously we only checked for the github-api being available.

Do you guys think the check's add value and improve the installation experience? 

To check if **git** and **grunt-cli** are installed we might also update the documentation and provide a snippet to check if both are properly installed.
The same would work for validation the node version before installing the tool or upgrading the tool.

**Comment by taylortom** [comment]
Another to check: ffmpeg

**Comment by taylortom** [comment]
Yep, but we can check if it's turned on in the config (agree it should be a warning though, as the app can run just fine without it)
