### ISSUE TITLE
Ability to import & export courses

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#905]
Would be very useful if courses built in the tool could be exported out, and imported into another instance.

**Comment by taylortom** [comment]
Initial mindmap can be found [in the documentation repo](https://raw.githubusercontent.com/adaptlearning/documentation/master/02_authoring_tool/04_feature_development/import_export/ImportExport.mm).
Requirements can be found [in the same place](https://github.com/adaptlearning/documentation/blob/master/02_authoring_tool/04_feature_development/import_export/import-export-reqs.md).

**Comment by taylortom** [comment]
Developer export added here: https://github.com/adaptlearning/adapt_authoring/commit/afc24bef8fa675e1fa8f0425a24d4fc8da65a458

**Comment by taylortom** [comment]
In-progress import here: https://github.com/adaptlearning/adapt_authoring/tree/issue/905

**Comment by dancgray** [comment]
See [issues/1387](https://github.com/adaptlearning/adapt_authoring/issues/1387) for the requirement IMEX-021: Ability to import a course developed outside of the AT

**Comment by taylortom** [comment]
Closing this, as not really relevant anymore

**Comment by zeigerpuppy** [comment]
import/export would be useful for moving courses between tenants

**Comment by taylortom** [comment]
@zeigerpuppy import was added in release 0.5.0. See the changelog for more info:
https://github.com/adaptlearning/adapt_authoring/blob/master/CHANGELOG.md#050---2018-06-26
