### ISSUE TITLE
Stray window.confirm needs converting to use Notify

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#908]
[frontend/src/core/editor/page/views/editorPageView.js#L144-L150](https://github.com/adaptlearning/adapt_authoring/blob/fe070510efd430aa21123479910041f373aa95ed/frontend/src/core/editor/page/views/editorPageView.js#L144-L150)

**Comment by dancgray** [comment]
@taylortom is this legacy code? I don't see where this is actually used.

**Comment by taylortom** [comment]
Not sure tbh @dancgray, think it just came up during a 'find and replace'. Will have a look into it.

**Comment by dancgray** [comment]
Has been removed in the develop branch: https://github.com/adaptlearning/adapt_authoring/commit/bd101593eca8a8ff877ababd1cf1872e8be34b3b
