### ISSUE TITLE
More fine-grained styling for forms

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#914]
My specific issue here is related to the fact that titles are the same size as attribute names (see below screen)
![screen shot 2015-10-27 at 12 42 59](https://cloud.githubusercontent.com/assets/1059083/10758307/97250f14-7ca8-11e5-9916-b6d6a3f626cd.png)

In this example, there's no real differentiation between the 'Popup Graphic' attributes, and the 'Graphic' attributes (with the exception of the tiny title, which is the same size as the other labels).

After a very quick check in the inspector, the HTML for both types of labels seems to be the same (i.e. no identifying classes or anything), so unfortunately, it's not just a quick CSS fix.

**Comment by brian-learningpool** [comment]
This is a pretty good enhancement.  I think a fix would involve delving into the Scaffold and possibly backbone-form-lists.js code and conditionally applying classes depending on where the property is in the hierarchy of the object.

**Comment by dancgray** [comment]
+1, this enhancement would help a lot.

**Comment by taylortom** [comment]
Fixed as of the 0.2 UI refresh.

Now have better styling, including indentation for nested items.
