### ISSUE TITLE
Error during paste of page

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#927]
Framework 2.0.4
Builder 0.1.3
Upgraded course
Cope a page from the course structure and hit the Paste button, error message appears "error during paste" and page is not pasted.

**Comment by hmaffin** [comment]
But then, when I try to preview the course I receive a huge list of "there is a block with no components". Rebooted server and browser and now two duplicate pages have appeared at the bottom of my course structure with mostly empty components

**Comment by brian-learningpool** [comment]
Hi @hmaffin, I haven't been able to re-create this with a fresh install.  Can you consistently get the error?  Is there any output in the console?

**Comment by hmaffin** [comment]
Hey Brian - I don't think this is an issue any more with the upgrade and I can't repeat it. Closing.
