### ISSUE TITLE
Spoor: edit imsmanifest.xml values

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#929]
Need a way to be able to set the values such as course title, mastery score etc. 

This may be a job for the framework build process.

**Comment by brian-learningpool** [comment]
I agree.  We could either inject this in the framework build process (reading the values from course.json or config.json), or create the imsmanifest.xml as part of the authoring tool build process.

This is also a framework issue so maybe we should go with the framework solution?

**Comment by moloko** [comment]
I agree this should be a framework solution

**Comment by taylortom** [comment]
Did we get anywhere with this?

**Comment by moloko** [comment]
course title & description are done via the framework
putting the mastery score in the manifest is rarely a good idea (it hands control of setting the lesson status to the lms which is not a good idea)
the only think that's missing is some way of generating a unique id for the course to go wherever you currently see 'adapt_' in the manifest. but that's pretty low priority, most lmses don't seem to care that this isn't set properly
