### ISSUE TITLE
Uploading New Theme Fails, Causes CPU to max to 100%

### ISSUE THREAD

**Issue by Si1kIfY** [adaptlearning/adapt_authoring#981]
Hi all, am using adapt_authoring through the Vagrant container and getting a strange bug, steps below:

1. `vagrant up`
2. Login with default user / password
3. Go to Plugin Upload page - http://localhost:5000/#/pluginManagement/upload
4. Select si1kify-theme.zip file (custom theme based off vanilla, made sure there are no extra files in the zip and has the same structure as vanilla)
5. Error pops up (no error message given)
6. Frontend no longer available (no data received)
7. VM rapidly races to 100% CPU
8. VM crashes

Browser console output:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:5000/api/upload/contentplugin Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
```

Don't know if this helps but If I perform the same steps above using adapt-contrib-vanilla.zip I get an error:
```
Error: MongooseDB#retrieve: Failed to retrieve model with name themetype
```

Bug is reproducible for me, i'll set up a new vagrant instance later today to test if it happens on a fresh install

Cheers

**Comment by brian-learningpool** [comment]
Hi, thanks for raising this.  When you say that the theme plugin you've uploaded is based off vanilla, have you actually changed any of the properties in the bower.json to give it a unique identifier?  Was there anything in the server console output?

**Comment by Si1kIfY** [comment]
Hey @brian-learningpool, feel free to close this, after much debugging I figured out the theme needs to be zipped in a root folder structure (should have read the docs better), doing this fixed the problem

Cheers
