### ISSUE TITLE
Add a double confirmation if the user attempts to delete a shared course

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#986]
The user should be prompted twice before they complete an action that they cannot undo.

**Comment by taylortom** [comment]
@michael-palmer any thoughts on this one?

**Comment by taylortom** [comment]
TODO check if this has been added

**Comment by taylortom** [comment]
Rather than add an extra confirmation, how about we add a timer to stop the user clicking the confirm button immediately?

There are quite a few services using this approach
