### ISSUE TITLE
'Newer version of framework available' message slightly misleading/unhelpful

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#988]
Scenario: 
- Latest code cloned/downloaded from GitHub
- Install process completed
- 'Framework out of date' message displayed on first run

It's likely that the `version.json` value will always be behind the latest release on GitHub, as we often need to test/make changes to make a release authoring tool compatible (the current value is set to 2.0.1 for example). 

My suggestion is to either remove this message, or be clearer when updating the framework to an 'unsupported' version. Not sure how best to do this -- simplest option may be to add an extra value to `versions.json` so we have installed version _and_ the latest supported/tested version.

**Comment by brian-learningpool** [comment]
+1, we should definitely address this.

**Comment by taylortom** [comment]
Fixed
