### ISSUE TITLE
Allow the user to view the _id of of contentobjects, articles, blocks, components

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#989]
We should provide a user friendly way of displaying the _id value to the user, so that it can be used in plugins that require it, e.g. assessment, or within inline HTML for things like routing to other course pages from hyperlinks.

One possible way of doing this is via a Copy ID to Clipboard type option, which would be part of the settings cog available on pages/menus, articles, blocks and components.  This makes sense as the _id is the ObjectID straight from MongoDB and not particularly readable from a usability perspective.  Persisting it on the clipboard might be enough, rather than cluttering the UI with such_id values.

**Comment by markl55** [comment]
+1 agree on the clutter and the implementation of adding the feature to copy to clipboard in the cog.
