### ISSUE TITLE
Support for arrays of strings

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#994]
Support for arrays of strings is patchy at the moment. There are a couple of blockers which require the most attention:

1. **Removing items**

 ~~You cannot remove a string from an array, even if a `confirmDelete` message is specified in the schema, likely due to this not being handled in [scaffold.js](https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/scaffold/scaffold.js#L81-L86). I don't think a confirm message is needed for this trivial task anyhow.~~ See #1008.

2. **Default items**

 ~~You cannot specify a default array of strings. If a default array is specified this becomes a placeholder string for each item added to the array.~~ See #1052.

Schema:
```json
"colours": {
  "type": "array",
  "default": [
    "red",
    "blue"
  ],
  "title": "Favourite colours",
  "inputType": "List",
  "help": "List your favourite colours."
}
```
Output:

![992](https://cloud.githubusercontent.com/assets/922987/12453911/444608a2-bf8d-11e5-840e-d546ccb68384.png)

**Comment by brian-learningpool** [comment]
@tomgreenfield, yes, this is a bit of a nuisance right now and something that has caused problems for editing the media and adapt-search properties.  We're a bit bound by our dependency on [backbone-forms](https://github.com/powmedia/backbone-forms) here though.

**Comment by brian-learningpool** [comment]
@taylortom or @tomgreenfield, any update on this?

**Comment by tomgreenfield** [comment]
See above for PRs that have been merged into develop.
