### ISSUE TITLE
Support for third party system integration.

### ISSUE THREAD

**Issue by ryangadams** [adaptlearning/adapt_authoring#997]
At Learning Pool, we have a requirement to integrate the Adapt Authoring tool with third party systems.  We've created a custom plugin to handle interface integration, but we need to keep track of relationships between the two systems.

We've considered the right approach to this, trying to make the solution work without a core change.  We're trying to keep the level of integration very light – we don't want to embed too much information from the external system into the authoring tool.

We've arrived at the approach outlined below, and are happy to implement the solution if it gains approval.

We want to add a new property to the course schema to allow us to store references to the current course on external systems. Extensions could then make use of that reference to add functionality to the course.

We suggest adding the following item to the [courseSchema](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/course/model.schema)

    "externalReferences": {
      "type" : "object"
    }

The externalReference would be a URI which represents the Adapt Course in the external system.

We suggest that the externalReference is defined as a URI stored against a property which identifies the system. The property name should be unique and should be prefixed with the integration type (e.g. projectmanagement, lms, comments, billing) and suffixed with the system name (e.g. projectmanagement_jira, projectmanagement_trello, projectmanagement_basecamp).

(These are not what Learning Pool are doing)
# Example - Commenting system #
A developer wants to create a system for commenting on an Adapt Course. They like the disqus system and want to embed Disqus on the course, having a unique comment thread for each course. The adapt-comment-disqus plugin needs to link the Adapt Course with the Thread, and to do that it stores an externalReference to the thread in the course schema.

The course object then has the following property (in object notation)

    course.externalReferences.comments_disqus = 'https://example.com/disqus/threads/:threadId'

# Example - Project Management System #
An e-learning organisation using Adapt Authoring tool for producing e-learning for customers needs to access project management resources relevant to the course they're creating.

They use Trello, and have a board created for each course they create.

They've created a simple plugin that links to the Trello board from the course, and need to keep relate the Trello board with the Course.

The course object then has the following property
    
    course.externalReferences.projectmanagement_trello = 'https://trello.com/b/BOARDID/NAMEOFTHEBOARD'

**Comment by dancgray** [comment]
@ryangadams looks really interesting, I'm assuming you are talking about authoring tool plugin not framework plugin?

**Comment by ryangadams** [comment]
@dancgray yes. I imagine plugin developers creating custom interfaces allowing teams to manage course development in Jira or Trello.  All that's required is the id from the 3 party system to hang hooks off.
